import type { RecyclingCollectionPoint } from "@/lib/csdi/types";

const BOOKS_FOR_LOVE_WASTE_TYPE = "Books";

const BOOKS_FOR_LOVE_CAMPAIGN = {
  id: "books-for-love-2026",
  officialUrl: "https://cloud.edm.swireproperties.com/2026BookCollection",
} as const;

const BGCA_HOURS_EN =
  "Mon 2pm–6pm; Tue 10am–6pm; Wed–Fri 2pm–10pm; Sat 10am–10pm; closed Sun & public holidays";
const BGCA_HOURS_TC =
  "星期一 2pm–6pm；星期二 10am–6pm；星期三至五 2pm–10pm；星期六 10am–10pm；星期日及公眾假期休息";

function point(
  id: string,
  district: string,
  nameEn: string,
  addressEn: string,
  addressTc: string,
  lat: number,
  lng: number,
  phone: string,
  openhourEn: string,
  openhourTc: string,
): RecyclingCollectionPoint {
  return {
    cp_id: id,
    cp_state: "Short-term",
    district_id: district,
    address_en: nameEn,
    address2_en: addressEn,
    address_tc: nameEn,
    address2_tc: addressTc,
    address_sc: null,
    address2_sc: null,
    lat,
    lng,
    waste_type: BOOKS_FOR_LOVE_WASTE_TYPE,
    legend: "Books for Love @ $10 — BGCA book collection (Jan 2026)",
    accessibilty_notes: null,
    contact_en: `Tel: ${phone}. Good-condition books only — see campaign guidelines.`,
    contact_tc: `電話：${phone}。只接受狀態良好的書籍，詳情請参阅收書準則。`,
    contact_sc: null,
    openhour_en: openhourEn,
    openhour_tc: openhourTc,
    openhour_sc: null,
    campaign_source: BOOKS_FOR_LOVE_CAMPAIGN.id,
    campaign_url: BOOKS_FOR_LOVE_CAMPAIGN.officialUrl,
    is_short_term: true,
  };
}

const COLLECTION_HOURS_EN = "Collection: 1 Jan – 31 Jan 2026 (during venue opening hours)";
const COLLECTION_HOURS_TC = "收書期：2026年1月1日至31日（場地開放時間內）";

function swirePoint(
  id: string,
  district: string,
  nameEn: string,
  addressEn: string,
  addressTc: string,
  lat: number,
  lng: number,
): RecyclingCollectionPoint {
  return {
    cp_id: id,
    cp_state: "Short-term",
    district_id: district,
    address_en: nameEn,
    address2_en: addressEn,
    address_tc: nameEn,
    address2_tc: addressTc,
    address_sc: null,
    address2_sc: null,
    lat,
    lng,
    waste_type: BOOKS_FOR_LOVE_WASTE_TYPE,
    legend: "Books for Love @ $10 — Swire Properties collection box (Jan 2026)",
    accessibilty_notes: null,
    contact_en: "Accepts good-condition paperback & hardcover books. See official guidelines.",
    contact_tc: "接受狀態良好的書籍。詳情請参阅官方收書準則。",
    contact_sc: null,
    openhour_en: COLLECTION_HOURS_EN,
    openhour_tc: COLLECTION_HOURS_TC,
    openhour_sc: null,
    campaign_source: BOOKS_FOR_LOVE_CAMPAIGN.id,
    campaign_url: BOOKS_FOR_LOVE_CAMPAIGN.officialUrl,
    is_short_term: true,
  };
}

/** Swire Properties collection boxes — source: official campaign page */
export const SWIRE_BOOK_COLLECTION_POINTS: RecyclingCollectionPoint[] = [
  swirePoint(
    "bfl-2026-swire-berkshire-house",
    "Eastern",
    "Berkshire House, Taikoo Place",
    "G/F, near Information Desk",
    "太古坊濠豐大廈地下，顧客服務台附近",
    22.2878,
    114.2135,
  ),
  swirePoint(
    "bfl-2026-swire-pccw-tower",
    "Eastern",
    "PCCW Tower, Taikoo Place",
    "1/F, near Pret A Manger",
    "太古坊電訊盈科中心1樓，Pret A Manger附近",
    22.2862,
    114.2112,
  ),
  swirePoint(
    "bfl-2026-swire-dorset-house",
    "Eastern",
    "Dorset House, Taikoo Place",
    "1/F, near Information Desk",
    "太古坊多盛大廈1樓，顧客服務台附近",
    22.287,
    114.212,
  ),
  swirePoint(
    "bfl-2026-swire-lincoln-house",
    "Eastern",
    "Lincoln House, Taikoo Place",
    "1/F, Linkbridge near lift lobby",
    "太古坊林肯大廈1樓行人天橋，升降機大堂附近",
    22.2868,
    114.2125,
  ),
  swirePoint(
    "bfl-2026-swire-one-taikoo-place",
    "Eastern",
    "One Taikoo Place",
    "G/F, near Information Desk",
    "太古坊一座地下，顧客服務台附近",
    22.2872,
    114.213,
  ),
  swirePoint(
    "bfl-2026-swire-two-taikoo-place",
    "Eastern",
    "Two Taikoo Place",
    "G/F, near Information Desk",
    "太古坊二座地下，顧客服務台附近",
    22.2875,
    114.2132,
  ),
  swirePoint(
    "bfl-2026-swire-one-island-east",
    "Eastern",
    "One Island East",
    "2/F, near escalator",
    "鰂魚涌港島東中心2樓，扶手電梯附近",
    22.2845,
    114.2155,
  ),
  swirePoint(
    "bfl-2026-swire-oxford-house",
    "Eastern",
    "Oxford House, Taikoo Place",
    "2/F, near escalator",
    "太古坊濠庭大廈2樓，扶手電梯附近",
    22.2868,
    114.2128,
  ),
  swirePoint(
    "bfl-2026-swire-cityplaza-gf",
    "Eastern",
    "Cityplaza",
    "G/F, near Singapoke Shop (SH1)",
    "太古城中心地下，Singapoke Shop (SH1) 附近",
    22.2847,
    114.2173,
  ),
  swirePoint(
    "bfl-2026-swire-cityplaza-ice",
    "Eastern",
    "Cityplaza Ice Palace",
    "2/F, Cityplaza Ice Palace",
    "太古城中心2樓冰上皇宫",
    22.285,
    114.217,
  ),
  swirePoint(
    "bfl-2026-swire-cityplaza-bridge",
    "Eastern",
    "Cityplaza Centre Bridge",
    "2/F Centre Bridge, opposite Customer Service Counter",
    "太古城中心2樓中橋，顧客服務台對面",
    22.2848,
    114.2168,
  ),
  swirePoint(
    "bfl-2026-swire-pp-mall",
    "Central_Western",
    "Pacific Place (Mall)",
    "L2, near Concierge Desk",
    "太古廣場商場2樓，禮賓部附近",
    22.2774,
    114.1633,
  ),
  swirePoint(
    "bfl-2026-swire-one-pacific-place",
    "Central_Western",
    "One Pacific Place",
    "4/F, office lift lobby",
    "太古廣場一座4樓，寫字樓升降機大堂",
    22.277,
    114.164,
  ),
  swirePoint(
    "bfl-2026-swire-two-pacific-place",
    "Central_Western",
    "Two Pacific Place",
    "4/F, office lift lobby",
    "太古廣場二座4樓，寫字樓升降機大堂",
    22.2768,
    114.1638,
  ),
  swirePoint(
    "bfl-2026-swire-three-pacific-place",
    "Central_Western",
    "Three Pacific Place",
    "B1/F, office lift lobby",
    "太古廣場三座B1樓，寫字樓升降機大堂",
    22.2772,
    114.1635,
  ),
  swirePoint(
    "bfl-2026-swire-six-pacific-place",
    "Central_Western",
    "Six Pacific Place",
    "1/F, office lift lobby",
    "太古廣場六座1樓，寫字樓升降機大堂",
    22.2765,
    114.1642,
  ),
  swirePoint(
    "bfl-2026-swire-one-citygate",
    "Islands",
    "One Citygate, Tung Chung",
    "G/F, office lift lobby",
    "東涌One Citygate地下，寫字樓升降機大堂",
    22.289,
    114.941,
  ),
  swirePoint(
    "bfl-2026-swire-citygate-jins",
    "Islands",
    "Citygate Outlets",
    "L1, near JINS (Shop 111)",
    "東薈城名店倉1樓，JINS (111號舖) 附近",
    22.2892,
    114.9413,
  ),
  swirePoint(
    "bfl-2026-swire-citygate-skechers",
    "Islands",
    "Citygate Outlets",
    "L2, near Skechers (Shop 215)",
    "東薈城名店倉2樓，Skechers (215號舖) 附近",
    22.2895,
    114.941,
  ),
  swirePoint(
    "bfl-2026-swire-citygate-csc",
    "Islands",
    "Citygate Outlets",
    "L2, near Customer Care Centre",
    "東薈城名店倉2樓，顧客關係中心附近",
    22.2893,
    114.9412,
  ),
  swirePoint(
    "bfl-2026-swire-island-place-mall",
    "Eastern",
    "Island Place (Mall), North Point",
    "G/F, near lift lobby",
    "北角港運城商場地下，升降機大堂附近",
    22.29,
    114.2,
  ),
  swirePoint(
    "bfl-2026-swire-island-place-tower",
    "Eastern",
    "Island Place Tower, North Point",
    "G/F, office lift lobby",
    "北角港運城辦公大樓地下，寫字樓升降機大堂",
    22.2902,
    114.2005,
  ),
  swirePoint(
    "bfl-2026-swire-south-island-place",
    "Southern",
    "South Island Place, Wong Chuk Hang",
    "G/F, office lift lobby",
    "黃竹坑南島坊地下，寫字樓升降機大堂",
    22.2485,
    114.1535,
  ),
];

/** Agency for Volunteer Service collection points — source: official campaign page */
export const AVS_BOOK_COLLECTION_POINTS: RecyclingCollectionPoint[] = [
  {
    cp_id: "bfl-2026-avs-volunteer-chai-wan",
    cp_state: "Short-term",
    district_id: "Eastern",
    address_en: "Volunteer Action Centre (AVS)",
    address2_en: "1/F, Yue Wan Estate, Chai Wan",
    address_tc: "義務工作發展局義工服務中心",
    address2_tc: "柴灣漁灣邨1樓",
    address_sc: null,
    address2_sc: null,
    lat: 22.264,
    lng: 114.237,
    waste_type: BOOKS_FOR_LOVE_WASTE_TYPE,
    legend: "Books for Love @ $10 — AVS book collection (Jan 2026)",
    accessibilty_notes: null,
    contact_en: "Tel: 2546 0694. Mon–Fri 9am–6pm; closed Sat, Sun & public holidays.",
    contact_tc: "電話：2546 0694。星期一至五 9am–6pm；星期六、日及公眾假期休息。",
    contact_sc: null,
    openhour_en: "Collection: 1 Jan – 31 Jan 2026",
    openhour_tc: "收書期：2026年1月1日至31日",
    openhour_sc: null,
    campaign_source: BOOKS_FOR_LOVE_CAMPAIGN.id,
    campaign_url: BOOKS_FOR_LOVE_CAMPAIGN.officialUrl,
    is_short_term: true,
  },
  {
    cp_id: "bfl-2026-avs-hkiv-kwai-chung",
    cp_state: "Short-term",
    district_id: "Kwai_Tsing",
    address_en: "Hong Kong Institute of Volunteers (AVS)",
    address2_en: "Unit 1-11, G/F, Block B, 6 Hing Shing Road, Kwai Chung",
    address_tc: "香港義工學院（義務工作發展局）",
    address2_tc: "葵涌興盛路6號B座地下1-11室",
    address_sc: null,
    address2_sc: null,
    lat: 22.358,
    lng: 114.127,
    waste_type: BOOKS_FOR_LOVE_WASTE_TYPE,
    legend: "Books for Love @ $10 — AVS book collection (Jan 2026)",
    accessibilty_notes: null,
    contact_en: "Tel: 2865 2520. Mon–Fri 9am–6pm; closed Sat, Sun & public holidays.",
    contact_tc: "電話：2865 2520。星期一至五 9am–6pm；星期六、日及公眾假期休息。",
    contact_sc: null,
    openhour_en: "Collection: 1 Jan – 31 Jan 2026",
    openhour_tc: "收書期：2026年1月1日至31日",
    openhour_sc: null,
    campaign_source: BOOKS_FOR_LOVE_CAMPAIGN.id,
    campaign_url: BOOKS_FOR_LOVE_CAMPAIGN.officialUrl,
    is_short_term: true,
  },
];

/** BGCA collection points — source: Books for Love @ $10 2026 campaign list */
export const BGCA_BOOK_COLLECTION_POINTS: RecyclingCollectionPoint[] = [
  point(
    "bfl-2026-bgca-hq",
    "Wan_Chai",
    "The Boys' & Girls' Clubs Association of Hong Kong",
    "3 Lockhart Road, Wan Chai",
    "灣仔駱克道3號",
    22.277,
    114.1685,
    "2527 9121",
    "Mon–Sat 9am–10pm; closed Sun & public holidays",
    "星期一至六 9am–10pm；星期日及公眾假期休息",
  ),
  point(
    "bfl-2026-volunteer-action-centre",
    "Central_Western",
    "Volunteer Action Centre",
    "1/F, Yuen Fai Court, 6 Sai Yuen Lane, Sai Ying Pun",
    "西營盤西源里6號源輝閣1樓",
    22.2865,
    114.1405,
    "2546 0694",
    "Mon–Fri 10am–6pm; closed Sat, Sun & public holidays",
    "星期一至五 10am–6pm；星期六、日及公眾假期休息",
  ),
  point(
    "bfl-2026-sheung-wan",
    "Central_Western",
    "Jockey Club Sheung Wan Children & Youth Integrated Services Centre",
    "11/F, Sheung Wan Municipal Services Building, 345 Queen's Road Central",
    "香港皇后大道中345號上環市政大廈11樓",
    22.285,
    114.148,
    "2850 7237",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-south-horizons",
    "Southern",
    "Jockey Club South Horizons Children & Youth Integrated Services Centre",
    "2/F, South Horizons Neighbourhood Community Centre, Marina Square East Centre, Ap Lei Chau",
    "香港鴨脷洲海怡半島海韻東商場2樓",
    22.243,
    114.148,
    "2552 2111",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-wah-kwai",
    "Southern",
    "Jockey Club Southern District Children & Youth Integrated Services Centre",
    "1/F & 3/F, Wah Kwai Community Centre, Wah Kwai Estate, Aberdeen",
    "香港香港仔華貴邨華貴社區中心1及3樓",
    22.252,
    114.138,
    "2550 3622",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-yau-tong",
    "Kwun_Tong",
    "Jockey Club Yau Tong Children & Youth Integrated Services Centre",
    "No. 1, 3/F, Carpark Block, Ko Cheung Court, Yau Tong",
    "九龍油塘高翔苑停車場大廈3樓1號",
    22.296,
    114.239,
    "2343 3554",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-sau-mau-ping",
    "Kwun_Tong",
    "Jockey Club Sau Mau Ping Children & Youth Integrated Services Centre",
    "G/F, Sau Lok House, Sau Mau Ping (III) Estate, Kwun Tong",
    "九龍觀塘秀茂坪（III）邨秀樂樓地下",
    22.319,
    114.234,
    "2348 0636",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-lai-kok",
    "Sham_Shui_Po",
    "Jockey Club Cheung Sha Wan Children & Youth Integrated Services Centre",
    "Room 101-120, G/F, Lai Ho House, Lai Kok Estate, Sham Shui Po",
    "九龍深水埗麗閣邨麗荷樓地下101-120室",
    22.335,
    114.155,
    "2729 2294",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-mei-foo",
    "Sham_Shui_Po",
    "Mei Foo Children & Youth Integrated Services Centre",
    "4/F & 5/F, Mei Foo Government Complex Building, 33 Mei Lai Road, Sham Shui Po",
    "九龍深水埗美荔道33號美孚政府合署4及5樓",
    22.338,
    114.138,
    "2741 6294",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-tsz-wan-shan",
    "Wong_Tai_Sin",
    "Jockey Club Tsz Wan Shan Children & Youth Integrated Services Centre",
    "Rm. 203, 1/F, Lung Poon Court Commercial Centre, Diamond Hill",
    "九龍鑽石山龍蟠苑商場1樓203室",
    22.342,
    114.201,
    "2320 4005",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-shek-yam",
    "Kwai_Tsing",
    "Jockey Club Shek Yam Children & Youth Integrated Services Centre",
    "G/F & 1/F, Yam Yue House, Shek Yam East Estate, Kwai Chung",
    "新界葵涌石蔭東邨蔭悦樓地下及1樓",
    22.358,
    114.141,
    "2481 3222",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-fanling",
    "North",
    "Jockey Club Fanling Children & Youth Integrated Services Centre",
    "G/F, Fuk Tai House, Ka Fuk Estate, Fan Ling",
    "新界粉嶺嘉福邨嘉泰樓地下",
    22.498,
    114.142,
    "2676 2392",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-tai-wai",
    "Sha_Tin",
    "Tai Wai Children & Youth Integrated Services Centre",
    "1/F, Tai Wai Social Service Building, 1 Mei Tin Road, Tai Wai",
    "新界沙田大圍美田路1號大圍社會服務樓1樓",
    22.373,
    114.178,
    "2694 9322",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-ma-on-shan",
    "Sha_Tin",
    "Jockey Club Ma On Shan Children & Youth Integrated Services Centre",
    "1/F, Kam Tai Shopping Centre, Kam Tai Court, Ma On Shan",
    "新界沙田馬鞍山錦泰苑錦泰商場1樓",
    22.425,
    114.231,
    "2641 7999",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-ma-on-shan-east",
    "Sha_Tin",
    "Ma On Shan East Children & Youth Integrated Services Centre",
    "2/F, Ma On Shan Lee On Community Services Complex, 23 Sha On Street",
    "新界沙田馬鞍山沙安街23號馬鞍山利安社區服務綜合大樓2樓",
    22.428,
    114.238,
    "2663 5088",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-kwong-lam",
    "Sha_Tin",
    "Community Creative Learning Centre",
    "G/F, Fook Lam House, Kwong Lam Court, Sha Tin",
    "新界沙田廣林苑馥林閣地下",
    22.378,
    114.195,
    "2338 0160",
    "Tue & Thu 1:30pm–5:30pm; Fri 1:30pm–9:30pm; Sat 9:30am–5:30pm; closed Wed, Sun & public holidays",
    "星期二、四 1:30pm–5:30pm；星期五 1:30pm–9:30pm；星期六 9:30am–5:30pm；星期三、日及公眾假期休息",
  ),
  point(
    "bfl-2026-tai-po",
    "Tai_Po",
    "Jockey Club Tai Po Children & Youth Integrated Services Centre",
    "1/F & 2/F, Tai Wo Neighbourhood Community Centre, Tai Wo Estate, Tai Po",
    "新界大埔太和邨太和鄰里社區中心1及2樓",
    22.451,
    114.167,
    "2694 9322",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-sham-tseng",
    "Tsuen_Wan",
    "Sham Tseng Children & Youth Integrated Services Centre",
    "Level 5, Commercial Block, Bellagio, 33 Castle Peak Road, Sham Tseng",
    "新界深井青山公路33號碧堤坊商場5樓",
    22.367,
    114.055,
    "2641 7999",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-tuen-mun",
    "Tuen_Mun",
    "Jockey Club Tuen Mun Children & Youth Integrated Services Centre",
    "G/F, Tower 1, Tai Hing Gardens Phase II, Tuen Mun",
    "新界屯門大興花園第2期1座地下",
    22.402,
    113.968,
    "2641 7994",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
  point(
    "bfl-2026-tseung-kwan-o",
    "Sai_Kung",
    "Jockey Club Tseung Kwan O Children & Youth Integrated Services Centre",
    "2/F, East Wing, Po Kan House, Po Lam Estate, Tseung Kwan O",
    "新界將軍澳寶林邨寶勤樓東翼2樓",
    22.322,
    114.258,
    "3525 0440",
    BGCA_HOURS_EN,
    BGCA_HOURS_TC,
  ),
];

/** May 2026 charity sale venues at Taikoo Place (Swire Properties) */
export const BOOKS_SALE_VENUE_POINTS: RecyclingCollectionPoint[] = [
  {
    cp_id: "bfl-2026-artistree",
    cp_state: "Short-term",
    district_id: "Eastern",
    address_en: "ArtisTree, 1/F Cambridge House, Taikoo Place",
    address2_en: "Charity book sale venue (May 2026)",
    address_tc: "ArtisTree，太古坊康橋大廈1樓",
    address2_tc: "實體書籍義賣場地（2026年5月）",
    address_sc: null,
    address2_sc: null,
    lat: 22.2865,
    lng: 114.2122,
    waste_type: BOOKS_FOR_LOVE_WASTE_TYPE,
    legend: "In-person sale: 7–10 & 14–17 May 2026, 12pm–8pm",
    accessibilty_notes: null,
    contact_en: "HK$10 per book. Proceeds to BGCA & AVS.",
    contact_tc: "每本港幣10元，收益撥捐小童群益會及義務工作發展局。",
    contact_sc: null,
    openhour_en: "Sale: 7–10 & 14–17 May 2026",
    openhour_tc: "義賣：2026年5月7至10日及14至17日",
    openhour_sc: null,
    campaign_source: BOOKS_FOR_LOVE_CAMPAIGN.id,
    campaign_url: BOOKS_FOR_LOVE_CAMPAIGN.officialUrl,
    is_short_term: true,
  },
  {
    cp_id: "bfl-2026-berkshire-house",
    cp_state: "Short-term",
    district_id: "Eastern",
    address_en: "Berkshire House, 18/F, Taikoo Place",
    address2_en: "Charity book sale venue (May 2026)",
    address_tc: "太古坊栢克大廈18樓",
    address2_tc: "實體書籍義賣場地（2026年5月）",
    address_sc: null,
    address2_sc: null,
    lat: 22.2878,
    lng: 114.2135,
    waste_type: BOOKS_FOR_LOVE_WASTE_TYPE,
    legend: "In-person sale: 7–10 & 14–17 May 2026, 12pm–8pm",
    accessibilty_notes: null,
    contact_en: "HK$10 per book. Proceeds to BGCA & AVS.",
    contact_tc: "每本港幣10元，收益撥捐小童群益會及義務工作發展局。",
    contact_sc: null,
    openhour_en: "Sale: 7–10 & 14–17 May 2026",
    openhour_tc: "義賣：2026年5月7至10日及14至17日",
    openhour_sc: null,
    campaign_source: BOOKS_FOR_LOVE_CAMPAIGN.id,
    campaign_url: BOOKS_FOR_LOVE_CAMPAIGN.officialUrl,
    is_short_term: true,
  },
];
