import type { RecyclingCollectionPoint } from "@/lib/csdi/types";

const WASTE_TYPE = "Contact Lens Cases";
const CAMPAIGN_ID = "contact-lens-easy-case-recycling";
const PROGRAM_URL = "https://www.contactlenseasy.com/con%E6%AE%BC%E5%9B%9E%E6%94%B6%E8%A2%8B/";

function buildPoint(
  id: string, district: string, nameEn: string, addressEn: string,
  nameTc: string, addressTc: string, noteEn: string, noteTc: string,
  lat: number, lng: number,
): RecyclingCollectionPoint {
  const contactEn = noteEn
    ? `Contact Lens Easy CON case & foil recycling. ${noteEn}. Clean and dry cases and foil separately before drop-off.`
    : "Contact Lens Easy CON case & foil recycling. Clean and dry contact lens cases and foil separately before drop-off.";
  const contactTc = noteTc
    ? `Contact Lens Easy CON殼錫紙回收。${noteTc}。請將CON殼及錫紙面分類、清潔並抹乾後投放。`
    : "Contact Lens Easy CON殼錫紙回收。請將CON殼及錫紙面分類、清潔並抹乾後投放。";
  return {
    cp_id: id,
    cp_state: "Accepted",
    district_id: district,
    address_en: nameEn,
    address2_en: addressEn,
    address_tc: nameTc,
    address2_tc: addressTc,
    address_sc: null,
    address2_sc: null,
    lat,
    lng,
    waste_type: WASTE_TYPE,
    legend: "Contact Lens Easy — CON case & foil recycling (ongoing programme)",
    accessibilty_notes: null,
    contact_en: contactEn,
    contact_tc: contactTc,
    contact_sc: null,
    openhour_en: "Opening hours vary by venue — see official programme page",
    openhour_tc: "營業時間視乎個別地點而定，請参阅官方計劃頁面",
    openhour_sc: null,
    campaign_source: CAMPAIGN_ID,
    campaign_url: PROGRAM_URL,
    is_short_term: false,
  };
}

export const CONTACT_LENS_CASE_POINTS: RecyclingCollectionPoint[] = [
  buildPoint("cle-mr-optical","Sham_Shui_Po","Mr. Optical 盈采眼鏡","香港西環皇后大道西425L後座地下","Mr. Optical 盈采眼鏡","香港西環皇后大道西425L後座地下","","",22.32,114.17),
  buildPoint("cle-shun-tak-centre","Sham_Shui_Po","Shun Tak Centre 信德中心","上環干諾道中200號信德中心 （信德中心西座2/F禮賓部 及 信德中心招商局大廈2/F禮賓部）","Shun Tak Centre 信德中心","上環干諾道中200號信德中心 （信德中心西座2/F禮賓部 及 信德中心招商局大廈2/F禮賓部）","","",22.32,114.17),
  buildPoint("cle-the-westwood","Sham_Shui_Po","The Westwood 西寶城","香港堅尼地城卑路乍街8號UG/F客戶服務台","The Westwood 西寶城","香港堅尼地城卑路乍街8號UG/F客戶服務台","","",22.32,114.17),
  buildPoint("cle-h-coffee-shop","Sham_Shui_Po","H. Coffee & Shop","灣仔駱克道150-158號祥友大廈1樓A室","H. Coffee & Shop","灣仔駱克道150-158號祥友大廈1樓A室","","",22.32,114.17),
  buildPoint("cle-33","Sham_Shui_Po","德輔道西33號","香港西營盤德輔道西33號","德輔道西33號","香港西營盤德輔道西33號","","",22.32,114.17),
  buildPoint("cle-8","Sham_Shui_Po","雲咸街8號","中環雲咸街8號","雲咸街8號","中環雲咸街8號","","",22.32,114.17),
  buildPoint("cle-point","Sham_Shui_Po","兆豐大廈","灣仔莊士敦道51-53號","兆豐大廈","灣仔莊士敦道51-53號","","",22.32,114.17),
  buildPoint("cle-point-2","Sham_Shui_Po","中安大廈","中環安蘭街11-15號","中安大廈","中環安蘭街11-15號","","",22.32,114.17),
  buildPoint("cle-point-3","Sham_Shui_Po","新卓管理有限公司 - 南豐大廈","上環干諾道中88號","新卓管理有限公司 - 南豐大廈","上環干諾道中88號","","",22.32,114.17),
  buildPoint("cle-ojo-de-bella","Sham_Shui_Po","OJO de Bella (銅鑼灣總店)","香港灣仔駱克道492號順禧銅鑼灣中心5樓全層","OJO de Bella (銅鑼灣總店)","香港灣仔駱克道492號順禧銅鑼灣中心5樓全層","","",22.32,114.17),
  buildPoint("cle-kaka-beauty","Sham_Shui_Po","KaKa Beauty 嘉嘉美容纖體中心","香港仔華富邨華安樓128號地下","KaKa Beauty 嘉嘉美容纖體中心","香港仔華富邨華安樓128號地下","","",22.32,114.17),
  buildPoint("cle-dynasty-court","Sham_Shui_Po","Dynasty Court 帝景園","中半山舊山頂道17-23號 （第一座地下服務處）","Dynasty Court 帝景園","中半山舊山頂道17-23號 （第一座地下服務處）","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-allied-world-assurance-company-limited","Sham_Shui_Po","Allied World Assurance Company Limited","鰂魚涌太古坊18號華蘭路港島東中心22樓","Allied World Assurance Company Limited","鰂魚涌太古坊18號華蘭路港島東中心22樓","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-aigburth","Sham_Shui_Po","Aigburth 譽皇居會所","中半山地利根德里12號10樓","Aigburth 譽皇居會所","中半山地利根德里12號10樓","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-cooley-hk","Sham_Shui_Po","Cooley HK","35/F, Two Exchange Square, 8 Connaught Place, Central, Hong Kong","Cooley HK","35/F, Two Exchange Square, 8 Connaught Place, Central, Hong Kong","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-kerry-centre","Sham_Shui_Po","Kerry Centre 嘉里中心","香港鰂魚涌英皇道683號嘉里中心 L1","Kerry Centre 嘉里中心","香港鰂魚涌英皇道683號嘉里中心 L1","Staff only","只限租戶及內部員工",22.32,114.17),
  buildPoint("cle-meta-hong-kong","Sham_Shui_Po","Meta Hong Kong","太古坊一座47樓","Meta Hong Kong","太古坊一座47樓","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-reed-smith-richards-butler-llp","Sham_Shui_Po","Reed Smith Richards Butler LLP","17/F, One Island East, 18 Westlands Road, Taikoo Place, Quarry Bay, Hong Kong","Reed Smith Richards Butler LLP","17/F, One Island East, 18 Westlands Road, Taikoo Place, Quarry Bay, Hong Kong","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-residence-bel-air","Sham_Shui_Po","Residence Bel-Air 貝沙灣","香港貝沙灣道48號貝沙灣灣畔會所","Residence Bel-Air 貝沙灣","香港貝沙灣道48號貝沙灣灣畔會所","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-pinebridge-investments-asia-limited","Sham_Shui_Po","PineBridge Investments Asia Limited","金鐘金鐘道88號古廣場二座1411室","PineBridge Investments Asia Limited","金鐘金鐘道88號古廣場二座1411室","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-singapore-airlines-limited","Sham_Shui_Po","Singapore Airlines Limited","17th Floor United Centre, 95 Queensway, Admiralty, Hong Kong","Singapore Airlines Limited","17th Floor United Centre, 95 Queensway, Admiralty, Hong Kong","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-wpp-marketing-communications-hong-kong-limited","Sham_Shui_Po","WPP Marketing Communications Hong Kong Limited","16/F, K11 Atelier King’s Road, 728 King’s Road, Quarry Bay","WPP Marketing Communications Hong Kong Limited","16/F, K11 Atelier King’s Road, 728 King’s Road, Quarry Bay","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-fwd-group-management-holdings-limited","Sham_Shui_Po","FWD Group Management Holdings Limited","太古城太古灣道14號17樓","FWD Group Management Holdings Limited","太古城太古灣道14號17樓","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-la-place-de-victoria","Sham_Shui_Po","La Place De Victoria 慧雲峯","香港北角英皇道632號","La Place De Victoria 慧雲峯","香港北角英皇道632號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-pao-yip-building","Sham_Shui_Po","Pao Yip Building 寶業大廈","香港灣仔船街1-7號","Pao Yip Building 寶業大廈","香港灣仔船街1-7號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-scmp","Sham_Shui_Po","SCMP","19/F Tower 1, Times Square, Causeway Bay, HK","SCMP","19/F Tower 1, Times Square, Causeway Bay, HK","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-jones-lang-lasalle-limited","Sham_Shui_Po","Jones Lang LaSalle Limited","7/F One Taikoo Place, Quarry Bay","Jones Lang LaSalle Limited","7/F One Taikoo Place, Quarry Bay","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-bolttech-management-limited","Sham_Shui_Po","Bolttech Management Limited","Units 2501-6, 308 Central Des Voeux, 308 Des Voeux Road Central, Hong Kong","Bolttech Management Limited","Units 2501-6, 308 Central Des Voeux, 308 Des Voeux Road Central, Hong Kong","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-contact-lens-easy","Yau_Tsim_Mong","Contact Lens Easy","尖沙咀加連威老道41C-41D號嘉威大廈1樓A室","Contact Lens Easy","尖沙咀加連威老道41C-41D號嘉威大廈1樓A室","","",22.32,114.17),
  buildPoint("cle-point-4","Sham_Shui_Po","奧海城二期","大角咀海庭道18號 奧海城二期 禮賓處","奧海城二期","大角咀海庭道18號 奧海城二期 禮賓處","","",22.32,114.17),
  buildPoint("cle-mikiki-mall","Sham_Shui_Po","MIKIKI Mall","九龍新蒲崗太子道東638號","MIKIKI Mall","九龍新蒲崗太子道東638號","","",22.32,114.17),
  buildPoint("cle-point-5","Sham_Shui_Po","荷里活廣場","香港九龍鑽石山龍蟠街3號 (一樓明星廣場客戶服務中心)","荷里活廣場","香港九龍鑽石山龍蟠街3號 (一樓明星廣場客戶服務中心)","","",22.32,114.17),
  buildPoint("cle-yue-man-square","Sham_Shui_Po","Yue Man Square 裕民坊商場","觀塘協和街33號裕民坊商場UG禮賓部","Yue Man Square 裕民坊商場","觀塘協和街33號裕民坊商場UG禮賓部","","",22.32,114.17),
  buildPoint("cle-tsim-sha-tsui-centre","Sham_Shui_Po","Tsim Sha Tsui Centre 尖沙咀中心, 帝國中心","尖沙咀麼地道66號","Tsim Sha Tsui Centre 尖沙咀中心, 帝國中心","尖沙咀麼地道66號","","",22.32,114.17),
  buildPoint("cle-point-6","Sham_Shui_Po","九龍塘又一居一期","九龍塘又一居一期","九龍塘又一居一期","九龍塘又一居一期","","",22.32,114.17),
  buildPoint("cle-point-7","Sham_Shui_Po","新科技廣場","新蒲崗大有街34號 新科技廣場UG層","新科技廣場","新蒲崗大有街34號 新科技廣場UG層","","",22.32,114.17),
  buildPoint("cle-cityusu","Sham_Shui_Po","CityUSU 香港城市大學學生會","長沙灣青山道124-126號俊薈Spark City 6樓B室","CityUSU 香港城市大學學生會","長沙灣青山道124-126號俊薈Spark City 6樓B室","","",22.32,114.17),
  buildPoint("cle-egaocohk","Sham_Shui_Po","Egaocohk 地球友善選物店 (回收前先向店舖查詢)","觀塘駿業街 66 號巧運工業大廈 2 樓 C1 室","Egaocohk 地球友善選物店 (回收前先向店舖查詢)","觀塘駿業街 66 號巧運工業大廈 2 樓 C1 室","Call shop before drop-off","回收前先向店舖查詢",22.32,114.17),
  buildPoint("cle-wind-and-sand","Sham_Shui_Po","Wind and Sand","鑽石山啟鑽商場109號鋪","Wind and Sand","鑽石山啟鑽商場109號鋪","","",22.32,114.17),
  buildPoint("cle-cordis-hotel-hong-kong","Sham_Shui_Po","Cordis Hotel Hong Kong 香港康得思酒店","香港九龍旺角上海街555號","Cordis Hotel Hong Kong 香港康得思酒店","香港九龍旺角上海街555號","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-argyle-centre-phase-i","Sham_Shui_Po","Argyle Centre Phase I 旺角中心第一座","旺角彌敦道688號旺角中心第一座16樓1612-12A室","Argyle Centre Phase I 旺角中心第一座","旺角彌敦道688號旺角中心第一座16樓1612-12A室","Tenants only","只限業戶",22.32,114.17),
  buildPoint("cle-tian-teck-group","Sham_Shui_Po","Tian Teck Group","9th Floor, iSQUARE 63 Nathan Road Tsim Sha Tsui Kowloon, Hong Kong","Tian Teck Group","9th Floor, iSQUARE 63 Nathan Road Tsim Sha Tsui Kowloon, Hong Kong","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-the-masterpiece","Sham_Shui_Po","The Masterpiece 名鑄","尖沙咀河內道18號名鑄","The Masterpiece 名鑄","尖沙咀河內道18號名鑄","Residents only","只限住客",22.32,114.17),
  buildPoint("cle-the-habourside","Sham_Shui_Po","The Habourside 君臨天下","1 Austin Rd W, Tsim Sha Tsui","The Habourside 君臨天下","1 Austin Rd W, Tsim Sha Tsui","Residents only","只限住客",22.32,114.17),
  buildPoint("cle-one-soho","Sham_Shui_Po","One Soho","旺角山東街32b號","One Soho","旺角山東街32b號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-ncb-innovation-centre","Sham_Shui_Po","NCB Innovation Centre 南商金融創新中心","長沙灣荔枝角道888號","NCB Innovation Centre 南商金融創新中心","長沙灣荔枝角道888號","Tenants only","只限商業租戶",22.32,114.17),
  buildPoint("cle-manhattan-hill","Sham_Shui_Po","Manhattan Hill 曼克頓山","荔枝角寶輪街一號曼克頓山","Manhattan Hill 曼克頓山","荔枝角寶輪街一號曼克頓山","Residents only","只限屋苑住戶及內部員工",22.32,114.17),
  buildPoint("cle-miami-quay","Sham_Shui_Po","Miami Quay","23 Shing Fung Road, Kai Tak, Kowloon","Miami Quay","23 Shing Fung Road, Kai Tak, Kowloon","Residents only","只限住戶及員工",22.32,114.17),
  buildPoint("cle-harbour-green","Sham_Shui_Po","Harbour Green 君匯港","長沙灣大角咀深旺道8號","Harbour Green 君匯港","長沙灣大角咀深旺道8號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-lions-rise","Sham_Shui_Po","Lions Rise 現祟山","黃大仙睦鄰街8號","Lions Rise 現祟山","黃大仙睦鄰街8號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-the-latitude","Sham_Shui_Po","The Latitude 譽港灣","新蒲崗太子道東638號會所大堂","The Latitude 譽港灣","新蒲崗太子道東638號會所大堂","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-lbs-group","Sham_Shui_Po","LBS Group 史偉莎","新蒲崗爵祿街33號6樓","LBS Group 史偉莎","新蒲崗爵祿街33號6樓","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-1-3-ede-road-1-3","Sham_Shui_Po","1&3 Ede Road 義德道1及3號","九龍塘義德道3號","1&3 Ede Road 義德道1及3號","九龍塘義德道3號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-mont-rouge","Sham_Shui_Po","Mont Rouge 緹山","龍駒道9號","Mont Rouge 緹山","龍駒道9號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-mont-verra","Sham_Shui_Po","Mont Verra 緹外","九龍筆架山龍駒道3號緹外會所","Mont Verra 緹外","九龍筆架山龍駒道3號緹外會所","Residents only","只限住戶及員工",22.32,114.17),
  buildPoint("cle-10-lasalle","Sham_Shui_Po","10 LaSalle 瀚名","喇沙利道10號","10 LaSalle 瀚名","喇沙利道10號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-8-lasalle","Sham_Shui_Po","8 LaSalle 傲名","喇沙利道8號","8 LaSalle 傲名","喇沙利道8號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-point-8","Sham_Shui_Po","易寶通訊服務有限公司","旺角廣東道1163號中華漆廠大廈四樓","易寶通訊服務有限公司","旺角廣東道1163號中華漆廠大廈四樓","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-point-9","Sham_Shui_Po","香港專業花式跳繩學校","九龍灣常悅道21號Eastmark 3樓12號鋪","香港專業花式跳繩學校","九龍灣常悅道21號Eastmark 3樓12號鋪","Students & staff only","只限家長及學生",22.32,114.17),
  buildPoint("cle-cullinan-west","Sham_Shui_Po","Cullinan West 匯璽","香港深水埗深旺道28號","Cullinan West 匯璽","香港深水埗深旺道28號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-point-10","Sham_Shui_Po","香港寬頻有限公司","九龍觀塘海濱道77號海濱會1座及2座11樓及19樓","香港寬頻有限公司","九龍觀塘海濱道77號海濱會1座及2座11樓及19樓","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-point-11","Sham_Shui_Po","慕光英文書院","香港觀塘功樂道55號","慕光英文書院","香港觀塘功樂道55號","Staff only","只限員工及學生",22.32,114.17),
  buildPoint("cle-hong-kong-baptist-university","Sham_Shui_Po","Hong Kong Baptist University 香港浸會大學","逸夫校園永隆銀行商學大樓401室大堂(WLB 401)","Hong Kong Baptist University 香港浸會大學","逸夫校園永隆銀行商學大樓401室大堂(WLB 401)","Students & staff only","只限學生及教師",22.32,114.17),
  buildPoint("cle-hong-kong-baptist-university-2","Sham_Shui_Po","Hong Kong Baptist University 香港浸會大學","羅肇唐書院大堂大堂（只限學生及教師）","Hong Kong Baptist University 香港浸會大學","羅肇唐書院大堂大堂（只限學生及教師）","Students & staff only","只限學生及教師",22.32,114.17),
  buildPoint("cle-hong-kong-baptist-university-3","Sham_Shui_Po","Hong Kong Baptist University 香港浸會大學","CARE 舍堂村書院一及書院三大堂","Hong Kong Baptist University 香港浸會大學","CARE 舍堂村書院一及書院三大堂","Students & staff only","只限學生及教師",22.32,114.17),
  buildPoint("cle-hong-kong-baptist-university-4","Sham_Shui_Po","Hong Kong Baptist University 香港浸會大學","陳瑞槐夫人胡尹桂女士持續教育大樓地下 Green Corner (ACC G/F)","Hong Kong Baptist University 香港浸會大學","陳瑞槐夫人胡尹桂女士持續教育大樓地下 Green Corner (ACC G/F)","Students & staff only","只限學生及教師",22.32,114.17),
  buildPoint("cle-hong-kong-baptist-university-5","Sham_Shui_Po","Hong Kong Baptist University 香港浸會大學","吳多泰博士國際中心 NTT International House 大堂","Hong Kong Baptist University 香港浸會大學","吳多泰博士國際中心 NTT International House 大堂","Students & staff only","只限學生及教師",22.32,114.17),
  buildPoint("cle-hong-kong-baptist-university-6","Sham_Shui_Po","Hong Kong Baptist University 香港浸會大學","李作權大道 (保安控制室對出)","Hong Kong Baptist University 香港浸會大學","李作權大道 (保安控制室對出)","Students & staff only","只限學生及教師",22.32,114.17),
  buildPoint("cle-the-city-university-of-hong-kong","Sham_Shui_Po","The City University of Hong Kong 香港城市大學","香港城市大學 南山樓地下","The City University of Hong Kong 香港城市大學","香港城市大學 南山樓地下","Students & staff only","只限學生及教師",22.32,114.17),
  buildPoint("cle-the-city-university-of-hong-kong-2","Sham_Shui_Po","The City University of Hong Kong 香港城市大學","賽馬會敬賢堂公共空間 Hall 1 Common Room","The City University of Hong Kong 香港城市大學","賽馬會敬賢堂公共空間 Hall 1 Common Room","Students & staff only","只限學生及教師",22.32,114.17),
  buildPoint("cle-the-city-university-of-hong-kong-3","Sham_Shui_Po","The City University of Hong Kong 香港城市大學","兆基堂大堂 Hall 6 Lobby","The City University of Hong Kong 香港城市大學","兆基堂大堂 Hall 6 Lobby","Students & staff only","只限學生及教師",22.32,114.17),
  buildPoint("cle-the-city-university-of-hong-kong-4","Sham_Shui_Po","The City University of Hong Kong 香港城市大學","城大宿十大堂 Hall 10 Lobby","The City University of Hong Kong 香港城市大學","城大宿十大堂 Hall 10 Lobby","Students & staff only","只限學生及教師",22.32,114.17),
  buildPoint("cle-vcity","Sham_Shui_Po","VCITY (往屯門市中心天橋方向 望見周生生商舖轉左 會有個回收區域)","屯門鄉事會路83號V city 1樓服務處","VCITY (往屯門市中心天橋方向 望見周生生商舖轉左 會有個回收區域)","屯門鄉事會路83號V city 1樓服務處","","",22.32,114.17),
  buildPoint("cle-yoho-mall-i-i","Sham_Shui_Po","YOHO Mall I 形點 I","新界元朗元龍街九號形點I 一期 （2樓禮賓部）","YOHO Mall I 形點 I","新界元朗元龍街九號形點I 一期 （2樓禮賓部）","","",22.32,114.17),
  buildPoint("cle-nan-fung-centre","Sham_Shui_Po","Nan Fung Centre 南豐中心","新界荃灣青山公路264-298號1樓禮賓部","Nan Fung Centre 南豐中心","新界荃灣青山公路264-298號1樓禮賓部","","",22.32,114.17),
  buildPoint("cle-dorsett-tsuen-wan-hong-kong","Sham_Shui_Po","Dorsett Tsuen Wan Hong Kong 香港荃灣帝盛酒店","葵涌健全街28號","Dorsett Tsuen Wan Hong Kong 香港荃灣帝盛酒店","葵涌健全街28號","","",22.32,114.17),
  buildPoint("cle-the-mills","Sham_Shui_Po","The Mills 南豐紗廠","新界荃灣白田1壩街45號地下禮賓部","The Mills 南豐紗廠","新界荃灣白田1壩街45號地下禮賓部","","",22.32,114.17),
  buildPoint("cle-point-12","Sham_Shui_Po","九龍貿易中心","葵涌葵昌路51號九龍貿易中心一座2樓 (禮賓部附近—綠惜之道)","九龍貿易中心","葵涌葵昌路51號九龍貿易中心一座2樓 (禮賓部附近—綠惜之道)","","",22.32,114.17),
  buildPoint("cle-tai-kwong-hilary-college","Sham_Shui_Po","Tai Kwong Hilary College 大光德萃書院","新界大埔錦山178號","Tai Kwong Hilary College 大光德萃書院","新界大埔錦山178號","Campus only","只限校內人士",22.32,114.17),
  buildPoint("cle-the-aurora","Sham_Shui_Po","The Aurora 映日灣","荃灣楊屋道88號映日灣會所地下大堂","The Aurora 映日灣","荃灣楊屋道88號映日灣會所地下大堂","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-twin-peaks","Sham_Shui_Po","Twin Peaks 將軍澳嘉悅會所","將軍澳至善街9號嘉悅會所","Twin Peaks 將軍澳嘉悅會所","將軍澳至善街9號嘉悅會所","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-mayfair-by-the-sea-8-8","Sham_Shui_Po","Mayfair By The Sea 8 逸瓏灣8","大埔半山科研路1號","Mayfair By The Sea 8 逸瓏灣8","大埔半山科研路1號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-royal-palms","Sham_Shui_Po","Royal Palms 加州豪園","元朗加州豪園會所","Royal Palms 加州豪園","元朗加州豪園會所","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-dragons-range","Sham_Shui_Po","Dragons Range 玖瓏山","沙田九肚山麗坪路33號","Dragons Range 玖瓏山","沙田九肚山麗坪路33號","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-the-wings-ii-ii","Sham_Shui_Po","The Wings II 天晉II","將軍澳唐俊街12號服務處","The Wings II 天晉II","將軍澳唐俊街12號服務處","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-the-wings-iiia-iiia","Sham_Shui_Po","The Wings IIIA 天晉IIIA","將軍澳唐賢街19號天晉IIIA","The Wings IIIA 天晉IIIA","將軍澳唐賢街19號天晉IIIA","Residents only","只限住戶",22.32,114.17),
  buildPoint("cle-point-13","Sham_Shui_Po","香港專業花式跳繩學校","新界沙田石門安群街3號京瑞廣場1期17樓N室","香港專業花式跳繩學校","新界沙田石門安群街3號京瑞廣場1期17樓N室","Students & staff only","只限家長及學生",22.32,114.17),
  buildPoint("cle-point-14","Sham_Shui_Po","香港寬頻有限公司","新界葵涌健康街18號恆亞中心12樓、14-16樓","香港寬頻有限公司","新界葵涌健康街18號恆亞中心12樓、14-16樓","Staff only","只限員工",22.32,114.17),
  buildPoint("cle-point-15","Sham_Shui_Po","清水灣半島","港新界將軍澳百勝角蓬萊路8號","清水灣半島","港新界將軍澳百勝角蓬萊路8號","Residents only","只限住戶及員工",22.32,114.17),
  buildPoint("cle-discovery-bay-office-centre","Islands","Discovery Bay Office Centre 愉景灣商務中心","大嶼山愉景灣廣場徑2號","Discovery Bay Office Centre 愉景灣商務中心","大嶼山愉景灣廣場徑2號","","",22.32,114.17),
  buildPoint("cle-coastal-skyline","Islands","Coastal Skyline 藍天海岸會","東涌海濱路12號藍天海岸會所（只限住戶）","Coastal Skyline 藍天海岸會","東涌海濱路12號藍天海岸會所（只限住戶）","","",22.32,114.17),
];
