/** Food Angel 惜食堂 — food rescue donation points (source: foodangel.org.hk/food-rescue) */

export type FoodAngelLocationType = "depot" | "collection_box" | "smart_machine" | "smart_box" | "parknshop_smart";

export interface FoodAngelLocation {
  id: string;
  district: string;
  nameEn: string;
  nameTc: string;
  addressEn: string;
  addressTc: string;
  lat: number;
  lng: number;
  type: FoodAngelLocationType;
  typeEn: string;
  typeTc: string;
  residentsOnly?: boolean;
  underRepair?: boolean;
}

export const FOOD_ANGEL_LOCATIONS: FoodAngelLocation[] = [
  {
    id: "food-angel-depot",
    district: "Kwai_Tsing",
    nameEn: "Food Angel Sharing Hub",
    nameTc: "惜食分餉站",
    addressEn: "Room 1303, Delta House, 88 Lei Muk Road, Kwai Chung, NT",
    addressTc: "新界葵涌梨木道88號達利中心1303室",
    lat: 22.3685,
    lng: 114.1392,
    type: "depot",
    typeEn: "Designated dry-goods drop-off",
    typeTc: "指定收集點（乾貨）",
  },
  {
    id: "food-angel-loc-1",
    district: "Kowloon_City",
    nameEn: "何文田廣場",
    nameTc: "何文田廣場",
    addressEn: "何文田佛光街80號近商場B區一樓服務台側",
    addressTc: "何文田佛光街80號近商場B區一樓服務台側",
    lat: 22.322,
    lng: 114.186,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-2",
    district: "Kowloon_City",
    nameEn: "鳳德商場",
    nameTc: "鳳德商場",
    addressEn: "九龍鑽石山鳳德道111號鳳德村銀鳳樓2樓店舖N241及N242 (米仔站內)",
    addressTc: "九龍鑽石山鳳德道111號鳳德村銀鳳樓2樓店舖N241及N242 (米仔站內)",
    lat: 22.324,
    lng: 114.186,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-mikiki",
    district: "Kowloon_City",
    nameEn: "Mikiki",
    nameTc: "Mikiki",
    addressEn: "九龍新蒲崗太子道東638號MIKIKI商場 LG 層升降機大堂(近一田超市門口)",
    addressTc: "九龍新蒲崗太子道東638號MIKIKI商場 LG 層升降機大堂(近一田超市門口)",
    lat: 22.326,
    lng: 114.186,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-monaco-one",
    district: "Kowloon_City",
    nameEn: "Monaco One",
    nameTc: "Monaco One",
    addressEn: "九龍啟德沐泰街10號Monaco ONE",
    addressTc: "九龍啟德沐泰街10號Monaco ONE",
    lat: 22.328,
    lng: 114.186,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-ccb-tower",
    district: "Central_Western",
    nameEn: "CCB Tower",
    nameTc: "CCB Tower",
    addressEn: "香港中環干諾道中 3號中國建設銀行大廈1樓 (CCB Tower)",
    addressTc: "香港中環干諾道中 3號中國建設銀行大廈1樓 (CCB Tower)",
    lat: 22.28,
    lng: 114.148,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-6",
    district: "Central_Western",
    nameEn: "信德中心",
    nameTc: "信德中心",
    addressEn: "上環信德中心干諾道中200號招商局大廈二樓東橋入口 (往中環方向行人天橋)",
    addressTc: "上環信德中心干諾道中200號招商局大廈二樓東橋入口 (往中環方向行人天橋)",
    lat: 22.282,
    lng: 114.148,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-ifc-shopping-mall",
    district: "Central_Western",
    nameEn: "IFC Shopping Mall",
    nameTc: "IFC Shopping Mall",
    addressEn: "香港中環金融街八號中環國際金融中心一期1樓 (近1021號鋪SMARTONE)",
    addressTc: "香港中環金融街八號中環國際金融中心一期1樓 (近1021號鋪SMARTONE)",
    lat: 22.284,
    lng: 114.148,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-3",
    district: "Central_Western",
    nameEn: "花園道3號",
    nameTc: "花園道3號",
    addressEn: "(2025版)香港中環花園道3號低層地下1號舖旁(自助汽水機隔離)",
    addressTc: "(2025版)香港中環花園道3號低層地下1號舖旁(自助汽水機隔離)",
    lat: 22.286,
    lng: 114.148,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-loc-9",
    district: "Yuen_Long",
    nameEn: "朗屏商場",
    nameTc: "朗屏商場",
    addressEn: "朗屏路1號商場3樓酒樓對開位置",
    addressTc: "朗屏路1號商場3樓酒樓對開位置",
    lat: 22.439,
    lng: 114.016,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-sol-city",
    district: "Yuen_Long",
    nameEn: "Sol City 朗城匯",
    nameTc: "Sol City 朗城匯",
    addressEn: "元朗區朗屏媽橫路1號會所地下接待處對面",
    addressTc: "元朗區朗屏媽橫路1號會所地下接待處對面",
    lat: 22.441,
    lng: 114.016,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-woo",
    district: "Yuen_Long",
    nameEn: "+ Woo 嘉湖商埸",
    nameTc: "+ Woo 嘉湖商埸",
    addressEn: "天水圍天恩路18號天水圍+woo嘉湖商埸一期一樓 (近商場服務台)",
    addressTc: "天水圍天恩路18號天水圍+woo嘉湖商埸一期一樓 (近商場服務台)",
    lat: 22.443,
    lng: 114.016,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-8-the-spectra",
    district: "Yuen_Long",
    nameEn: "朗屏8號 THE SPECTRA",
    nameTc: "朗屏8號 THE SPECTRA",
    addressEn: "元朗朗屏擴業街8號朗屏8號",
    addressTc: "元朗朗屏擴業街8號朗屏8號",
    lat: 22.445,
    lng: 114.016,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-the-yoho-hub",
    district: "Yuen_Long",
    nameEn: "The YOHO HUB",
    nameTc: "The YOHO HUB",
    addressEn: "元朗朗樂路一號YOHO HUB二期會所Club Vis",
    addressTc: "元朗朗樂路一號YOHO HUB二期會所Club Vis",
    lat: 22.447,
    lng: 114.016,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-loc-14",
    district: "Tuen_Mun",
    nameEn: "大興商場",
    nameTc: "大興商場",
    addressEn: "大興街1號近商場二期地下升降機大堂",
    addressTc: "大興街1號近商場二期地下升降機大堂",
    lat: 22.385,
    lng: 113.971,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-15",
    district: "Tuen_Mun",
    nameEn: "怡峰園",
    nameTc: "怡峰園",
    addressEn: "屯門屯興路9號怡峰園",
    addressTc: "屯門屯興路9號怡峰園",
    lat: 22.387,
    lng: 113.971,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-century-gateway",
    district: "Tuen_Mun",
    nameEn: "瓏門 Century Gateway",
    nameTc: "瓏門 Century Gateway",
    addressEn: "屯門鄉事會路83號瓏門",
    addressTc: "屯門鄉事會路83號瓏門",
    lat: 22.389,
    lng: 113.971,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-miami-beach-towers",
    district: "Tuen_Mun",
    nameEn: "邁亞美海灣 Miami Beach Towers",
    nameTc: "邁亞美海灣 Miami Beach Towers",
    addressEn: "屯門碼頭湖翠路268號第2座住客會所平台",
    addressTc: "屯門碼頭湖翠路268號第2座住客會所平台",
    lat: 22.391,
    lng: 113.971,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-loc-18",
    district: "Tuen_Mun",
    nameEn: "御海灣",
    nameTc: "御海灣",
    addressEn: "屯門海皇路23號御海灣二樓住客會所",
    addressTc: "屯門海皇路23號御海灣二樓住客會所",
    lat: 22.393,
    lng: 113.971,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2",
    district: "Tuen_Mun",
    nameEn: "屯門市廣場2期",
    nameTc: "屯門市廣場2期",
    addressEn: "新界屯門屯龍街3號屯門市廣場二期",
    addressTc: "新界屯門屯龍街3號屯門市廣場二期",
    lat: 22.395,
    lng: 113.971,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-v-city",
    district: "Tuen_Mun",
    nameEn: "V City",
    nameTc: "V City",
    addressEn: "(2025版)香港新界屯門鄉事會路83號V City港鐵樓層M-95號舖周生生旁",
    addressTc: "(2025版)香港新界屯門鄉事會路83號V City港鐵樓層M-95號舖周生生旁",
    lat: 22.397,
    lng: 113.971,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-avon-park",
    district: "North",
    nameEn: "碧湖花園 Avon Park",
    nameTc: "碧湖花園 Avon Park",
    addressEn: "新界粉嶺一鳴路15號碧湖花園平台住客會所",
    addressTc: "新界粉嶺一鳴路15號碧湖花園平台住客會所",
    lat: 22.488,
    lng: 114.122,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-loc-22",
    district: "North",
    nameEn: "新都廣場",
    nameTc: "新都廣場",
    addressEn: "上水龍運街8號新都廣場上水新都廣場 1-3座 (回收箱於一至三座大堂輪流擺放各4 個月)",
    addressTc: "上水龍運街8號新都廣場上水新都廣場 1-3座 (回收箱於一至三座大堂輪流擺放各4 個月)",
    lat: 22.49,
    lng: 114.122,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-spot",
    district: "North",
    nameEn: "SPOT 上水匯",
    nameTc: "SPOT 上水匯",
    addressEn: "(2025版)新界上水龍心道48號上水匯3樓禮賓部",
    addressTc: "(2025版)新界上水龍心道48號上水匯3樓禮賓部",
    lat: 22.492,
    lng: 114.122,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-loc-24",
    district: "Sha_Tin",
    nameEn: "恆安商場",
    nameTc: "恆安商場",
    addressEn: "馬鞍山恆錦街1號近2樓服務台",
    addressTc: "馬鞍山恆錦街1號近2樓服務台",
    lat: 22.375,
    lng: 114.182,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-25",
    district: "Sha_Tin",
    nameEn: "顯徑商場",
    nameTc: "顯徑商場",
    addressEn: "沙田大圍車公廟道69號近商場一樓服務台",
    addressTc: "沙田大圍車公廟道69號近商場一樓服務台",
    lat: 22.377,
    lng: 114.182,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-lake-silver",
    district: "Sha_Tin",
    nameEn: "銀湖天峰 LAKE SILVER",
    nameTc: "銀湖天峰 LAKE SILVER",
    addressEn: "烏溪沙馬鞍山西沙路599號銀湖天峰",
    addressTc: "烏溪沙馬鞍山西沙路599號銀湖天峰",
    lat: 22.379,
    lng: 114.182,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-the-palazzo",
    district: "Sha_Tin",
    nameEn: "御龍山 THE PALAZZO",
    nameTc: "御龍山 THE PALAZZO",
    addressEn: "火炭樂景街28號御龍山",
    addressTc: "火炭樂景街28號御龍山",
    lat: 22.381,
    lng: 114.182,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-festival-city",
    district: "Sha_Tin",
    nameEn: "大圍名城 FESTIVAL CITY",
    nameTc: "大圍名城 FESTIVAL CITY",
    addressEn: "大圍美田路一號名城",
    addressTc: "大圍美田路一號名城",
    lat: 22.383,
    lng: 114.182,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-fortune-city-one",
    district: "Sha_Tin",
    nameEn: "置富第一城 Fortune City One",
    nameTc: "置富第一城 Fortune City One",
    addressEn: "沙田銀城街一號沙田第一城商場置富第一城地下 (近商場服務台)",
    addressTc: "沙田銀城街一號沙田第一城商場置富第一城地下 (近商場服務台)",
    lat: 22.385,
    lng: 114.182,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-jubilee-square",
    district: "Sha_Tin",
    nameEn: "銀禧薈 Jubilee Square",
    nameTc: "銀禧薈 Jubilee Square",
    addressEn: "新界沙田火炭樂景街2-18號火炭銀禧薈三樓 (近商場服務台)",
    addressTc: "新界沙田火炭樂景街2-18號火炭銀禧薈三樓 (近商場服務台)",
    lat: 22.387,
    lng: 114.182,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-ma-on-shan-plaza",
    district: "Sha_Tin",
    nameEn: "馬鞍山廣場 MA ON SHAN PLAZA",
    nameTc: "馬鞍山廣場 MA ON SHAN PLAZA",
    addressEn: "新界馬鞍山西沙路608號馬鞍山廣場2樓",
    addressTc: "新界馬鞍山西沙路608號馬鞍山廣場2樓",
    lat: 22.375,
    lng: 114.184,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-st-michel",
    district: "Sha_Tin",
    nameEn: "瓏珀山 ST MICHEL",
    nameTc: "瓏珀山 ST MICHEL",
    addressEn: "小瀝源多石街33號瓏珀山",
    addressTc: "小瀝源多石街33號瓏珀山",
    lat: 22.377,
    lng: 114.184,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-seanorama",
    district: "Sha_Tin",
    nameEn: "星漣海 SEANORAMA",
    nameTc: "星漣海 SEANORAMA",
    addressEn: "沙田馬鞍山彩沙街1號住客會所一樓",
    addressTc: "沙田馬鞍山彩沙街1號住客會所一樓",
    lat: 22.379,
    lng: 114.184,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-34",
    district: "Sha_Tin",
    nameEn: "沙田廚房",
    nameTc: "沙田廚房",
    addressEn: "(2025版)沙田多石街1號惜食堂賽馬會食品製作中心",
    addressTc: "(2025版)沙田多石街1號惜食堂賽馬會食品製作中心",
    lat: 22.381,
    lng: 114.184,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-loc-35",
    district: "Eastern",
    nameEn: "興華廣場",
    nameTc: "興華廣場",
    addressEn: "柴灣環翠道11號近商場一樓服務台",
    addressTc: "柴灣環翠道11號近商場一樓服務台",
    lat: 22.273,
    lng: 114.219,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-36",
    district: "Eastern",
    nameEn: "小西灣廣場",
    nameTc: "小西灣廣場",
    addressEn: "小西灣小西灣道10號近商場一樓服務台",
    addressTc: "小西灣小西灣道10號近商場一樓服務台",
    lat: 22.275,
    lng: 114.219,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-37",
    district: "Eastern",
    nameEn: "恆隆康怡廣場",
    nameTc: "恆隆康怡廣場",
    addressEn: "鰂魚湧康山道1-2號康怡廣埸南座1樓停車場繳費處側",
    addressTc: "鰂魚湧康山道1-2號康怡廣埸南座1樓停車場繳費處側",
    lat: 22.277,
    lng: 114.219,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-harbour-north-phase-2",
    district: "Eastern",
    nameEn: "北角匯二期 Harbour North Phase 2",
    nameTc: "北角匯二期 Harbour North Phase 2",
    addressEn: "北角渣華道123號北角匯商場2期B2職電梯大堂",
    addressTc: "北角渣華道123號北角匯商場2期B2職電梯大堂",
    lat: 22.279,
    lng: 114.219,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-kodak-house",
    district: "Eastern",
    nameEn: "柯達大廈2期 KODAK HOUSE",
    nameTc: "柯達大廈2期 KODAK HOUSE",
    addressEn: "北角健康東街39號鰂魚湧柯達大廈2期地下",
    addressTc: "北角健康東街39號鰂魚湧柯達大廈2期地下",
    lat: 22.281,
    lng: 114.219,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-40",
    district: "Yau_Tsim_Mong",
    nameEn: "海富商場",
    nameTc: "海富商場",
    addressEn: "旺角海庭路2號近地下顧客服務台側",
    addressTc: "旺角海庭路2號近地下顧客服務台側",
    lat: 22.299,
    lng: 114.165,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-harbour-green",
    district: "Yau_Tsim_Mong",
    nameEn: "君匯港 Harbour Green",
    nameTc: "君匯港 Harbour Green",
    addressEn: "九龍深旺道8號君匯港第6座客務處",
    addressTc: "九龍深旺道8號君匯港第6座客務處",
    lat: 22.301,
    lng: 114.165,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-grand-austin",
    district: "Yau_Tsim_Mong",
    nameEn: "Grand Austin",
    nameTc: "Grand Austin",
    addressEn: "佐敦柯士甸道西9號佐敦柯士甸道西9號",
    addressTc: "佐敦柯士甸道西9號佐敦柯士甸道西9號",
    lat: 22.303,
    lng: 114.165,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-loc-43",
    district: "Yau_Tsim_Mong",
    nameEn: "帝峰 ‧皇殿",
    nameTc: "帝峰 ‧皇殿",
    addressEn: "九龍旺角西海泓道1號帝峰 · 皇殿住客會所 (6樓）",
    addressTc: "九龍旺角西海泓道1號帝峰 · 皇殿住客會所 (6樓）",
    lat: 22.305,
    lng: 114.165,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-sorrento",
    district: "Yau_Tsim_Mong",
    nameEn: "擎天半島 SORRENTO",
    nameTc: "擎天半島 SORRENTO",
    addressEn: "九龍柯士甸道西一號擎天半島",
    addressTc: "九龍柯士甸道西一號擎天半島",
    lat: 22.307,
    lng: 114.165,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-2-park-avenue-central-park",
    district: "Yau_Tsim_Mong",
    nameEn: "柏景灣2期 帝柏海灣 Park Avenue Central Park",
    nameTc: "柏景灣2期 帝柏海灣 Park Avenue Central Park",
    addressEn: "西九龍海庭道18號帝柏海灣/柏景灣",
    addressTc: "西九龍海庭道18號帝柏海灣/柏景灣",
    lat: 22.309,
    lng: 114.165,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-the-austin",
    district: "Yau_Tsim_Mong",
    nameEn: "The Austin",
    nameTc: "The Austin",
    addressEn: "九龍站匯翔道8號The Austin",
    addressTc: "九龍站匯翔道8號The Austin",
    lat: 22.311,
    lng: 114.165,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-the-arch",
    district: "Yau_Tsim_Mong",
    nameEn: "凱旋門 The Arch",
    nameTc: "凱旋門 The Arch",
    addressEn: "九龍站柯士甸道西1號L29,30 shuttle lift lobby, G/F, The Arch",
    addressTc: "九龍站柯士甸道西1號L29,30 shuttle lift lobby, G/F, The Arch",
    lat: 22.299,
    lng: 114.167,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-the-cullinan",
    district: "Yau_Tsim_Mong",
    nameEn: "天璽 The CULLINAN",
    nameTc: "天璽 The CULLINAN",
    addressEn: "九龍站柯士甸道西1號天璽",
    addressTc: "九龍站柯士甸道西1號天璽",
    lat: 22.301,
    lng: 114.167,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-island-harbourview",
    district: "Yau_Tsim_Mong",
    nameEn: "維港灣 Island Harbourview",
    nameTc: "維港灣 Island Harbourview",
    addressEn: "西九龍海輝道11號維港灣8座會所",
    addressTc: "西九龍海輝道11號維港灣8座會所",
    lat: 22.303,
    lng: 114.167,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-loc-50",
    district: "Yau_Tsim_Mong",
    nameEn: "奧海城",
    nameTc: "奧海城",
    addressEn: "九龍大角咀海輝道11號奧海城商場一期地下",
    addressTc: "九龍大角咀海輝道11號奧海城商場一期地下",
    lat: 22.305,
    lng: 114.167,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
    underRepair: true,
  },
  {
    id: "food-angel-icc",
    district: "Yau_Tsim_Mong",
    nameEn: "ICC 環球貿易廣場",
    nameTc: "ICC 環球貿易廣場",
    addressEn: "香港西九龍柯士甸道西1號西九龍環球貿易廣場1樓ICC穿梭巴士上落客處",
    addressTc: "香港西九龍柯士甸道西1號西九龍環球貿易廣場1樓ICC穿梭巴士上落客處",
    lat: 22.307,
    lng: 114.167,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-loc-52",
    district: "Yau_Tsim_Mong",
    nameEn: "朗豪坊",
    nameTc: "朗豪坊",
    addressEn: "旺角亞皆老街8號旺角朗豪坊商場 L2層 07號鋪 \"CAUDALIE\" 對著電梯大堂",
    addressTc: "旺角亞皆老街8號旺角朗豪坊商場 L2層 07號鋪 \"CAUDALIE\" 對著電梯大堂",
    lat: 22.309,
    lng: 114.167,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-loc-53",
    district: "Yau_Tsim_Mong",
    nameEn: "港灣豪庭",
    nameTc: "港灣豪庭",
    addressEn: "(2025版)九龍大角咀福利街8號G/F時租停車場住宅出入口𨋢大堂",
    addressTc: "(2025版)九龍大角咀福利街8號G/F時租停車場住宅出入口𨋢大堂",
    lat: 22.311,
    lng: 114.167,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-loc-54",
    district: "Kowloon_City",
    nameEn: "紅磡海濱廣場",
    nameTc: "紅磡海濱廣場",
    addressEn: "香港九龍紅磡德豐街18-22號紅磡海濱廣場一座地下升降機大堂",
    addressTc: "香港九龍紅磡德豐街18-22號紅磡海濱廣場一座地下升降機大堂",
    lat: 22.33,
    lng: 114.186,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-55",
    district: "Kowloon_City",
    nameEn: "悅目",
    nameTc: "悅目",
    addressEn: "九龍紅磡利工街9號UG層 住客會所",
    addressTc: "九龍紅磡利工街9號UG層 住客會所",
    lat: 22.332,
    lng: 114.186,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-royal-peninsula",
    district: "Kowloon_City",
    nameEn: "半島豪庭 ROYAL PENINSULA",
    nameTc: "半島豪庭 ROYAL PENINSULA",
    addressEn: "紅磡紅荔道8號紅磡紅荔道8號",
    addressTc: "紅磡紅荔道8號紅磡紅荔道8號",
    lat: 22.334,
    lng: 114.186,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-ocean-pride",
    district: "Tsuen_Wan",
    nameEn: "海之戀 OCEAN PRIDE",
    nameTc: "海之戀 OCEAN PRIDE",
    addressEn: "荃灣大河道100號海之戀",
    addressTc: "荃灣大河道100號海之戀",
    lat: 22.365,
    lng: 114.107,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-summit-terrace",
    district: "Tsuen_Wan",
    nameEn: "翠豐臺 SUMMIT TERRACE",
    nameTc: "翠豐臺 SUMMIT TERRACE",
    addressEn: "荃景圍安育路1-2號會所環保角, P5樓層",
    addressTc: "荃景圍安育路1-2號會所環保角, P5樓層",
    lat: 22.367,
    lng: 114.107,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-belvedere-square",
    district: "Tsuen_Wan",
    nameEn: "麗城薈 Belvedere Square",
    nameTc: "麗城薈 Belvedere Square",
    addressEn: "荃灣青山道625號荃灣麗城薈三期地下 (近商場服務台)",
    addressTc: "荃灣青山道625號荃灣麗城薈三期地下 (近商場服務台)",
    lat: 22.369,
    lng: 114.107,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-bellagio",
    district: "Tsuen_Wan",
    nameEn: "碧堤半島 Bellagio",
    nameTc: "碧堤半島 Bellagio",
    addressEn: "深井青山公路深井段33號碧堤半島 -",
    addressTc: "深井青山公路深井段33號碧堤半島 -",
    lat: 22.371,
    lng: 114.107,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-loc-61",
    district: "Tsuen_Wan",
    nameEn: "荃新天地",
    nameTc: "荃新天地",
    addressEn: "新界荃灣楊屋道 1 號荃灣荃新天地一期 UG 層 (UG50號鋪旁邊)",
    addressTc: "新界荃灣楊屋道 1 號荃灣荃新天地一期 UG 層 (UG50號鋪旁邊)",
    lat: 22.373,
    lng: 114.107,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-loc-62",
    district: "Tsuen_Wan",
    nameEn: "珀麗灣",
    nameTc: "珀麗灣",
    addressEn: "(2025版)馬灣珀麗路8號珀麗灣第3與第5座基座Park Island 珀麗灣-珀麗灣巴士總站候車室",
    addressTc: "(2025版)馬灣珀麗路8號珀麗灣第3與第5座基座Park Island 珀麗灣-珀麗灣巴士總站候車室",
    lat: 22.375,
    lng: 114.107,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-loc-63",
    district: "Tsuen_Wan",
    nameEn: "南豐中心",
    nameTc: "南豐中心",
    addressEn: "(2025版)荃灣青山公路 - 荃灣段264 - 298號南豐中心B1層停車場電梯大堂",
    addressTc: "(2025版)荃灣青山公路 - 荃灣段264 - 298號南豐中心B1層停車場電梯大堂",
    lat: 22.377,
    lng: 114.107,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-loc-64",
    district: "Tsuen_Wan",
    nameEn: "葵涌廣場",
    nameTc: "葵涌廣場",
    addressEn: "(2025版)葵涌葵富路7-11號葵涌廣場1樓 E9及E10號扶手電梯前",
    addressTc: "(2025版)葵涌葵富路7-11號葵涌廣場1樓 E9及E10號扶手電梯前",
    lat: 22.365,
    lng: 114.109,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-tko-spot",
    district: "Sai_Kung",
    nameEn: "TKO SPOT",
    nameTc: "TKO SPOT",
    addressEn: "將軍澳唐明街2號近商場二樓服務台",
    addressTc: "將軍澳唐明街2號近商場二樓服務台",
    lat: 22.308,
    lng: 114.258,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-tko-gateway",
    district: "Sai_Kung",
    nameEn: "TKO Gateway",
    nameTc: "TKO Gateway",
    addressEn: "將軍澳常寧路2號近商場一樓服務台",
    addressTc: "將軍澳常寧路2號近商場一樓服務台",
    lat: 22.31,
    lng: 114.258,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-metro-town",
    district: "Sai_Kung",
    nameEn: "都會驛 METRO TOWN",
    nameTc: "都會驛 METRO TOWN",
    addressEn: "將軍澳調景嶺景嶺路8號都會驛",
    addressTc: "將軍澳調景嶺景嶺路8號都會驛",
    lat: 22.312,
    lng: 114.258,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-residence-oasis",
    district: "Sai_Kung",
    nameEn: "蔚藍灣畔 Residence Oasis",
    nameTc: "蔚藍灣畔 Residence Oasis",
    addressEn: "將軍澳坑口培成路15號蔚藍灣畔",
    addressTc: "將軍澳坑口培成路15號蔚藍灣畔",
    lat: 22.314,
    lng: 114.258,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-monterey",
    district: "Sai_Kung",
    nameEn: "Monterey",
    nameTc: "Monterey",
    addressEn: "將軍澳南唐俊街23號地下住客會所",
    addressTc: "將軍澳南唐俊街23號地下住客會所",
    lat: 22.316,
    lng: 114.258,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-savannah",
    district: "Sai_Kung",
    nameEn: "Savannah",
    nameTc: "Savannah",
    addressEn: "香港新界將軍澳至善街3號Savannah",
    addressTc: "香港新界將軍澳至善街3號Savannah",
    lat: 22.318,
    lng: 114.258,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-the-grandiose",
    district: "Sai_Kung",
    nameEn: "君傲灣 The Grandiose",
    nameTc: "君傲灣 The Grandiose",
    addressEn: "將軍澳唐俊街9號君傲灣",
    addressTc: "將軍澳唐俊街9號君傲灣",
    lat: 22.32,
    lng: 114.258,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-hemera-a-lohas-park-phase-3a",
    district: "Sai_Kung",
    nameEn: "緻藍天 HEMERA 日出康城三A期 LOHAS PARK Phase 3A",
    nameTc: "緻藍天 HEMERA 日出康城三A期 LOHAS PARK Phase 3A",
    addressEn: "將軍澳康城路1號緻藍天",
    addressTc: "將軍澳康城路1號緻藍天",
    lat: 22.308,
    lng: 114.26,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-the-parkside-fsb006",
    district: "Sai_Kung",
    nameEn: "The Parkside將軍澳 (FSB006)",
    nameTc: "The Parkside將軍澳 (FSB006)",
    addressEn: "將軍澳唐俊街18號The Parkside住客會所",
    addressTc: "將軍澳唐俊街18號The Parkside住客會所",
    lat: 22.31,
    lng: 114.26,
    type: "smart_box",
    typeEn: "Smart food collection box",
    typeTc: "智能食物收集箱",
  },
  {
    id: "food-angel-park-central-fsb002",
    district: "Sai_Kung",
    nameEn: "將軍澳中心 Park Central(FSB002)",
    nameTc: "將軍澳中心 Park Central(FSB002)",
    addressEn: "將軍澳唐德街平台將軍澳中心",
    addressTc: "將軍澳唐德街平台將軍澳中心",
    lat: 22.312,
    lng: 114.26,
    type: "smart_box",
    typeEn: "Smart food collection box",
    typeTc: "智能食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-loc-75",
    district: "Sham_Shui_Po",
    nameEn: "元州商場",
    nameTc: "元州商場",
    addressEn: "長沙灣元州街303號商場1樓服務台旁",
    addressTc: "長沙灣元州街303號商場1樓服務台旁",
    lat: 22.325,
    lng: 114.156,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-76",
    district: "Sham_Shui_Po",
    nameEn: "南昌薈",
    nameTc: "南昌薈",
    addressEn: "深水埗西村路19號近地下顧客服務台",
    addressTc: "深水埗西村路19號近地下顧客服務台",
    lat: 22.327,
    lng: 114.156,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-77",
    district: "Sham_Shui_Po",
    nameEn: "又一村花園俱樂部",
    nameTc: "又一村花園俱樂部",
    addressEn: "又一村高槐路7號又一村花園俱樂部",
    addressTc: "又一村高槐路7號又一村花園俱樂部",
    lat: 22.329,
    lng: 114.156,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-cullinan-west",
    district: "Sham_Shui_Po",
    nameEn: "匯璽 Cullinan West",
    nameTc: "匯璽 Cullinan West",
    addressEn: "南昌站深旺道28號匯璽 L5 住客會所(即V- Walk 商場樓上)",
    addressTc: "南昌站深旺道28號匯璽 L5 住客會所(即V- Walk 商場樓上)",
    lat: 22.331,
    lng: 114.156,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-loc-79",
    district: "Sham_Shui_Po",
    nameEn: "惜食堂教育部",
    nameTc: "惜食堂教育部",
    addressEn: "豐盛大廈一樓",
    addressTc: "豐盛大廈一樓",
    lat: 22.333,
    lng: 114.156,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-80",
    district: "Islands",
    nameEn: "富東廣場",
    nameTc: "富東廣場",
    addressEn: "新界東湧富東街6號近商場一樓服務台， 大家樂附近",
    addressTc: "新界東湧富東街6號近商場一樓服務台， 大家樂附近",
    lat: 22.302,
    lng: 113.912,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-caribbean-coast",
    district: "Islands",
    nameEn: "映灣園 CARIBBEAN COAST",
    nameTc: "映灣園 CARIBBEAN COAST",
    addressEn: "東湧市中心健東路2號映灣園會所 CLUB CARIBBEAN",
    addressTc: "東湧市中心健東路2號映灣園會所 CLUB CARIBBEAN",
    lat: 22.304,
    lng: 113.912,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-coastal-skyline",
    district: "Islands",
    nameEn: "藍天海岸 Coastal Skyline",
    nameTc: "藍天海岸 Coastal Skyline",
    addressEn: "東湧海濱路12號藍天海岸",
    addressTc: "東湧海濱路12號藍天海岸",
    lat: 22.306,
    lng: 113.912,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-fsb003",
    district: "Wan_Chai",
    nameEn: "囍匯 (FSB003)",
    nameTc: "囍匯 (FSB003)",
    addressEn: "灣仔區皇后大道東200號囍匯第一座住客會所",
    addressTc: "灣仔區皇后大道東200號囍匯第一座住客會所",
    lat: 22.271,
    lng: 114.167,
    type: "smart_box",
    typeEn: "Smart food collection box",
    typeTc: "智能食物收集箱",
    residentsOnly: true,
  },
  {
    id: "food-angel-loc-84",
    district: "Kwun_Tong",
    nameEn: "寶達商場",
    nameTc: "寶達商場",
    addressEn: "觀塘秀茂坪寶琳路2號近地下顧客服務台",
    addressTc: "觀塘秀茂坪寶琳路2號近地下顧客服務台",
    lat: 22.306,
    lng: 114.219,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-85",
    district: "Kwun_Tong",
    nameEn: "啟田商場",
    nameTc: "啟田商場",
    addressEn: "九龍觀塘藍田啟田道50號近商場一樓停車場繳費處",
    addressTc: "九龍觀塘藍田啟田道50號近商場一樓停車場繳費處",
    lat: 22.308,
    lng: 114.219,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-fsb005",
    district: "Kwun_Tong",
    nameEn: "麗港城商場 (FSB005)",
    nameTc: "麗港城商場 (FSB005)",
    addressEn: "九龍藍田茶果嶺道88號藍田麗港城商場地下 美心西餅旁邊電梯大堂前",
    addressTc: "九龍藍田茶果嶺道88號藍田麗港城商場地下 美心西餅旁邊電梯大堂前",
    lat: 22.31,
    lng: 114.219,
    type: "smart_box",
    typeEn: "Smart food collection box",
    typeTc: "智能食物收集箱",
  },
  {
    id: "food-angel-loc-87",
    district: "Kwun_Tong",
    nameEn: "觀塘裕民坊",
    nameTc: "觀塘裕民坊",
    addressEn: "九龍觀塘協和街33號裕民坊1樓102店旁",
    addressTc: "九龍觀塘協和街33號裕民坊1樓102店旁",
    lat: 22.312,
    lng: 114.219,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-loc-88",
    district: "Kwun_Tong",
    nameEn: "淘大商場",
    nameTc: "淘大商場",
    addressEn: "(2025版)九龍灣牛頭角道77號淘大商場 一樓 162-168鋪旁邊",
    addressTc: "(2025版)九龍灣牛頭角道77號淘大商場 一樓 162-168鋪旁邊",
    lat: 22.314,
    lng: 114.219,
    type: "smart_machine",
    typeEn: "Smart food donation machine",
    typeTc: "智能食物捐贈機",
  },
  {
    id: "food-angel-2-45",
    district: "Central_Western",
    nameEn: "士美菲路2香港堅尼地城士美菲路45",
    nameTc: "士美菲路2香港堅尼地城士美菲路45",
    addressEn: "51號Smithfield Walk低層地下7號舖",
    addressTc: "51號Smithfield Walk低層地下7號舖",
    lat: 22.288,
    lng: 114.148,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-17",
    district: "Central_Western",
    nameEn: "堅尼地城香港堅尼地城卑路乍街17",
    nameTc: "堅尼地城香港堅尼地城卑路乍街17",
    addressEn: "35號及堅尼地城海旁36-38號A及B號舖",
    addressTc: "35號及堅尼地城海旁36-38號A及B號舖",
    lat: 22.29,
    lng: 114.148,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-20-2-3",
    district: "Eastern",
    nameEn: "華蘭中心香港華蘭路20號華蘭中心地下2號及3號舖",
    nameTc: "華蘭中心香港華蘭路20號華蘭中心地下2號及3號舖",
    addressEn: "華蘭中心香港華蘭路20號華蘭中心地下2號及3號舖",
    addressTc: "華蘭中心香港華蘭路20號華蘭中心地下2號及3號舖",
    lat: 22.283,
    lng: 114.219,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-217",
    district: "Eastern",
    nameEn: "杏花村香港杏花邨杏花新城西翼二樓217",
    nameTc: "杏花村香港杏花邨杏花新城西翼二樓217",
    addressEn: "230號舖",
    addressTc: "230號舖",
    lat: 22.285,
    lng: 114.219,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-1-104",
    district: "Eastern",
    nameEn: "愛東邨香港筲箕灣愛東邨愛東商場1樓104",
    nameTc: "愛東邨香港筲箕灣愛東邨愛東商場1樓104",
    addressEn: "105號舖",
    addressTc: "105號舖",
    lat: 22.273,
    lng: 114.221,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-21",
    district: "Eastern",
    nameEn: "和富中心2香港北角和富道21",
    nameTc: "和富中心2香港北角和富道21",
    addressEn: "53號和富薈地庫B46號舖",
    addressTc: "53號和富薈地庫B46號舖",
    lat: 22.275,
    lng: 114.221,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-6",
    district: "Eastern",
    nameEn: "天后廟香港北角英皇道6",
    nameTc: "天后廟香港北角英皇道6",
    addressEn: "8號百利大廈地下部分及1樓全層",
    addressTc: "8號百利大廈地下部分及1樓全層",
    lat: 22.277,
    lng: 114.221,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-2-mcw",
    district: "Eastern",
    nameEn: "港運城2港運城2 MCW",
    nameTc: "港運城2港運城2 MCW",
    addressEn: "RC-RL 香港北角英皇道500號港運城商場地庫B05號舖",
    addressTc: "RC-RL 香港北角英皇道500號港運城商場地庫B05號舖",
    lat: 22.279,
    lng: 114.221,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-1-1-22",
    district: "Islands",
    nameEn: "映灣園大嶼山東涌健東路1號映灣坊1樓平台22",
    nameTc: "映灣園大嶼山東涌健東路1號映灣坊1樓平台22",
    addressEn: "23號舖",
    addressTc: "23號舖",
    lat: 22.308,
    lng: 113.912,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-20-b1",
    district: "Islands",
    nameEn: "東薈城大嶼山東涌達東路20號東薈城B1",
    nameTc: "東薈城大嶼山東涌達東路20號東薈城B1",
    addressEn: "B10號舖",
    addressTc: "B10號舖",
    lat: 22.31,
    lng: 113.912,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-70",
    district: "Kowloon_City",
    nameEn: "何文田九龍窩打老道70號曾榕大廈地下",
    nameTc: "何文田九龍窩打老道70號曾榕大廈地下",
    addressEn: "何文田九龍窩打老道70號曾榕大廈地下",
    addressTc: "何文田九龍窩打老道70號曾榕大廈地下",
    lat: 22.322,
    lng: 114.188,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-33-27",
    district: "Kowloon_City",
    nameEn: "欣榮花園九龍土瓜灣馬頭角道33號欣榮花園地下27號舖",
    nameTc: "欣榮花園九龍土瓜灣馬頭角道33號欣榮花園地下27號舖",
    addressEn: "欣榮花園九龍土瓜灣馬頭角道33號欣榮花園地下27號舖",
    addressTc: "欣榮花園九龍土瓜灣馬頭角道33號欣榮花園地下27號舖",
    lat: 22.324,
    lng: 114.188,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-108",
    district: "Kowloon_City",
    nameEn: "偉恆昌九龍土瓜灣美景街108號偉恒昌新恒景閣地下",
    nameTc: "偉恆昌九龍土瓜灣美景街108號偉恒昌新恒景閣地下",
    addressEn: "偉恆昌九龍土瓜灣美景街108號偉恒昌新恒景閣地下",
    addressTc: "偉恆昌九龍土瓜灣美景街108號偉恒昌新恒景閣地下",
    lat: 22.326,
    lng: 114.188,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-3-b2",
    district: "Kowloon_City",
    nameEn: "黃埔花園3九龍紅磡黃埔花園第十二期家居庭地庫B2號舖",
    nameTc: "黃埔花園3九龍紅磡黃埔花園第十二期家居庭地庫B2號舖",
    addressEn: "黃埔花園3九龍紅磡黃埔花園第十二期家居庭地庫B2號舖",
    addressTc: "黃埔花園3九龍紅磡黃埔花園第十二期家居庭地庫B2號舖",
    lat: 22.328,
    lng: 114.188,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-g23a",
    district: "Kowloon_City",
    nameEn: "愛民廣場九龍何文田愛民廣場地下G23A號舖",
    nameTc: "愛民廣場九龍何文田愛民廣場地下G23A號舖",
    addressEn: "愛民廣場九龍何文田愛民廣場地下G23A號舖",
    addressTc: "愛民廣場九龍何文田愛民廣場地下G23A號舖",
    lat: 22.33,
    lng: 114.188,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-3-26-internal-1a",
    district: "Kowloon_City",
    nameEn: "紅磡九龍紅磡黃埔花園第3期地下26號舖 (Internal: 1A號舖)",
    nameTc: "紅磡九龍紅磡黃埔花園第3期地下26號舖 (Internal: 1A號舖)",
    addressEn: "紅磡九龍紅磡黃埔花園第3期地下26號舖 (Internal: 1A號舖)",
    addressTc: "紅磡九龍紅磡黃埔花園第3期地下26號舖 (Internal: 1A號舖)",
    lat: 22.332,
    lng: 114.188,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-9-6",
    district: "Kwai_Tsing",
    nameEn: "長宏邨新界青衣寮肚路9號長宏邨長宏商場地下6號舖",
    nameTc: "長宏邨新界青衣寮肚路9號長宏邨長宏商場地下6號舖",
    addressEn: "長宏邨新界青衣寮肚路9號長宏邨長宏商場地下6號舖",
    addressTc: "長宏邨新界青衣寮肚路9號長宏邨長宏商場地下6號舖",
    lat: 22.35,
    lng: 114.121,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-dc",
    district: "Kwai_Tsing",
    nameEn: "盈翠半島盈翠半島 DC",
    nameTc: "盈翠半島盈翠半島 DC",
    addressEn: "MY 新界青衣青敬路33號青衣城3樓313號舖",
    addressTc: "MY 新界青衣青敬路33號青衣城3樓313號舖",
    lat: 22.352,
    lng: 114.121,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-4-401",
    district: "Kwun_Tong",
    nameEn: "匯景廣場2九龍藍田匯景廣場4樓401號舖",
    nameTc: "匯景廣場2九龍藍田匯景廣場4樓401號舖",
    addressEn: "匯景廣場2九龍藍田匯景廣場4樓401號舖",
    addressTc: "匯景廣場2九龍藍田匯景廣場4樓401號舖",
    lat: 22.316,
    lng: 114.219,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-15-f3-f4-r02",
    district: "Kwun_Tong",
    nameEn: "順利2九龍觀塘利安道15號順利商場F3及F4樓R02號舖",
    nameTc: "順利2九龍觀塘利安道15號順利商場F3及F4樓R02號舖",
    addressEn: "順利2九龍觀塘利安道15號順利商場F3及F4樓R02號舖",
    addressTc: "順利2九龍觀塘利安道15號順利商場F3及F4樓R02號舖",
    lat: 22.318,
    lng: 114.219,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-3-316",
    district: "Kwun_Tong",
    nameEn: "樂華邨九龍牛頭角樂華北邨樂華商場3樓316號舖",
    nameTc: "樂華邨九龍牛頭角樂華北邨樂華商場3樓316號舖",
    addressEn: "樂華邨九龍牛頭角樂華北邨樂華商場3樓316號舖",
    addressTc: "樂華邨九龍牛頭角樂華北邨樂華商場3樓316號舖",
    lat: 22.306,
    lng: 114.221,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-110",
    district: "Kwun_Tong",
    nameEn: "麗港城九龍觀塘茶果嶺道麗港城第一期商場地下",
    nameTc: "麗港城九龍觀塘茶果嶺道麗港城第一期商場地下",
    addressEn: "麗港城九龍觀塘茶果嶺道麗港城第一期商場地下",
    addressTc: "麗港城九龍觀塘茶果嶺道麗港城第一期商場地下",
    lat: 22.308,
    lng: 114.221,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-18-11",
    district: "North",
    nameEn: "粉嶺名都新界粉嶺粉嶺車站路18號粉嶺名都地下11",
    nameTc: "粉嶺名都新界粉嶺粉嶺車站路18號粉嶺名都地下11",
    addressEn: "15號舖",
    addressTc: "15號舖",
    lat: 22.494,
    lng: 114.122,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-5-16",
    district: "North",
    nameEn: "清河邨新界上水清曉路5號清河邨清河商場16號舖",
    nameTc: "清河邨新界上水清曉路5號清河邨清河商場16號舖",
    addressEn: "清河邨新界上水清曉路5號清河邨清河商場16號舖",
    addressTc: "清河邨新界上水清曉路5號清河邨清河商場16號舖",
    lat: 22.496,
    lng: 114.122,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-1-e146-2-e203",
    district: "Sai_Kung",
    nameEn: "厚德邨2新界將軍澳厚德商場東翼1樓E146號舖及2樓E203號舖",
    nameTc: "厚德邨2新界將軍澳厚德商場東翼1樓E146號舖及2樓E203號舖",
    addressEn: "厚德邨2新界將軍澳厚德商場東翼1樓E146號舖及2樓E203號舖",
    addressTc: "厚德邨2新界將軍澳厚德商場東翼1樓E146號舖及2樓E203號舖",
    lat: 22.314,
    lng: 114.26,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-dc",
    district: "Sai_Kung",
    nameEn: "翠林邨翠林邨 DC",
    nameTc: "翠林邨翠林邨 DC",
    addressEn: "PH-TTH 新界將軍澳翠琳路11號 翠林邨翠林新城5樓132 舖",
    addressTc: "PH-TTH 新界將軍澳翠琳路11號 翠林邨翠林新城5樓132 舖",
    lat: 22.316,
    lng: 114.26,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-mcw",
    district: "Sai_Kung",
    nameEn: "「西貢壹同」翠塘路翠塘路 MCW",
    nameTc: "「西貢壹同」翠塘路翠塘路 MCW",
    addressEn: "KN 新界西貢翠塘路1號 A三樓301及302號舖",
    addressTc: "KN 新界西貢翠塘路1號 A三樓301及302號舖",
    lat: 22.318,
    lng: 114.26,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-dc",
    district: "Sai_Kung",
    nameEn: "西貢花園西貢花園 DC",
    nameTc: "西貢花園西貢花園 DC",
    addressEn: "PH-TTH 新界西貢親民街16號西貢花園地下入口 部分及樓梯及1樓",
    addressTc: "PH-TTH 新界西貢親民街16號西貢花園地下入口 部分及樓梯及1樓",
    lat: 22.32,
    lng: 114.26,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-7b-46",
    district: "Sha_Tin",
    nameEn: "第一城\"新界沙田銀城街2號置富第一城‧樂薈地下7B, 46",
    nameTc: "第一城\"新界沙田銀城街2號置富第一城‧樂薈地下7B, 46",
    addressEn: "80號 \"",
    addressTc: "80號 \"",
    lat: 22.383,
    lng: 114.184,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-608-3-343",
    district: "Sha_Tin",
    nameEn: "馬鞍山廣場2新界沙田馬鞍山西沙路608號馬鞍山廣場3樓343",
    nameTc: "馬鞍山廣場2新界沙田馬鞍山西沙路608號馬鞍山廣場3樓343",
    addressEn: "363號舖",
    addressTc: "363號舖",
    lat: 22.385,
    lng: 114.184,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-ah",
    district: "Sha_Tin",
    nameEn: "偉華中心偉華中心 AH",
    nameTc: "偉華中心偉華中心 AH",
    addressEn: "KCH-LL 新界沙田正街11-17號偉華中心商場2樓6-7號舖",
    addressTc: "KCH-LL 新界沙田正街11-17號偉華中心商場2樓6-7號舖",
    lat: 22.387,
    lng: 114.184,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-ah",
    district: "Sha_Tin",
    nameEn: "愉翠商場愉翠商場 AH",
    nameTc: "愉翠商場愉翠商場 AH",
    addressEn: "YKF 新界沙田愉翠苑愉翠商場1樓104號舖",
    addressTc: "YKF 新界沙田愉翠苑愉翠商場1樓104號舖",
    lat: 22.375,
    lng: 114.186,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-mcw",
    district: "Sha_Tin",
    nameEn: "保泰街保泰街 MCW",
    nameTc: "保泰街保泰街 MCW",
    addressEn: "RC-RL 新界馬鞍山保泰街16號We Go Mall 3樓301號舖",
    addressTc: "RC-RL 新界馬鞍山保泰街16號We Go Mall 3樓301號舖",
    lat: 22.377,
    lng: 114.186,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-l001",
    district: "Sha_Tin",
    nameEn: "新翠商場新界沙田翠田街2號新翠邨街市地下L001號舖",
    nameTc: "新翠商場新界沙田翠田街2號新翠邨街市地下L001號舖",
    addressEn: "新翠商場新界沙田翠田街2號新翠邨街市地下L001號舖",
    addressTc: "新翠商場新界沙田翠田街2號新翠邨街市地下L001號舖",
    lat: 22.379,
    lng: 114.186,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-ah",
    district: "Sha_Tin",
    nameEn: "駿景園駿景園 AH",
    nameTc: "駿景園駿景園 AH",
    addressEn: "YKF 新界沙田火炭駿景路1號駿景廣場地下G1-G17號舖",
    addressTc: "YKF 新界沙田火炭駿景路1號駿景廣場地下G1-G17號舖",
    lat: 22.381,
    lng: 114.186,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-9-2-4",
    district: "Sham_Shui_Po",
    nameEn: "宇晴軒\"九龍荔枝角深盛路9號宇晴軒商場2層4",
    nameTc: "宇晴軒\"九龍荔枝角深盛路9號宇晴軒商場2層4",
    addressEn: "6,66號舖\"",
    addressTc: "6,66號舖\"",
    lat: 22.335,
    lng: 114.156,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-5",
    district: "Sham_Shui_Po",
    nameEn: "又一城九龍九龍塘達之路又一城地下香港鐵路層5號舖",
    nameTc: "又一城九龍九龍塘達之路又一城地下香港鐵路層5號舖",
    addressEn: "又一城九龍九龍塘達之路又一城地下香港鐵路層5號舖",
    addressTc: "又一城九龍九龍塘達之路又一城地下香港鐵路層5號舖",
    lat: 22.337,
    lng: 114.156,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-13",
    district: "Southern",
    nameEn: "香港仔中心香港香港仔南寧街13",
    nameTc: "香港仔中心香港香港仔南寧街13",
    addressEn: "23號ac1地下1及9號舖",
    addressTc: "23號ac1地下1及9號舖",
    lat: 22.241,
    lng: 114.146,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-88",
    district: "Southern",
    nameEn: "陽明山莊香港淺水灣大潭水塘道88號陽明山莊商場二樓",
    nameTc: "陽明山莊香港淺水灣大潭水塘道88號陽明山莊商場二樓",
    addressEn: "陽明山莊香港淺水灣大潭水塘道88號陽明山莊商場二樓",
    addressTc: "陽明山莊香港淺水灣大潭水塘道88號陽明山莊商場二樓",
    lat: 22.243,
    lng: 114.146,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-201",
    district: "Southern",
    nameEn: "置富花園香港薄扶林置富花園商場二樓201",
    nameTc: "置富花園香港薄扶林置富花園商場二樓201",
    addressEn: "202號舖",
    addressTc: "202號舖",
    lat: 22.245,
    lng: 114.146,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-13",
    district: "Southern",
    nameEn: "華貴商場2華貴邨華貴商場地下13號舖位",
    nameTc: "華貴商場2華貴邨華貴商場地下13號舖位",
    addressEn: "華貴商場2華貴邨華貴商場地下13號舖位",
    addressTc: "華貴商場2華貴邨華貴商場地下13號舖位",
    lat: 22.247,
    lng: 114.146,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-550-32",
    district: "Southern",
    nameEn: "碧瑤灣香港薄扶林域多利道550號碧瑤灣32",
    nameTc: "碧瑤灣香港薄扶林域多利道550號碧瑤灣32",
    addressEn: "40座地下",
    addressTc: "40座地下",
    lat: 22.249,
    lng: 114.146,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-16e-lg1",
    district: "Southern",
    nameEn: "壽臣山廣場香港壽臣山壽山村道16E號壽臣山廣場LG1號舖",
    nameTc: "壽臣山廣場香港壽臣山壽山村道16E號壽臣山廣場LG1號舖",
    addressEn: "壽臣山廣場香港壽臣山壽山村道16E號壽臣山廣場LG1號舖",
    addressTc: "壽臣山廣場香港壽臣山壽山村道16E號壽臣山廣場LG1號舖",
    lat: 22.251,
    lng: 114.146,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-3-302",
    district: "Southern",
    nameEn: "海怡半島2香港香港仔鴨脷洲海怡半島海怡廣場西座3樓302號舖",
    nameTc: "海怡半島2香港香港仔鴨脷洲海怡半島海怡廣場西座3樓302號舖",
    addressEn: "海怡半島2香港香港仔鴨脷洲海怡半島海怡廣場西座3樓302號舖",
    addressTc: "海怡半島2香港香港仔鴨脷洲海怡半島海怡廣場西座3樓302號舖",
    lat: 22.253,
    lng: 114.146,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-3-3-jch",
    district: "Southern",
    nameEn: "利東邨3利東邨3 JCH",
    nameTc: "利東邨3利東邨3 JCH",
    addressEn: "MS-BT 香港鴨脷洲利東邨道5號利東邨利東商場3樓1 號舖",
    addressTc: "MS-BT 香港鴨脷洲利東邨道5號利東邨利東商場3樓1 號舖",
    lat: 22.241,
    lng: 114.148,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-12-3-301",
    district: "Tai_Po",
    nameEn: "太和邨2新界大埔太和路12號太和邨太和廣場3樓301號舖",
    nameTc: "太和邨2新界大埔太和路12號太和邨太和廣場3樓301號舖",
    addressEn: "太和邨2新界大埔太和路12號太和邨太和廣場3樓301號舖",
    addressTc: "太和邨2新界大埔太和路12號太和邨太和廣場3樓301號舖",
    lat: 22.445,
    lng: 114.158,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-4-d-612",
    district: "Tai_Po",
    nameEn: "大埔中心新界大埔安邦路4號大埔超級城D區612",
    nameTc: "大埔中心新界大埔安邦路4號大埔超級城D區612",
    addressEn: "670號舖",
    addressTc: "670號舖",
    lat: 22.447,
    lng: 114.158,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-2-ah",
    district: "Tuen_Mun",
    nameEn: "富泰商場2富泰商場2 AH",
    nameTc: "富泰商場2富泰商場2 AH",
    addressEn: "JT 新界屯門屯貴路9號富泰商場2樓220-226號舖",
    addressTc: "JT 新界屯門屯貴路9號富泰商場2樓220-226號舖",
    lat: 22.385,
    lng: 113.973,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-398-1-1033",
    district: "Tsuen_Wan",
    nameEn: "愉景新城2新界荃灣青山公路荃灣段398號愉景新城1樓1033",
    nameTc: "愉景新城2新界荃灣青山公路荃灣段398號愉景新城1樓1033",
    addressEn: "34b及1069號舖",
    addressTc: "34b及1069號舖",
    lat: 22.367,
    lng: 114.109,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-229",
    district: "Tsuen_Wan",
    nameEn: "石圍角新城新界荃灣石圍角路石圍角商場二樓229",
    nameTc: "石圍角新城新界荃灣石圍角路石圍角商場二樓229",
    addressEn: "233 號",
    addressTc: "233 號",
    lat: 22.369,
    lng: 114.109,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-loc-139",
    district: "Tsuen_Wan",
    nameEn: "豪景花園新界荃灣青龍頭青山公路",
    nameTc: "豪景花園新界荃灣青龍頭青山公路",
    addressEn: "青龍頭段100號豪景花園第3期豪景花園商場地下",
    addressTc: "青龍頭段100號豪景花園第3期豪景花園商場地下",
    lat: 22.371,
    lng: 114.109,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-99-105",
    district: "Tuen_Mun",
    nameEn: "寶田邨新界屯門鳴琴路99號寶田商場105號舖",
    nameTc: "寶田邨新界屯門鳴琴路99號寶田商場105號舖",
    addressEn: "寶田邨新界屯門鳴琴路99號寶田商場105號舖",
    addressTc: "寶田邨新界屯門鳴琴路99號寶田商場105號舖",
    lat: 22.387,
    lng: 113.973,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-32",
    district: "Wan_Chai",
    nameEn: "跑馬地香港跑馬地山村道32",
    nameTc: "跑馬地香港跑馬地山村道32",
    addressEn: "40號豐寧大廈地下",
    addressTc: "40號豐寧大廈地下",
    lat: 22.273,
    lng: 114.167,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-9",
    district: "Wan_Chai",
    nameEn: "渣甸山香港半山區渣甸山春暉道9號地下",
    nameTc: "渣甸山香港半山區渣甸山春暉道9號地下",
    addressEn: "渣甸山香港半山區渣甸山春暉道9號地下",
    addressTc: "渣甸山香港半山區渣甸山春暉道9號地下",
    lat: 22.275,
    lng: 114.167,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-15-2-s229",
    district: "Wong_Tai_Sin",
    nameEn: "竹園2九龍黃大仙竹園道15號竹園商場2樓S229號舖",
    nameTc: "竹園2九龍黃大仙竹園道15號竹園商場2樓S229號舖",
    addressEn: "竹園2九龍黃大仙竹園道15號竹園商場2樓S229號舖",
    addressTc: "竹園2九龍黃大仙竹園道15號竹園商場2樓S229號舖",
    lat: 22.33,
    lng: 114.188,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-1",
    district: "Wong_Tai_Sin",
    nameEn: "慈正邨九龍慈雲山慈正邨慈正二期慈正商場地下1號舖",
    nameTc: "慈正邨九龍慈雲山慈正邨慈正二期慈正商場地下1號舖",
    addressEn: "慈正邨九龍慈雲山慈正邨慈正二期慈正商場地下1號舖",
    addressTc: "慈正邨九龍慈雲山慈正邨慈正二期慈正商場地下1號舖",
    lat: 22.332,
    lng: 114.188,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-28",
    district: "Wong_Tai_Sin",
    nameEn: "啟德花園九龍黃大仙啟德花園二期地下28號舖",
    nameTc: "啟德花園九龍黃大仙啟德花園二期地下28號舖",
    addressEn: "啟德花園九龍黃大仙啟德花園二期地下28號舖",
    addressTc: "啟德花園九龍黃大仙啟德花園二期地下28號舖",
    lat: 22.334,
    lng: 114.188,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-2-dc",
    district: "Wong_Tai_Sin",
    nameEn: "荷里活廣場2荷里活廣場2 DC",
    nameTc: "荷里活廣場2荷里活廣場2 DC",
    addressEn: "MY 九龍鑽石山荷里活廣場4樓401號舖",
    addressTc: "MY 九龍鑽石山荷里活廣場4樓401號舖",
    lat: 22.336,
    lng: 114.188,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-171-1",
    district: "Yau_Tsim_Mong",
    nameEn: "別樹一居九龍旺角太子道西171號別樹一居地下入口位置及1樓",
    nameTc: "別樹一居九龍旺角太子道西171號別樹一居地下入口位置及1樓",
    addressEn: "別樹一居九龍旺角太子道西171號別樹一居地下入口位置及1樓",
    addressTc: "別樹一居九龍旺角太子道西171號別樹一居地下入口位置及1樓",
    lat: 22.299,
    lng: 114.169,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-mcw",
    district: "Yau_Tsim_Mong",
    nameEn: "浪澄灣浪澄灣 MCW",
    nameTc: "浪澄灣浪澄灣 MCW",
    addressEn: "RC-JK 九龍大角咀海輝道8號浪澄灣2樓2號舖",
    addressTc: "RC-JK 九龍大角咀海輝道8號浪澄灣2樓2號舖",
    lat: 22.301,
    lng: 114.169,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-33-t-town-north-2-n206",
    district: "Yuen_Long",
    nameEn: "頌富廣場2新界天水圍天華路33號 T Town North 2樓N206",
    nameTc: "頌富廣場2新界天水圍天華路33號 T Town North 2樓N206",
    addressEn: "209號舖",
    addressTc: "209號舖",
    lat: 22.449,
    lng: 114.016,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-woo-12",
    district: "Yuen_Long",
    nameEn: "嘉湖 +Woo新界天水圍天恩路12",
    nameTc: "嘉湖 +Woo新界天水圍天恩路12",
    addressEn: "18號 +WOO 嘉湖1期2樓220號舖",
    addressTc: "18號 +WOO 嘉湖1期2樓220號舖",
    lat: 22.451,
    lng: 114.016,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-2-9-2-l101",
    district: "Yuen_Long",
    nameEn: "天瑞邨2新界天水圍天瑞路9號天瑞商場2樓L101號舖",
    nameTc: "天瑞邨2新界天水圍天瑞路9號天瑞商場2樓L101號舖",
    addressEn: "天瑞邨2新界天水圍天瑞路9號天瑞商場2樓L101號舖",
    addressTc: "天瑞邨2新界天水圍天瑞路9號天瑞商場2樓L101號舖",
    lat: 22.439,
    lng: 114.018,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
  {
    id: "food-angel-ah",
    district: "Yuen_Long",
    nameEn: "御庭居御庭居 AH",
    nameTc: "御庭居御庭居 AH",
    addressEn: "KCH-WW 新界元朗馬田路80號御庭居地下9-12及 15-19號舖",
    addressTc: "KCH-WW 新界元朗馬田路80號御庭居地下9-12及 15-19號舖",
    lat: 22.441,
    lng: 114.018,
    type: "collection_box",
    typeEn: "Food collection box",
    typeTc: "食物收集箱",
  },
];
