/** EPD Food Waste Recycling Spots 廚餘回收流動點 — source PDF as of 13 Jun 2026 */

export interface FoodWasteSpotLocation {
  id: string;
  district: string;
  nameEn: string;
  nameTc: string;
  addressEn: string;
  addressTc: string;
  lat: number;
  lng: number;
  timeEn: string;
  timeTc: string;
}

export const FOOD_WASTE_SPOT_LOCATIONS: FoodWasteSpotLocation[] = [
  {
    id: "food-waste-001-macdonnell-road-mid-levels-near-silvercrest",
    district: "Central_Western",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Macdonnell Road, Mid-Levels (near Silvercrest)",
    addressTc: "半山區麥當勞道（近聚安樓）",
    lat: 22.2751722,
    lng: 114.1571206,
    timeEn: "6:30 pm – 8:30 pm",
    timeTc: "6:30 晚上 – 8:30 晚上",
  },
  {
    id: "food-waste-002-parking-area-outside-exit-c-of-sai-ying-pun-mtr",
    district: "Central_Western",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Parking Area outside Exit C of Sai Ying Pun MTR Station",
    addressTc: "西營盤港鐵站 C 出口外停車處",
    lat: 22.286,
    lng: 114.154,
    timeEn: "6:30 pm – 8:30 pm",
    timeTc: "6:30 晚上 – 8:30 晚上",
  },
  {
    id: "food-waste-003-no-99-caine-road-central-near-albron-court",
    district: "Central_Western",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "No. 99 Caine Road, Central (near Albron Court)",
    addressTc: "中環堅道 99 號（近豐樂閣）",
    lat: 22.2810984,
    lng: 114.1522052,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-004-junction-of-forbes-street-and-davis-street-kenne",
    district: "Central_Western",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Forbes Street and Davis Street, Kennedy Town (near Sincere Western House)",
    addressTc: "堅尼地城科士街與爹核士街交界（近先施西環大廈）",
    lat: 22.286,
    lng: 114.154,
    timeEn: "8:30 pm – 10:30 pm",
    timeTc: "8:30 晚上 – 10:30 晚上",
  },
  {
    id: "food-waste-005-praya-kennedy-town-kennedy-town-near-brilliant-c",
    district: "Central_Western",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Praya Kennedy Town, Kennedy Town (near Brilliant Court)",
    addressTc: "堅尼地城堅彌地城海旁（近明珠閣）",
    lat: 22.284499,
    lng: 114.1305653,
    timeEn: "7:30 pm – 9:30 pm",
    timeTc: "7:30 晚上 – 9:30 晚上",
  },
  {
    id: "food-waste-006-junction-of-graham-street-and-hollywood-road-cen",
    district: "Central_Western",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Graham Street and Hollywood Road, Central (near Sun Fung Mansion)",
    addressTc: "中環嘉咸街與荷里活道交界（近新豐樓）",
    lat: 22.286,
    lng: 114.154,
    timeEn: "10:00 pm – 12:00 am",
    timeTc: "10:00 晚上 – 12:00 凌晨",
  },
  {
    id: "food-waste-007-junction-of-queen-s-road-central-and-cochrane-st",
    district: "Central_Western",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Queen's Road Central and Cochrane Street, Central (near 100QRC)",
    addressTc: "中環皇后大道中與閣麟街交界（近 100QRC）",
    lat: 22.286,
    lng: 114.154,
    timeEn: "10:00 pm – 12:00 am",
    timeTc: "10:00 晚上 – 12:00 凌晨",
  },
  {
    id: "food-waste-008-junction-of-third-street-and-centre-street-sai-y",
    district: "Central_Western",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Third Street and Centre Street, Sai Ying Pun (near rear exit of Sai Ying Pung Market)",
    addressTc: "西營盤第三街與正街交界（近西營盤街市後門）",
    lat: 22.286,
    lng: 114.154,
    timeEn: "10:00 pm – 12:00 am",
    timeTc: "10:00 晚上 – 12:00 凌晨",
  },
  {
    id: "food-waste-009-near-children-s-playground-on-whitty-street-shek",
    district: "Eastern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Near Children's Playground on Whitty Street, Shek Tong Tsui (near Kam Ling Court)",
    addressTc: "石塘咀屈地街兒童遊樂場（近金陵大廈）",
    lat: 22.284,
    lng: 114.224,
    timeEn: "10:00 pm – 12:00 am",
    timeTc: "10:00 晚上 – 12:00 凌晨",
  },
  {
    id: "food-waste-010-junction-of-wang-on-road-and-fook-yum-road-north",
    district: "Eastern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Wang On Road and Fook Yum Road, North Point (near Harbour Heights, Nam Fung Court)",
    addressTc: "北角宏安道與福蔭道交界（近海峰園南峰閣）",
    lat: 22.284,
    lng: 114.224,
    timeEn: "6:30 pm - 8:30 pm",
    timeTc: "6:30 晚上 - 8:30 晚上",
  },
  {
    id: "food-waste-011-b",
    district: "Eastern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "鰂魚涌芬尼街與海康街交界（近鰂魚涌港鐵站 B 出口）",
    addressTc: "鰂魚涌芬尼街與海康街交界（近鰂魚涌港鐵站 B 出口）",
    lat: 22.284,
    lng: 114.224,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-012-spot",
    district: "Eastern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "餘回收流動點 」，每晚以定時定點街站 或流動",
    addressTc: "餘回收流動點 」，每晚以定時定點街站 或流動",
    lat: 22.284,
    lng: 114.224,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-013-spot",
    district: "Eastern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "車的方式， 為附近小型商戶和居民提供廚餘回",
    addressTc: "車的方式， 為附近小型商戶和居民提供廚餘回",
    lat: 22.284,
    lng: 114.224,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-014-the-environmental-protection-department-has-set",
    district: "Eastern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "The Environmental Protection Department has set up 105 Food Waste Recycling Spots at different operate as kerbside booths or mobile truck at fixed hours and locations every night to provide food waste recycling service for nearby small business Junction of Finnie Street and Hoi Hong Street, Quarry Bay (near Quarry Bay MTR Station Exit B)",
    addressTc: "收服務。",
    lat: 22.284,
    lng: 114.224,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-015-junction-of-java-road-and-north-point-road-north",
    district: "Eastern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Java Road and North Point Road, North Point (near North Point Asia-Pac Commercial Centre)",
    addressTc: "北角渣華道與北角道交界（近北角亞太商業中心）",
    lat: 22.284,
    lng: 114.224,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-016-no-33-cloud-view-road-braemar-hill-north-point-o",
    district: "Eastern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "No. 33 Cloud View Road, Braemar Hill, North Point (outside Cloud View Road Shopping Centre)",
    addressTc: "北角寶馬山雲景道 33 號（雲景道購物中心對出）",
    lat: 22.2871588,
    lng: 114.1971815,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-017-junction-of-north-view-street-and-king-s-road-no",
    district: "Eastern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of North View Street and King's Road, North Point (near Hang Ying Building)",
    addressTc: "北角北景街與英皇道交界（近恆英大廈）",
    lat: 22.284,
    lng: 114.224,
    timeEn: "7:30 pm – 9:30 pm",
    timeTc: "7:30 晚上 – 9:30 晚上",
  },
  {
    id: "food-waste-018-mong-lung-street-sitting-out-area-shau-kei-wan-n",
    district: "Eastern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Mong Lung Street Sitting-out Area, Shau Kei Wan (near Tung Shing House)",
    addressTc: "筲箕灣望隆街休憩處（近東成樓）",
    lat: 22.2789515,
    lng: 114.2297884,
    timeEn: "8:30 pm – 10:30 pm",
    timeTc: "8:30 晚上 – 10:30 晚上",
  },
  {
    id: "food-waste-019-junction-of-marsh-road-and-lockhart-road-wan-cha",
    district: "Wan_Chai",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Marsh Road and Lockhart Road, Wan Chai (near Chuang’s Enterprises Building)",
    addressTc: "灣仔馬師道與駱克道交界（近莊士企業大廈）",
    lat: 22.277,
    lng: 114.173,
    timeEn: "8:00 pm – 10:00 pm",
    timeTc: "8:00 晚上 – 10:00 晚上",
  },
  {
    id: "food-waste-020-junction-of-johnston-road-and-fenwick-street-wan",
    district: "Wan_Chai",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Johnston Road and Fenwick Street, Wan Chai (outside the Chinese Methodist Church)",
    addressTc: "灣仔莊士敦道與分域街交界（循道衛理聯合教會香港堂對出）",
    lat: 22.277,
    lng: 114.173,
    timeEn: "8:30 pm – 10:30 pm",
    timeTc: "8:30 晚上 – 10:30 晚上",
  },
  {
    id: "food-waste-021-junction-of-burrows-street-and-cross-lane-wan-ch",
    district: "Wan_Chai",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Burrows Street and Cross Lane, Wan Chai (near Vine Centre)",
    addressTc: "灣仔巴路士街與交加里交界（近 Vine Centre）",
    lat: 22.277,
    lng: 114.173,
    timeEn: "9:00 pm – 11:00 pm",
    timeTc: "9:00 晚上 – 11:00 晚上",
  },
  {
    id: "food-waste-022-junction-of-canal-road-east-and-leighton-road-ca",
    district: "Wan_Chai",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Canal Road East and Leighton Road, Causeway Bay (under the flyover)",
    addressTc: "銅鑼灣堅拿道東與禮頓道交界（天橋底）",
    lat: 22.277,
    lng: 114.173,
    timeEn: "10:00 pm – 12:00 am",
    timeTc: "10:00 晚上 – 12:00 凌晨",
  },
  {
    id: "food-waste-023-junction-of-tung-lo-wan-road-and-wun-sha-street",
    district: "Wan_Chai",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Tung Lo Wan Road and Wun Sha Street, Tai Hang (opposite to Chinese Recreation Club)",
    addressTc: "大坑銅鑼灣道與浣紗街交界（中華遊樂會對面）",
    lat: 22.277,
    lng: 114.173,
    timeEn: "10:00 pm – 12:00 am",
    timeTc: "10:00 晚上 – 12:00 凌晨",
  },
  {
    id: "food-waste-024-public-pavement-outside-2-king-kwong-street-happ",
    district: "Wan_Chai",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement outside 2 King Kwong Street, Happy Valley (near King Kwong Mansion)",
    addressTc: "跑馬地景光街 2 號（近景光樓）",
    lat: 22.269101,
    lng: 114.1856635,
    timeEn: "10:00 pm – 12:00 am",
    timeTc: "10:00 晚上 – 12:00 凌晨",
  },
  {
    id: "food-waste-025-junction-of-ap-lei-chau-main-street-and-wai-fung",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Ap Lei Chau Main Street and Wai Fung Street, Ap Lei Chau (near Shun King Court)",
    addressTc: "鴨脷洲鴨脷洲大街與惠風街交界（近順景閣）",
    lat: 22.247,
    lng: 114.158,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-026-junction-of-shouson-hill-road-and-wong-chuk-hang",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Shouson Hill Road and Wong Chuk Hang Road, Wong Chuk Hang (near refuse collection point)",
    addressTc: "黃竹坑壽山村道及黃竹坑道交界（近垃圾站）",
    lat: 22.247,
    lng: 114.158,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-027-junction-of-wah-ting-street-and-yuet-hoi-street",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of  Wah Ting Street and Yuet Hoi Street, Ap Lei Chau (outside Ap Lei Chau Market)",
    addressTc: "鴨脷洲華庭街與悅海街交界（鴨脷洲街市外）",
    lat: 22.247,
    lng: 114.158,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-028-7-nam-ning-street-aberdeen-outside-aberdeen-cent",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "7 Nam Ning Street, Aberdeen (outside Aberdeen Centre)",
    addressTc: "香港仔南寧街 7 號（香港仔中心對出）",
    lat: 22.2482546,
    lng: 114.1534159,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-029-20-yue-fai-road-aberdeen-near-minibus-terminus",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "20 Yue Fai Road, Aberdeen (near minibus terminus)",
    addressTc: "香港仔漁暉道 20 號（近小巴總站）",
    lat: 22.2484152,
    lng: 114.1561662,
    timeEn: "7:00 pm – 9:00 pm",
    timeTc: "7:00 晚上 – 9:00 晚上",
  },
  {
    id: "food-waste-030-81-shek-pai-wan-road-tin-wan-opposite-to-south-v",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "81 Shek Pai Wan Road, Tin Wan (opposite to South View Garden)",
    addressTc: "田灣石排灣道 81 號（南景花園對面）",
    lat: 22.2497859,
    lng: 114.1471063,
    timeEn: "8:30 pm – 10:30 pm",
    timeTc: "8:30 晚上 – 10:30 晚上",
  },
  {
    id: "food-waste-031-junction-of-baker-street-and-ming-on-street-hung",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Baker Street and Ming On Street, Hung Hom (near Lux Theatre Building)",
    addressTc: "紅磡必嘉街與明安街交界（近寶石戲院大廈）#",
    lat: 22.247,
    lng: 114.158,
    timeEn: "6:30 pm - 8:00 pm",
    timeTc: "6:30 晚上 - 8:00 晚上",
  },
  {
    id: "food-waste-032-fuk-lo-tsun-road-kowloon-city-near-chi-chun-cour",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Fuk Lo Tsun Road, Kowloon City (near Chi Chun Court)",
    addressTc: "Fuk Lo Tsun Road, Kowloon City (near Chi Chun Court)",
    lat: 22.3298232,
    lng: 114.1876569,
    timeEn: "6:30 pm - 8:00 pm",
    timeTc: "6:30 晚上 - 8:00 晚上",
  },
  {
    id: "food-waste-033-661-673-gillies-avenue-north-hung-hom-near-cheon",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "661-673 Gillies Avenue North, Hung Hom (near Cheong Shing Court)",
    addressTc: "紅磡機利士北路 661 至 673 號（近昌盛金舖大樓）",
    lat: 22.247,
    lng: 114.158,
    timeEn: "6:30 pm - 8:00 pm",
    timeTc: "6:30 晚上 - 8:00 晚上",
  },
  {
    id: "food-waste-034-public-pavement-at-junction-of-pak-tai-street-an",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement at Junction of Pak Tai Street and San Shan Road, To Kwa Wan (near Jubilant Place)",
    addressTc: "土瓜灣北帝街與新山道交界（近欣榮花園）",
    lat: 22.247,
    lng: 114.158,
    timeEn: "6:30 pm - 8:00 pm",
    timeTc: "6:30 晚上 - 8:00 晚上",
  },
  {
    id: "food-waste-035-80-wuhu-street-outside-gillies-avenue-south-hung",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "80 Wuhu Street outside Gillies Avenue South, Hung Hom (near Yun Tat Commercial Building) 6 Ede Road, Kowloon Tong (near Jade Garden)",
    addressTc: "紅磡蕪湖街 80 號對出機利士南路（近潤達商業大廈）",
    lat: 22.247,
    lng: 114.158,
    timeEn: "6:30 pm - 8:00 pm",
    timeTc: "6:30 晚上 - 8:00 晚上",
  },
  {
    id: "food-waste-036-public-pavement-at-whampoa-garden-phase-5-oak-ma",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement at Whampoa Garden Phase 5 Oak Mansions Block 1, Hung Hom (near The Whampoa)",
    addressTc: "紅磡黃埔花園 5 期青樺苑 1 座對出行人路 （近黃埔號）",
    lat: 22.247,
    lng: 114.158,
    timeEn: "8:00 pm - 10:00 pm",
    timeTc: "8:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-037-public-pavement-outside-cascades-block-1-good-sh",
    district: "Southern",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement outside Cascades Block 1, Good Shepherd Street, Ho Man Tin",
    addressTc: "何文田牧愛街欣圖軒第一座對出行人路 #",
    lat: 22.247,
    lng: 114.158,
    timeEn: "8:30 pm - 10:30 pm",
    timeTc: "8:30 晚上 - 10:30 晚上",
  },
  {
    id: "food-waste-038-public-pavement-outside-sitting-out-area-in-ting",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement outside Sitting-out Area in Ting Yue Square, Ting On Street, Ngau Tau Kok  (near Sheung Heu Building)",
    addressTc: "牛頭角定安街定裕坊休憩處對出行人路（近雙喜大廈）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "6:30 pm - 8:30 pm",
    timeTc: "6:30 晚上 - 8:30 晚上",
  },
  {
    id: "food-waste-039-public-pavement-outside-yau-lee-building-yee-on",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement outside Yau Lee Building, Yee On Street, Ngau Tau Kok",
    addressTc: "牛頭角宜安街有利大樓對出行人路",
    lat: 22.313,
    lng: 114.225,
    timeEn: "6:30 pm - 8:30 pm",
    timeTc: "6:30 晚上 - 8:30 晚上",
  },
  {
    id: "food-waste-040-public-payment-of-ka-wing-street-near-yau-tong-c",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public payment of Ka Wing Street (near Yau Tong Centre Tower 4), Yau Tong",
    addressTc: "7:00 pm - 9:00 pm 油塘嘉榮街（近油塘中心第 4 座）對出行人路",
    lat: 22.313,
    lng: 114.225,
    timeEn: "6:30 pm - 8:30 pm",
    timeTc: "6:30 晚上 - 8:30 晚上",
  },
  {
    id: "food-waste-041-public-pavement-outside-kin-tak-house-hip-wo-str",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement outside Kin Tak House, Hip Wo Street, Kwun Tong",
    addressTc: "觀塘協和街建德大樓對出行人路",
    lat: 22.3156636,
    lng: 114.2258165,
    timeEn: "8:00 pm - 10:00 pm",
    timeTc: "8:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-042-public-pavement-outside-69-lei-yue-mun-praya-roa",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement outside 69 Lei Yue Mun Praya Road (near Kong Lung Seafood Restaurant)",
    addressTc: "鯉魚門海傍道 69 號（近港龍海鮮酒家）",
    lat: 22.2920837,
    lng: 114.2389529,
    timeEn: "9:00 pm - 11:00 pm",
    timeTc: "9:00 晚上 - 11:00 晚上",
  },
  {
    id: "food-waste-043-sham-shui-po-mtr-station-exit-d2-sham-shui-po-ne",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Sham Shui Po MTR Station Exit D2, Sham Shui Po (near Golden Computer Arcade)",
    addressTc: "深水埗港鐵深水埗站 D2 出口（近黃金電腦商場）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "9:00 pm - 11:00 pm",
    timeTc: "9:00 晚上 - 11:00 晚上",
  },
  {
    id: "food-waste-044-hing-wah-street-sham-shui-po-near-hing-wah-apart",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Hing Wah Street, Sham Shui Po (near Hing Wah Apartments)",
    addressTc: "7:00 pm - 9:00 pm 深水埗興華街（近海華麗軒）",
    lat: 22.3315774,
    lng: 114.1488128,
    timeEn: "9:00 pm - 11:00 pm",
    timeTc: "9:00 晚上 - 11:00 晚上",
  },
  {
    id: "food-waste-045-junction-of-hai-tan-street-and-yee-kuk-street-sh",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Hai Tan Street and Yee Kuk Street, Sham Shui Po (near Oi Man Sang)",
    addressTc: "深水埗海壇街與醫局街交界（近愛文生）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "9:00 pm - 11:00 pm",
    timeTc: "9:00 晚上 - 11:00 晚上",
  },
  {
    id: "food-waste-046-public-pavement-underneath-the-kwai-chung-road-f",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement underneath the Kwai Chung Road Flyover, Sham Shui Po (near the Lai Wan Mei Foo Social Centre for the Elderly)",
    addressTc: "深水埗葵涌道高架道路橋底行人路（近荔灣長者中心）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "7:30 pm - 9:30 pm",
    timeTc: "7:30 晚上 - 9:30 晚上",
  },
  {
    id: "food-waste-047-public-pavement-of-yen-chow-street-outside-milan",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement of Yen Chow Street outside Milan Place (near Dragon Centre)",
    addressTc: "深水埗米蘭軒對出向欽州街（近西九龍中心）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "7:30 pm - 9:30 pm",
    timeTc: "7:30 晚上 - 9:30 晚上",
  },
  {
    id: "food-waste-048-junction-of-kiu-kiang-street-and-castle-peak-roa",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Kiu Kiang Street and Castle Peak Road, Sham Shui Po (near Celebrity Commercial Centre) Wong Tai Sin",
    addressTc: "深水埗九江街與青山道交界（近名人商業中心）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "7:30 pm - 9:30 pm",
    timeTc: "7:30 晚上 - 9:30 晚上",
  },
  {
    id: "food-waste-049-public-pavement-at-junction-of-tak-ku-ling-road",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement at Junction of Tak Ku Ling Road and Lok Sin Road,",
    addressTc: "場）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "7:00 pm - 9:00 pm",
    timeTc: "7:00 晚上 - 9:00 晚上",
  },
  {
    id: "food-waste-050-spot",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "慈雲山雙鳳街與金鳳街交界對出行人路（慈雲山綜合家庭服務",
    addressTc: "慈雲山雙鳳街與金鳳街交界對出行人路（慈雲山綜合家庭服務",
    lat: 22.313,
    lng: 114.225,
    timeEn: "7:00 pm - 9:00 pm",
    timeTc: "7:00 晚上 - 9:00 晚上",
  },
  {
    id: "food-waste-051-public-pavement-at-junction-of-sheung-fung-stree",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement at Junction of Sheung Fung Street and Kam Fung Street, Tsz Wan Shan (opposite to Tsz Wan Shan Integrated Family Service Centre)",
    addressTc: "中心對面）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "7:00 pm - 9:00 pm",
    timeTc: "7:00 晚上 - 9:00 晚上",
  },
  {
    id: "food-waste-052-public-pavement-outside-shung-ling-street-sittin",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement outside Shung Ling Street Sitting-out Area, San Po Kong (near Shung Ling Building)",
    addressTc: "新蒲崗崇齡街休憩處對出行人路（近崇齡大廈）",
    lat: 22.3343575,
    lng: 114.1962103,
    timeEn: "7:00 pm - 9:00 pm",
    timeTc: "7:00 晚上 - 9:00 晚上",
  },
  {
    id: "food-waste-053-public-pavement-outside-man-po-building-yuk-wah",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement outside Man Po Building, Yuk Wah Crescent, Tsz Wan Shan",
    addressTc: "慈雲山毓華里近萬寶大廈對出行人路",
    lat: 22.313,
    lng: 114.225,
    timeEn: "7:00 pm - 9:00 pm",
    timeTc: "7:00 晚上 - 9:00 晚上",
  },
  {
    id: "food-waste-054-public-pavement-outside-18-wan-fung-street-tsz-w",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement outside 18 Wan Fung Street, Tsz Wan Shan (near Wah Chung Mansion)",
    addressTc: "慈雲山環鳳街 18 號對出行人路（近華頌樓）",
    lat: 22.3437361,
    lng: 114.1981116,
    timeEn: "7:30 pm - 9:30 pm",
    timeTc: "7:30 晚上 - 9:30 晚上",
  },
  {
    id: "food-waste-055-21-pok-man-street-mong-kok-near-peony-house-west",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "21 Pok Man Street, Mong Kok (near Peony House West Block)",
    addressTc: "旺角博文街 21 號（近富貴大廈西座）",
    lat: 22.3194763,
    lng: 114.1604899,
    timeEn: "7:00 pm - 9:00 pm",
    timeTc: "7:00 晚上 - 9:00 晚上",
  },
  {
    id: "food-waste-056-yau-ma-tei-mtr-station-exit-a1-yau-mai-tei-near",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Yau Ma Tei MTR Station Exit A1, Yau Mai Tei (near Bell House)",
    addressTc: "油麻地港鐵油麻地站 A1 出口（近寶寧大廈）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "7:30 pm - 9:30 pm",
    timeTc: "7:30 晚上 - 9:30 晚上",
  },
  {
    id: "food-waste-057-412-portland-street-prince-edward-near-ju-xing-h",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "412 Portland Street, Prince Edward (near Ju Xing Home)",
    addressTc: "太子砵蘭街 412 號（近聚興家）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "7:30 pm - 9:30 pm",
    timeTc: "7:30 晚上 - 9:30 晚上",
  },
  {
    id: "food-waste-058-east-tsim-sha-tsui-mtr-station-exit-n2-tsim-sha",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "East Tsim Sha Tsui MTR Station Exit N2, Tsim Sha Tsui  (near Century House)",
    addressTc: "尖沙咀港鐵尖東站 N2 出口（近世紀商業大廈）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "7:30 pm - 9:30 pm",
    timeTc: "7:30 晚上 - 9:30 晚上",
  },
  {
    id: "food-waste-059-junction-of-hak-po-street-and-pak-po-street-mong",
    district: "Kwun_Tong",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Hak Po Street and Pak Po Street, Mong Kok (near Tak Po House)",
    addressTc: "旺角黑布街和白布街交界（近德寶樓）",
    lat: 22.313,
    lng: 114.225,
    timeEn: "8:00 pm - 10:00 pm",
    timeTc: "8:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-060-junction-of-temple-street-and-nanking-street-jor",
    district: "Kwai_Tsing",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Temple Street and Nanking Street, Jordan (near Nanking Building)",
    addressTc: "佐敦廟街與南京街交界（近南京大廈）",
    lat: 22.358,
    lng: 114.128,
    timeEn: "8:00 pm - 10:00 pm",
    timeTc: "8:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-061-21-kwong-fai-circuit-kwai-chung-near-cheong-fat",
    district: "Kwai_Tsing",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "21 Kwong Fai Circuit, Kwai Chung (near Cheong Fat Building)",
    addressTc: "葵涌光輝圍 21 號（近昌發大廈）",
    lat: 22.3680302,
    lng: 114.1330874,
    timeEn: "6:00 pm - 8:00 pm",
    timeTc: "6:00 晚上 - 8:00 晚上",
  },
  {
    id: "food-waste-062-107-tai-loong-street-kwai-chung-near-cheong-wing",
    district: "Kwai_Tsing",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "107 Tai Loong Street, Kwai Chung (near Cheong Wing Mansion)",
    addressTc: "葵涌大隴街 107 號（近昌榮樓）",
    lat: 22.3648166,
    lng: 114.1372227,
    timeEn: "6:15 pm - 8:15 pm",
    timeTc: "6:15 晚上 - 8:15 晚上",
  },
  {
    id: "food-waste-063-outside-shek-yam-road-rest-garden-no-2-shek-yam",
    district: "Kwai_Tsing",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Outside Shek Yam Road Rest Garden No.2, Shek Yam Road, Kwai Chung (near Kwong Fai Building)",
    addressTc: "葵涌石蔭路第二休憩花園對出（近光輝樓）",
    lat: 22.358,
    lng: 114.128,
    timeEn: "6:30 pm - 8:30 pm",
    timeTc: "6:30 晚上 - 8:30 晚上",
  },
  {
    id: "food-waste-064-junction-of-lai-fong-street-and-shun-fong-street",
    district: "Kwai_Tsing",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Lai Fong Street and Shun Fong Street, Kwai Chung (near Victory Court)",
    addressTc: "葵涌禮芳街與信芳街交界（近豪勝閣）",
    lat: 22.358,
    lng: 114.128,
    timeEn: "7:00 pm - 9:00 pm",
    timeTc: "7:00 晚上 - 9:00 晚上",
  },
  {
    id: "food-waste-065-3-tak-tai-path-kwai-chung-near-tak-tai-court",
    district: "Kwai_Tsing",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "3 Tak Tai Path, Kwai Chung (near Tak Tai Court)",
    addressTc: "葵涌德大徑 3 號（近德大閣）",
    lat: 22.3693365,
    lng: 114.1232937,
    timeEn: "7:15 pm - 9:15 pm",
    timeTc: "7:15 晚上 - 9:15 晚上",
  },
  {
    id: "food-waste-066-tsing-king-road-tsing-yi-near-st-paul-s-village",
    district: "Kwai_Tsing",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Tsing King Road, Tsing Yi (near St. Paul’s Village)",
    addressTc: "青衣青敬路（近聖保祿村）",
    lat: 22.360156,
    lng: 114.1031401,
    timeEn: "7:30 pm – 9:30 pm",
    timeTc: "7:30 晚上 – 9:30 晚上",
  },
  {
    id: "food-waste-067-junction-of-san-hong-street-tsun-fu-street-sheun",
    district: "North",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of San Hong Street & Tsun Fu Street, Sheung Shui",
    addressTc: "上水新康街及巡撫街交界",
    lat: 22.494,
    lng: 114.138,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-068-junction-of-san-sing-avenue-fu-hing-street-sheun",
    district: "North",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of San Sing Avenue & Fu Hing Street, Sheung Shui (near subway exit)",
    addressTc: "上水新成路及符興街交界 （近行人隧道口）",
    lat: 22.494,
    lng: 114.138,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-069-san-wan-road-fanling-near-fanling-centre",
    district: "North",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "San Wan Road, Fanling (near Fanling Centre)",
    addressTc: "粉嶺新運路（近粉嶺中心）",
    lat: 22.4942586,
    lng: 114.1380186,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-070-lui-ming-road-fanling-near-wah-ming-estate-bus-t",
    district: "North",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Lui Ming Road, Fanling (near Wah Ming Estate Bus Terminus)",
    addressTc: "粉嶺雷鳴路（近華明邨巴士總站）",
    lat: 22.4852468,
    lng: 114.1407334,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-071-wo-tai-street-luen-wo-hui-near-union-plaza",
    district: "Sai_Kung",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Wo Tai Street, Luen Wo Hui (near Union Plaza)",
    addressTc: "聯和墟和泰街（近海聯廣場）",
    lat: 22.5005957,
    lng: 114.1431605,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-072-po-tung-road-diagonal-to-temple-car-park",
    district: "Sai_Kung",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Po Tung Road (diagonal to Temple Car Park)",
    addressTc: "普通道（天后古廟停車場斜對面）",
    lat: 22.381648,
    lng: 114.2707688,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-073-sai-kung-hoi-pong-square-near-mini-bus-terminus",
    district: "Sai_Kung",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Sai Kung Hoi Pong Square (near Mini-bus Terminus)",
    addressTc: "西貢海傍廣場（近小巴總站）",
    lat: 22.3815137,
    lng: 114.2734462,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-074-public-pavement-outside-bauhinia-garden-multi-st",
    district: "Sai_Kung",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement outside Bauhinia Garden Multi-storey Car Park, Po Yap Road, Tseung Kwan O",
    addressTc: "將軍澳寶邑路寶盈花園多層停車場對出行人路",
    lat: 22.3076036,
    lng: 114.2624516,
    timeEn: "8:00 pm -10:00 pm",
    timeTc: "8:00 晚上 -10:00 晚上",
  },
  {
    id: "food-waste-075-public-pavement-outside-po-lam-estate-multipurpo",
    district: "Sha_Tin",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Public pavement outside Po Lam Estate Multipurpose Hall, Tseung Kwan O",
    addressTc: "將軍澳寶琳邨文娛活動會堂對出行人路",
    lat: 22.381,
    lng: 114.188,
    timeEn: "8:00 pm -10:00 pm",
    timeTc: "8:00 晚上 -10:00 晚上",
  },
  {
    id: "food-waste-076-tsuen-nam-road-tai-wai-near-grandway-garden",
    district: "Sha_Tin",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Tsuen Nam Road, Tai Wai (near Grandway Garden)",
    addressTc: "大圍村南道（近富嘉花園）",
    lat: 22.3742633,
    lng: 114.1795508,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-077-junction-of-hin-keng-street-and-hin-tin-street-t",
    district: "Sha_Tin",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Hin Keng Street and Hin Tin Street, Tai Wai (outside Sheung Keng Hau Village)",
    addressTc: "大圍顯徑街及顯田街交界（上徑口村外）",
    lat: 22.381,
    lng: 114.188,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-078-tin-sam-street-tai-wai-pavement-next-to-tin-sam",
    district: "Sha_Tin",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Tin Sam Street, Tai Wai (Pavement next to Tin Sam Garden No.3)",
    addressTc: "大圍田心街（田心第三花園對出行人路）",
    lat: 22.3692152,
    lng: 114.1796989,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-079-yi-shing-square-sha-tin-wai-near-lai-shing-garde",
    district: "Sha_Tin",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Yi Shing Square, Sha Tin Wai (near Lai Shing Garden)",
    addressTc: "沙田圍怡成坊（近勵城花園）",
    lat: 22.3805217,
    lng: 114.1956179,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-080-kwong-sin-street-siu-lek-yuen-near-siu-lek-yuen",
    district: "Sha_Tin",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Kwong Sin Street, Siu Lek Yuen (near Siu Lek Yuen Tsuen entrance)",
    addressTc: "小瀝源廣善街（近小瀝源村路口）",
    lat: 22.3836275,
    lng: 114.214147,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-081-no-1-ngan-shing-street-city-one-shatin-near-pak",
    district: "Sha_Tin",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "No. 1 Ngan Shing Street, City One Shatin (near Pak Tak Street)",
    addressTc: "沙田第一城銀城街 1 號（近百得街）",
    lat: 22.381,
    lng: 114.188,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-082-chevalier-garden-ma-on-shan-near-bus-terminus",
    district: "Tai_Po",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Chevalier Garden, Ma On Shan (near Bus Terminus)",
    addressTc: "馬鞍山富安花園（近巴士總站）",
    lat: 22.4076764,
    lng: 114.2224323,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-083-nam-wan-road-near-wan-loi-house-wan-tau-tong-est",
    district: "Tai_Po",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Nam Wan Road (near Wan Loi House, Wan Tau Tong Estate)",
    addressTc: "南運路（近運頭塘邨運來樓）",
    lat: 22.4475637,
    lng: 114.1720633,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-084-tai-ming-lane-near-tai-ming-lane-square",
    district: "Tai_Po",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Tai Ming Lane (near Tai Ming Lane Square)",
    addressTc: "大明里（近大明里廣場）",
    lat: 22.447436,
    lng: 114.1676796,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-085-junction-of-kwong-fuk-road-and-tsing-yuen-street",
    district: "Tai_Po",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Kwong Fuk Road and Tsing Yuen Street (near Kwong Fuk Place)",
    addressTc: "廣福道及靖遠街交界（近廣福華庭）",
    lat: 22.45,
    lng: 114.164,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-086-on-chee-road-near-jade-plaza",
    district: "Tai_Po",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "On Chee Road (near Jade Plaza)",
    addressTc: "安慈路（近翠屏花園）",
    lat: 22.4528702,
    lng: 114.1680298,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-087-tai-po-tai-wo-road-near-greenery-plaza",
    district: "Tai_Po",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Tai Po Tai Wo Road (near Greenery Plaza)",
    addressTc: "大埔太和路（近翠怡花園）",
    lat: 22.4510614,
    lng: 114.1750302,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-088-po-nga-road-near-tsui-wo-house-tai-wo-estate",
    district: "Tsuen_Wan",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Po Nga Road (near Tsui Wo House, Tai Wo Estate)",
    addressTc: "寶雅路（近太和邨翠和樓）",
    lat: 22.4518925,
    lng: 114.1598483,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-089-118-chuen-lung-street-tsuen-wan-near-optimall",
    district: "Tsuen_Wan",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "118 Chuen Lung Street, Tsuen Wan (near Optimall)",
    addressTc: "荃灣川龍街 118 號（近百悅坊）",
    lat: 22.3691767,
    lng: 114.1149146,
    timeEn: "6:00 pm - 8:00 pm",
    timeTc: "6:00 晚上 - 8:00 晚上",
  },
  {
    id: "food-waste-090-junction-of-chung-on-street-and-tsuen-wan-market",
    district: "Tsuen_Wan",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Chung On Street and Tsuen Wan Market Street, Tsuen Wan (near Tsuen Wan Market)",
    addressTc: "荃灣街市街與眾安街交界（近荃灣街市）",
    lat: 22.371,
    lng: 114.114,
    timeEn: "6:30 pm - 8:30 pm",
    timeTc: "6:30 晚上 - 8:30 晚上",
  },
  {
    id: "food-waste-091-62-heung-wo-street-tsuen-wan-near-good-view-mans",
    district: "Tsuen_Wan",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "62 Heung Wo Street, Tsuen Wan (near Good View Mansion)",
    addressTc: "荃灣享和街 62 號（近好景唐樓）",
    lat: 22.3718499,
    lng: 114.1115117,
    timeEn: "7:00 pm - 9:00 pm",
    timeTc: "7:00 晚上 - 9:00 晚上",
  },
  {
    id: "food-waste-092-junction-of-lung-yue-road-and-lung-tang-road-tsi",
    district: "Tsuen_Wan",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Lung Yue Road and Lung Tang Road, Tsing Lung Tau, Tsuen Wan (near Royal Sea Crest)",
    addressTc: "荃灣青龍頭龍如路與龍騰路交界（近帝華軒）",
    lat: 22.371,
    lng: 114.114,
    timeEn: "7:00 pm - 9:00 pm",
    timeTc: "7:00 晚上 - 9:00 晚上",
  },
  {
    id: "food-waste-093-on-wing-street-tsuen-wan-near-fortune-mansion",
    district: "Tsuen_Wan",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "On Wing Street, Tsuen Wan (near Fortune Mansion)",
    addressTc: "荃灣安榮街（近富榮大廈）",
    lat: 22.3727014,
    lng: 114.115765,
    timeEn: "7:15 pm - 9:15 pm",
    timeTc: "7:15 晚上 - 9:15 晚上",
  },
  {
    id: "food-waste-094-sham-tseng-tsuen-wan-near-fu-kee-restaurant",
    district: "Tsuen_Wan",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Sham Tseng, Tsuen Wan (near Fu Kee Restaurant)",
    addressTc: "荃灣深井（近傅記茶餐廳）",
    lat: 22.3676522,
    lng: 114.0597802,
    timeEn: "7:30 pm - 9:30 pm",
    timeTc: "7:30 晚上 - 9:30 晚上",
  },
  {
    id: "food-waste-095-tsing-shan-square-near-tsing-shan-children-s-pla",
    district: "Tuen_Mun",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Tsing Shan Square near Tsing Shan Children's Playground (opposite Wah Lok Mansion)",
    addressTc: "青山坊近青山兒童遊樂場（華樂大廈對面）",
    lat: 22.391,
    lng: 113.977,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-096-tak-ching-count-open-space-opposite-to-hoi-shing",
    district: "Tuen_Mun",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Tak Ching Count (open space opposite to Hoi Shing Building )",
    addressTc: "德政圍（海盛大廈對面空地）",
    lat: 22.391,
    lng: 113.977,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-097-junction-of-yan-oi-tong-circuit-and-kei-lun-path",
    district: "Tuen_Mun",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Yan Oi Tong Circuit and Kei Lun Path, San Hui (near Hang Fuk Building)",
    addressTc: "新墟仁愛堂街與麒麟徑交界（近幸福樓）",
    lat: 22.391,
    lng: 113.977,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-098-junction-of-tsing-hang-path-and-tsing-ling-path",
    district: "Tuen_Mun",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Tsing Hang Path and Tsing Ling Path, San Hui (near Elite Garden)",
    addressTc: "新墟青杏徑與青菱徑交界（近雅麗花園）",
    lat: 22.391,
    lng: 113.977,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-099-lam-tei-open-area-near-block-2-e-lu",
    district: "Yuen_Long",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Lam Tei (open area near Block 2, E Lu)",
    addressTc: "藍地（怡廬 2 座對出空地）",
    lat: 22.4186987,
    lng: 113.981894,
    timeEn: "7:00 pm - 10:00 pm",
    timeTc: "7:00 晚上 - 10:00 晚上",
  },
  {
    id: "food-waste-100-on-hing-street-yuen-long-open-space-between-ho-c",
    district: "Yuen_Long",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "On Hing Street, Yuen Long (open space between Ho Choi Building and On Fai Building)",
    addressTc: "元朗安興街（好彩洋樓及安輝樓之間空地）",
    lat: 22.4458985,
    lng: 114.0281678,
    timeEn: "7:00 pm – 10:00 pm",
    timeTc: "7:00 晚上 – 10:00 晚上",
  },
  {
    id: "food-waste-101-ping-cheong-path-long-ping-near-sir-denys-robert",
    district: "Yuen_Long",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Ping Cheong Path, Long Ping (near Sir Denys Roberts Squash Court)",
    addressTc: "朗屏屏昌徑（近羅弼時爵士壁球場）",
    lat: 22.445,
    lng: 114.022,
    timeEn: "7:00 pm – 10:00 pm",
    timeTc: "7:00 晚上 – 10:00 晚上",
  },
  {
    id: "food-waste-102-rain-shelter-at-wang-lok-street-yuen-long-near-e",
    district: "Yuen_Long",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Rain Shelter at Wang Lok Street, Yuen Long (near Exit A of Long Ping MTR Station)",
    addressTc: "元朗宏樂街避雨亭（近港鐵朗屏站Ａ出口）",
    lat: 22.445,
    lng: 114.022,
    timeEn: "7:00 pm – 10:00 pm",
    timeTc: "7:00 晚上 – 10:00 晚上",
  },
  {
    id: "food-waste-103-junction-of-kau-yuk-road-and-sai-yu-path-near-ko",
    district: "Yuen_Long",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Junction of Kau Yuk Road and Sai Yu Path (near KOLOUR‧Yuen Long)",
    addressTc: "元朗教育路與西裕徑交界（近元朗千色匯）",
    lat: 22.445,
    lng: 114.022,
    timeEn: "7:00 pm – 10:00 pm",
    timeTc: "7:00 晚上 – 10:00 晚上",
  },
  {
    id: "food-waste-104-shui-che-kwun-lane-open-space-between-pearl-hous",
    district: "Yuen_Long",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Shui Che Kwun Lane (open space between Pearl House and Golden Plaza)",
    addressTc: "水車館里（萬金中心與明珠樓之間）",
    lat: 22.4449129,
    lng: 114.0315651,
    timeEn: "7:00 pm – 10:00 pm",
    timeTc: "7:00 晚上 – 10:00 晚上",
  },
  {
    id: "food-waste-105-open-space-outside-fung-kwan-street-garden-at-fu",
    district: "Yuen_Long",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Open space outside Fung Kwan Street Garden at Fung Kwan Path (near Ho Shun King Building)",
    addressTc: "鳳群徑鳳群街花園對出空地 （近好順景大廈）",
    lat: 22.445,
    lng: 114.022,
    timeEn: "7:00 pm – 10:00 pm",
    timeTc: "7:00 晚上 – 10:00 晚上",
  },
  {
    id: "food-waste-106-open-space-opposite-hung-tak-road-sitting-out-ar",
    district: "Yuen_Long",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Open Space opposite Hung Tak Road Sitting-out Area No.2 (near Treasure Court)",
    addressTc: "洪水橋洪德路二號休憩處對出空地（近翠珊園）",
    lat: 22.445,
    lng: 114.022,
    timeEn: "7:00 pm – 10:00 pm",
    timeTc: "7:00 晚上 – 10:00 晚上",
  },
  {
    id: "food-waste-107-kam-tin-road-near-kam-tin-post-office",
    district: "Yuen_Long",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Kam Tin Road (near Kam Tin Post Office)",
    addressTc: "錦田公路（近錦田郵政局）",
    lat: 22.4412093,
    lng: 114.0888902,
    timeEn: "7:00 pm – 10:00 pm",
    timeTc: "7:00 晚上 – 10:00 晚上",
  },
  {
    id: "food-waste-108-refuse-collection-point-near-ha-tsuen-heung-arch",
    district: "Yuen_Long",
    nameEn: "Food Waste Recycling Spot",
    nameTc: "廚餘回收流動點",
    addressEn: "Refuse collection point near Ha Tsuen Heung Archway",
    addressTc: "廈村鄉牌坊旁垃圾收集站",
    lat: 22.445,
    lng: 114.022,
    timeEn: "7:00 pm – 10:00 pm",
    timeTc: "7:00 晚上 – 10:00 晚上",
  },
];
