/**
 * Watsons HK/Macau store locations for skincare container recycling.
 * Source: 20260508_Storelist_updated-pages-deleted.pdf (official Watsons store list).
 * Service hours: 10:00 AM – 9:00 PM at all listed branches.
 */
export const WATSONS_STORE_HOURS_EN = "10:00 AM – 9:00 PM daily";
export const WATSONS_STORE_HOURS_TC = "每日上午10時至晚上9時";

export const WATSONS_STORE_LOCATIONS = [
  {
    storeId: "wtc-fortune-centre",
    district: "Wan_Chai",
    nameEn: "Fortune Centre",
    nameTc: "恩平中心",
    lat: 22.2756,
    lng: 114.17268,
    addressEn: "Shop 3-10 of G/F, Whole 1/F & 2/F Fortune Centre, 44-48 Yun Ping Road, Causeway Bay, Hong Kong",
    addressTc: "香港銅鑼灣恩平道44-48號恩平中心地舖, 1樓及2樓",
  },
  {
    storeId: "wtc-jp-plaza",
    district: "Wan_Chai",
    nameEn: "JP Plaza",
    nameTc: "翡翠明珠廣場",
    lat: 22.27664,
    lng: 114.173,
    addressEn: "Shop No. 32A & 32B, G/F, JP Plaza, 22 Paterson Street, Causeway Bay",
    addressTc: "銅鑼灣百德新街22號地下32A及32B舖",
  },
  {
    storeId: "wtc-wah-ming-centre",
    district: "Central_Western",
    nameEn: "Wah Ming Centre",
    nameTc: "華明中心",
    lat: 22.2848,
    lng: 114.14516,
    addressEn: "G/F, Wah Ming Centre, 396 Des Voeux Road West, Hong Kong",
    addressTc: "德輔道西396號華明中心地下",
  },
  {
    storeId: "wtc-belchers-hill",
    district: "Central_Western",
    nameEn: "Belcher's Hill",
    nameTc: "寶雅山",
    lat: 22.28752,
    lng: 114.14508,
    addressEn: "Shop 1 & 2, Lower Ground Floor, Belcher's Hill, 42-44 Belcher's Street, Kennedy Town, Hong Kong",
    addressTc: "堅尼地城卑路乍街42至44號寶雅山低層地下1及2號舖",
  },
  {
    storeId: "wtc-tin-hau",
    district: "Eastern",
    nameEn: "Tin Hau",
    nameTc: "天后",
    lat: 22.28492,
    lng: 114.22564,
    addressEn: "Shop C, C1 & D, G/F, Kiu Hing Mansion, 14 King's Road, North Point, Hong Kong",
    addressTc: "北角英皇道十四號僑興大廈地下C, C1 & D",
  },
  {
    storeId: "wtc-hennessy-road",
    district: "Wan_Chai",
    nameEn: "Hennessy Road",
    nameTc: "軒尼詩道",
    lat: 22.27712,
    lng: 114.17364,
    addressEn: "G/F & M/F, 205-207 Hennessy Road, Wanchai, Hong Kong",
    addressTc: "軒尼詩道205-207號廣德大廈地下及閣樓",
  },
  {
    storeId: "wtc-shun-tak-centre",
    district: "Central_Western",
    nameEn: "Shun Tak Centre",
    nameTc: "信德中心",
    lat: 22.28672,
    lng: 114.14564,
    addressEn: "Unit 291-293, 2/F, Shun Tak Centre, 200 Connaught Road Central, Hong Kong",
    addressTc: "德輔道中200號信德中心二樓291-293號",
  },
  {
    storeId: "wtc-centre-street",
    district: "Central_Western",
    nameEn: "Centre Street",
    nameTc: "正街",
    lat: 22.28792,
    lng: 114.14508,
    addressEn: "Ground Floor, No. 13-15 Centre Street, Sai Ying Pun, Hong Kong",
    addressTc: "西營盤正街13-15號地舖",
  },
  {
    storeId: "wtc-tung-lo-wan-road",
    district: "Wan_Chai",
    nameEn: "Tung Lo Wan Road",
    nameTc: "銅鑼灣道",
    lat: 22.2756,
    lng: 114.17316,
    addressEn: "Shop A, G/F, Cathay Mansion, 3-5 Tung Lo Wan Road, Causeway Bay, HK",
    addressTc: "銅鑼灣道3-5號國泰大廈A座2號舖",
  },
  {
    storeId: "wtc-united-centre",
    district: "Central_Western",
    nameEn: "United Centre",
    nameTc: "統一中心",
    lat: 22.28688,
    lng: 114.14436,
    addressEn: "Shop 1003-1004, 1/F, United Centre, 95 Queensway Road, Hong Kong",
    addressTc: "金鐘道95號統一中心1003-1004號",
  },
  {
    storeId: "wtc-pacific-place-l2",
    district: "Central_Western",
    nameEn: "Pacific Place Level 2",
    nameTc: "太古廣場",
    lat: 22.28696,
    lng: 114.1446,
    addressEn: "Shop 204, Level 2, Pacific Place, Phase II, 88 Queensway, HK",
    addressTc: "金鐘道88號太古廣場二期2樓204號舖",
  },
  {
    storeId: "wtc-admiralty-centre",
    district: "Central_Western",
    nameEn: "Admiralty Centre",
    nameTc: "金鐘海富中心",
    lat: 22.28608,
    lng: 114.14468,
    addressEn: "Shop 23-26, 81-83, 1/F Podium, Admiralty Centre, Admiralty, HK",
    addressTc: "金鐘海富中心一樓平台23-26, 81-83號舖",
  },
  {
    storeId: "wtc-times-square",
    district: "Wan_Chai",
    nameEn: "Times Square",
    nameTc: "時代廣場",
    lat: 22.27696,
    lng: 114.1734,
    addressEn: "Shop No.927-928, 9th Floor, Times Square, Causeway Bay, Hong Kong",
    addressTc: "銅鑼灣時代廣場9樓927-928號舖",
  },
  {
    storeId: "wtc-hopewell-centre",
    district: "Wan_Chai",
    nameEn: "Hopewell Centre",
    nameTc: "合和中心",
    lat: 22.27776,
    lng: 114.17244,
    addressEn: "Shop 301-306, Hopewell Centre, 183 Queen's Road East, Wanchai, Hong Kong",
    addressTc: "灣仔皇后大道東183號合和中心三樓301-306號",
  },
  {
    storeId: "wtc-fook-sing-court",
    district: "Central_Western",
    nameEn: "Fook Sing Court",
    nameTc: "福陞閣",
    lat: 22.28776,
    lng: 114.14492,
    addressEn: "Designated portion on G/F, Fook Sing Court, 378 Queen's Road Central, HK",
    addressTc: "皇后大道中378號福陞閣地下指定部份",
  },
  {
    storeId: "wtc-melbourne-plaza",
    district: "Central_Western",
    nameEn: "Melbourne Plaza",
    nameTc: "萬邦行",
    lat: 22.28656,
    lng: 114.14476,
    addressEn: "Shop G1-A, G/F, Melbourne Plaza, 33 Queen's Road Central, Hong Kong",
    addressTc: "中環皇后大道中33號萬邦行地下G1-A舖",
  },
  {
    storeId: "wtc-hong-kong-station",
    district: "Central_Western",
    nameEn: "Hong Kong Station",
    nameTc: "香港站",
    lat: 22.28424,
    lng: 114.14444,
    addressEn: "Concession HOK 55, Unpaid Concourse, MTR Hong Kong Station, Central, HK",
    addressTc: "港鐵香港站非入閘區大堂55號舖",
  },
  {
    storeId: "wtc-des-voeux-33",
    district: "Central_Western",
    nameEn: "Des Voeux Road Central 33",
    nameTc: "德輔道中33號",
    lat: 22.2868,
    lng: 114.14484,
    addressEn: "Whole Shop on G/F, No.33 Des Voeux Road Central, Central, HK",
    addressTc: "德輔道中33號地下",
  },
  {
    storeId: "wtc-cheung-kong-centre",
    district: "Central_Western",
    nameEn: "Cheung Kong Centre",
    nameTc: "長江中心",
    lat: 22.28472,
    lng: 114.14452,
    addressEn: "Portal of Parknshop, Basement 2, Cheung Kong Centre, Central, Hong Kong",
    addressTc: "中環長江中心地庫2層",
  },
  {
    storeId: "wtc-discovery-bay",
    district: "Islands",
    nameEn: "Discovery Bay",
    nameTc: "愉景灣",
    lat: 22.2896,
    lng: 113.945,
    addressEn: "Shop 135, 1/F, Block C, D B Plaza, Discovery Bay, Lantau Island, Hong Kong",
    addressTc: "大嶼山愉景灣商場135號",
  },
  {
    storeId: "wtc-cheung-chau",
    district: "Islands",
    nameEn: "Cheung Chau",
    nameTc: "長洲",
    lat: 22.28744,
    lng: 113.94444,
    addressEn: "G/F-3/F & roof, 85 Praya Road, Cheung Chau, Hong Kong",
    addressTc: "長洲海傍路85號",
  },
  {
    storeId: "wtc-hing-wah",
    district: "Eastern",
    nameEn: "Hing Wah Shopping Centre",
    nameTc: "興華村",
    lat: 22.28372,
    lng: 114.22516,
    addressEn: "Shop No. 119-120, 1/F Hing Wah Plaza, Chai Wan, Hong Kong",
    addressTc: "柴灣興華廣場1樓119-120號舖",
  },
  {
    storeId: "wtc-aberdeen-centre",
    district: "Southern",
    nameEn: "Aberdeen Centre",
    nameTc: "香港仔中心",
    lat: 22.24588,
    lng: 114.1542,
    addressEn: "Flat/RM 6C, G/F, Hoi Chu Court, AC4 Aberdeen, HK",
    addressTc: "香港仔中心海珠閣地下6C",
  },
  {
    storeId: "wtc-lei-tung",
    district: "Southern",
    nameEn: "Lei Tung Estate",
    nameTc: "利東村",
    lat: 22.24828,
    lng: 114.15516,
    addressEn: "Shop No. L-202C, 1/F Lei Tung Comm Centre Phase 1, Lei Tung Est, HK",
    addressTc: "利東邨利東社區中心1樓L-202C號舖",
  },
  {
    storeId: "wtc-cityplaza",
    district: "Eastern",
    nameEn: "Cityplaza",
    nameTc: "太古城中心",
    lat: 22.28396,
    lng: 114.22468,
    addressEn: "Shop No. 124, First Floor, Cityplaza, 18 TaiKoo Shing Rd, Island East, HK",
    addressTc: "太古城太古城道18號太古城中心1樓124號舖",
  },
  {
    storeId: "wtc-shau-kei-wan",
    district: "Eastern",
    nameEn: "Shau Kei Wan",
    nameTc: "筲箕灣",
    lat: 22.28484,
    lng: 114.22468,
    addressEn: "Shop D & E, G/F, King Fai Building, 104 Shau Kei Wan Main Street, Hong Kong",
    addressTc: "筲箕灣筲箕灣道104號景輝大廈地下D及E舖",
  },
  {
    storeId: "wtc-siu-sai-wan",
    district: "Eastern",
    nameEn: "Siu Sai Wan Shopping Centre",
    nameTc: "小西灣商場",
    lat: 22.28452,
    lng: 114.22532,
    addressEn: "Shop No. 108, First Floor, Siu Sai Wan Shopping Centre, Hong Kong",
    addressTc: "小西灣商場1樓108號舖",
  },
  {
    storeId: "wtc-south-horizons",
    district: "Southern",
    nameEn: "South Horizons",
    nameTc: "海怡半島",
    lat: 22.24716,
    lng: 114.155,
    addressEn: "Shop 112, 112A & 113, 1/F, South Horizon Marina Square West Comm. Ctr., Ap Lei Chau, HK",
    addressTc: "鴨脷洲海怡半島海怡西商場1樓112, 112A及113號舖",
  },
  {
    storeId: "wtc-noble-square",
    district: "Southern",
    nameEn: "Noble Square",
    nameTc: "華貴坊",
    lat: 22.24724,
    lng: 114.1546,
    addressEn: "Shop Nos. 15-16, G/F Noble Square, Wah Kwai Estate, 3 Wah Kwai Road, Aberdeen, HK",
    addressTc: "香港仔華貴邨華貴坊地下15-16號舖",
  },
  {
    storeId: "wtc-the-southside",
    district: "Southern",
    nameEn: "The Southside",
    nameTc: "港島南岸",
    lat: 22.24732,
    lng: 114.15516,
    addressEn: "Shop Unit G13, Ground Floor, The SouthSide, Wong Chuk Hang, HK",
    addressTc: "黃竹坑港島南岸地下G13號舖",
  },
  {
    storeId: "wtc-electric-road-228",
    district: "Eastern",
    nameEn: "Electric Road 228",
    nameTc: "電氣道228號",
    lat: 22.28612,
    lng: 114.22564,
    addressEn: "Unit 1 on Ground Floor, 228 Electric Road, North Point, HK",
    addressTc: "北角電氣道228號地下1號",
  },
  {
    storeId: "wtc-kornhill-plaza",
    district: "Eastern",
    nameEn: "Kornhill Plaza",
    nameTc: "康怡廣場",
    lat: 22.28508,
    lng: 114.22476,
    addressEn: "Shop Nos. S26-S27, 2/F, Kornhill Plaza, 1 Kornhill Road, Quarry Bay, HK",
    addressTc: "鰂魚涌康山道1號康怡廣場2樓S26-S27號舖",
  },
  {
    storeId: "wtc-island-place",
    district: "Eastern",
    nameEn: "Island Place",
    nameTc: "港運城",
    lat: 22.28604,
    lng: 114.22484,
    addressEn: "Shop 111, 1/F, Island Place, 500 King's Road, North Point, Hong Kong",
    addressTc: "北角英皇道500號港運城商場1樓111號",
  },
  {
    storeId: "wtc-nathan-road-80",
    district: "Yau_Tsim_Mong",
    nameEn: "Nathan Road 80",
    nameTc: "彌敦道80號",
    lat: 22.30636,
    lng: 114.17172,
    addressEn: "Shop A, G/F, Majestic House, No. 80 Nathan Rd, Tsim Sha Tsui, KL",
    addressTc: "尖沙咀彌敦道80號金鑾大廈地下A號舖",
  },
  {
    storeId: "wtc-metro-harbour-plaza",
    district: "Sham_Shui_Po",
    nameEn: "Metro Harbour Plaza",
    nameTc: "港灣豪庭廣場",
    lat: 22.32952,
    lng: 114.16136,
    addressEn: "Shop Nos. G83-G85, G/F, Metro Harbour Plaza, Tai Kok Tsui, KL",
    addressTc: "大角咀港灣豪庭地下G83-G85號舖",
  },
  {
    storeId: "wtc-whampoa-garden",
    district: "Kowloon_City",
    nameEn: "Whampoa Garden",
    nameTc: "黃埔花園",
    lat: 22.32648,
    lng: 114.19124,
    addressEn: "Shop No G3A, G/F, Site 2, Whampoa Garden, Hunghom, KLN",
    addressTc: "紅磡黃埔花園第二期商場地下3A號舖",
  },
  {
    storeId: "wtc-harbour-city",
    district: "Yau_Tsim_Mong",
    nameEn: "Harbour City",
    nameTc: "海港城",
    lat: 22.30572,
    lng: 114.17084,
    addressEn: "Shop 3302 Level 3, Gateway Arcade, Harbour City, 7-23 Canton Road, Tsim Sha Tsui",
    addressTc: "尖沙咀廣東道7-23號海港城港威中心三樓3302號舖",
  },
  {
    storeId: "wtc-laguna-city",
    district: "Kwun_Tong",
    nameEn: "Laguna City",
    nameTc: "麗港城",
    lat: 22.31,
    lng: 114.22428,
    addressEn: "Shop 60-62, Level 1, Laguna City Plaza, Kowloon",
    addressTc: "觀塘麗港城商場第一層60-62號",
  },
  {
    storeId: "wtc-metropolis-mall",
    district: "Kowloon_City",
    nameEn: "Metropolis Mall",
    nameTc: "國際都會",
    lat: 22.32976,
    lng: 114.19084,
    addressEn: "Shop No. 719 & 720B, Level 7, The Metropolis Mall, 6 Metropolis Drive, Hunghom",
    addressTc: "紅磡都會道6號置富都會7層719, 720B號舖",
  },
  {
    storeId: "wtc-hilton-tower",
    district: "Yau_Tsim_Mong",
    nameEn: "Hilton Tower",
    nameTc: "希爾頓大廈",
    lat: 22.30324,
    lng: 114.17044,
    addressEn: "Front Portion of Shop C, G/F, Hilton Tower, 96 Granville Road, Tsimshatsui, KL",
    addressTc: "尖沙咀加連威老道96號希爾頓大廈地下C舖",
  },
  {
    storeId: "wtc-hunghom-bay",
    district: "Kowloon_City",
    nameEn: "Hunghom Bay",
    nameTc: "紅磡灣",
    lat: 22.328,
    lng: 114.1902,
    addressEn: "Shop 10, G/F, Hunghom Bay Centre, 92-112 Baker Street, Hunghom, Kowloon",
    addressTc: "紅磡必嘉街92-112號紅磡中心地下10號舖",
  },
  {
    storeId: "wtc-olympian-city",
    district: "Sham_Shui_Po",
    nameEn: "Olympian City",
    nameTc: "奧海城",
    lat: 22.33176,
    lng: 114.16272,
    addressEn: "Shop 108, 1/F, Olympian City 2, 18 Hoi Ting Road, Kowloon",
    addressTc: "海庭道18號奧海城二期一樓108號",
  },
  {
    storeId: "wtc-festival-walk",
    district: "Sham_Shui_Po",
    nameEn: "Festival Walk",
    nameTc: "又一城",
    lat: 22.32896,
    lng: 114.16176,
    addressEn: "Portion of Unit MTR-01, Level MTR, Festival Walk, 80 Tat Chee Avenue, Kowloon",
    addressTc: "九龍塘達之路80號又一城MTR01號",
  },
  {
    storeId: "wtc-china-hong-kong-city",
    district: "Yau_Tsim_Mong",
    nameEn: "China Hong Kong City",
    nameTc: "中港城",
    lat: 22.30444,
    lng: 114.17156,
    addressEn: "UG/F 43D, China Hong Kong City, 33 Canton Road, Tsim Sha Tsui",
    addressTc: "尖沙咀廣東道33號中港城高層地下43D號舖",
  },
  {
    storeId: "wtc-sai-yeung-choi-st",
    district: "Yau_Tsim_Mong",
    nameEn: "Sai Yeung Choi St. S",
    nameTc: "西洋菜南街",
    lat: 22.30452,
    lng: 114.17028,
    addressEn: "Shop G06 & G07, G/F, Sim City, 47-51 Shan Tung Street, Mongkok, KL",
    addressTc: "旺角山東街47-51號星際城市地下G06-G07號舖",
  },
  {
    storeId: "wtc-celestial-plaza",
    district: "Kowloon_City",
    nameEn: "Celestial Plaza",
    nameTc: "壹號名薈",
    lat: 22.32928,
    lng: 114.19132,
    addressEn: "Shop No. 16, 1/F, Celestial Place, No. 80 Sheung Shing Street, KL",
    addressTc: "常盛街80號半山壹號名薈1樓16號舖",
  },
  {
    storeId: "wtc-hunghom-comm-ctr",
    district: "Kowloon_City",
    nameEn: "Hunghom Comm Ctr G/F",
    nameTc: "紅磡商業中心",
    lat: 22.32792,
    lng: 114.19148,
    addressEn: "Shop No. 45-47, G/F, Hunghom Commercial Centre, 37-41 Ma Tau Wai Road, KL",
    addressTc: "紅磡馬頭圍道37-41號紅磡商業中心地下45-47號舖",
  },
  {
    storeId: "wtc-moko",
    district: "Yau_Tsim_Mong",
    nameEn: "MOKO Level 1",
    nameTc: "新世紀廣場",
    lat: 22.305,
    lng: 114.17124,
    addressEn: "Shop No. 153, Level 1, MOKO, 193 Prince Edward Road West, Mong Kok, KL",
    addressTc: "旺角太子道西193號新世紀廣場1樓153號舖",
  },
  {
    storeId: "wtc-jubilant-place",
    district: "Kowloon_City",
    nameEn: "Jubilant Place",
    nameTc: "欣榮花園",
    lat: 22.328,
    lng: 114.19132,
    addressEn: "Shops 28-30 & 46-49, G/F, Jubilant Place, 33 Ma Tau Kok Road, Tokwawan, KL",
    addressTc: "土瓜灣馬頭角道33號欣榮花園地下46-49號",
  },
  {
    storeId: "wtc-mongkok-655",
    district: "Yau_Tsim_Mong",
    nameEn: "Mongkok",
    nameTc: "旺角",
    lat: 22.305,
    lng: 114.17076,
    addressEn: "Shop C1 & C2, G/F and Whole of M/F Wu Sang House, 655 Nathan Road, Mongkok, KL",
    addressTc: "旺角彌敦道655號胡社生行地下C1及C2號舖",
  },
  {
    storeId: "wtc-tokwawan",
    district: "Kowloon_City",
    nameEn: "Tokwawan",
    nameTc: "土瓜灣",
    lat: 22.32872,
    lng: 114.19108,
    addressEn: "G/F, Shop 20-1, Portion of Shop 30B, Honor Building, 80-2 Tokwawan Road, Tokwawan, KLN",
    addressTc: "土瓜灣道80-2號定安大廈地下20-1及30B舖",
  },
  {
    storeId: "wtc-fuk-lo-tsun-road",
    district: "Kowloon_City",
    nameEn: "Fuk Lo Tsun Road",
    nameTc: "福佬村道",
    lat: 22.3292,
    lng: 114.19052,
    addressEn: "G/F, No. 13 Fuk Lo Tsun Road, Kowloon City, Kowloon",
    addressTc: "九龍城福佬村道13號地下",
  },
  {
    storeId: "wtc-dragon-centre-2",
    district: "Sham_Shui_Po",
    nameEn: "Dragon Centre 2",
    nameTc: "西九龍中心2",
    lat: 22.3308,
    lng: 114.16128,
    addressEn: "Unit 203, 2/F, Dragon Centre, 37 Yen Chow Street, Sham Shui Po, Kowloon",
    addressTc: "深水埗欽州街西九龍中心203號舖",
  },
  {
    storeId: "wtc-union-park-centre",
    district: "Yau_Tsim_Mong",
    nameEn: "Union Park Centre",
    nameTc: "柏宜中心",
    lat: 22.30436,
    lng: 114.17124,
    addressEn: "Shop Nos. 4-6, G/F, Union Park Centre, 771-775 Nathan Road, Mongkok, Kowloon",
    addressTc: "旺角彌敦道771-775號柏宜中心地下4-6號舖",
  },
  {
    storeId: "wtc-oi-man",
    district: "Kowloon_City",
    nameEn: "Oi Man Shopping Centre",
    nameTc: "愛民商場",
    lat: 22.32952,
    lng: 114.19164,
    addressEn: "Shop No. G16, G/F, Oi Man Plaza, 60 Chung Hau Street, KL",
    addressTc: "忠孝街60號愛民商場地下G16號舖",
  },
  {
    storeId: "wtc-megabox",
    district: "Kwun_Tong",
    nameEn: "Megabox Level 2",
    nameTc: "企業廣場",
    lat: 22.31288,
    lng: 114.22524,
    addressEn: "Units 32 & 33, Level 2, Megabox, 38 Wang Chiu Road, Kowloon Bay, KL",
    addressTc: "九龍灣宏照道38號企業廣場五期L2層32及33號舖",
  },
  {
    storeId: "wtc-ping-shek",
    district: "Kwun_Tong",
    nameEn: "Ping Shek Estate",
    nameTc: "坪石邨",
    lat: 22.31256,
    lng: 114.22564,
    addressEn: "Shop No.201A, Tsuen Shek House, Ping Shek Estate, Kowloon",
    addressTc: "坪石邨鑽石樓201A號舖",
  },
  {
    storeId: "wtc-temple-mall-north",
    district: "Wong_Tai_Sin",
    nameEn: "Temple Mall North",
    nameTc: "黃大仙中心北館",
    lat: 22.34136,
    lng: 114.195,
    addressEn: "Shop No. N221 Level 2, Temple Mall North, 136 Lung Cheung Road, KL",
    addressTc: "龍翔道黃大仙中心北館N221號舖",
  },
  {
    storeId: "wtc-choi-wan",
    district: "Wong_Tai_Sin",
    nameEn: "Choi Wan Shopping Centre",
    nameTc: "彩雲商場",
    lat: 22.34328,
    lng: 114.19444,
    addressEn: "Shop No. B203, 2/F, Choi Wan Shopping Centre Phase 3, Ngau Chi Wan, Kowloon",
    addressTc: "牛池灣彩雲商場二樓B203號舖",
  },
  {
    storeId: "wtc-amoy-plaza",
    district: "Kwun_Tong",
    nameEn: "Amoy Plaza",
    nameTc: "淘大商場",
    lat: 22.31368,
    lng: 114.22436,
    addressEn: "Shop Nos. G73-76, 78, G/F Amoy Plaza, 77 Ngau Tau Kok Rd, Kowloon",
    addressTc: "牛頭角道77號淘大商場地下G73-76及78號舖",
  },
  {
    storeId: "wtc-kai-tak-sports-park",
    district: "Kowloon_City",
    nameEn: "Kai Tak Sports Park",
    nameTc: "啟德體育園",
    lat: 22.32904,
    lng: 114.19076,
    addressEn: "Shop No. M1-217, Level 2, Kai Tak Mall 1, Kai Tak Sports Park, Kai Tak, KL",
    addressTc: "啟德體育園啟德零售館1二樓M1-217號舖",
  },
  {
    storeId: "wtc-telford-plaza",
    district: "Kwun_Tong",
    nameEn: "Telford Plaza I",
    nameTc: "德福廣場一期",
    lat: 22.31184,
    lng: 114.22548,
    addressEn: "Shop Unit G52, Telford Plaza I, Kowloon Bay, Kowloon",
    addressTc: "九龍灣德福廣場一期G52號舖",
  },
  {
    storeId: "wtc-mikiki",
    district: "Wong_Tai_Sin",
    nameEn: "Mikiki",
    nameTc: "Mikiki",
    lat: 22.34344,
    lng: 114.1954,
    addressEn: "Shop No. G02B-G03 on G/F, Mikiki, 638 Prince Edward Road East, San Po Kong, Kowloon",
    addressTc: "新蒲崗太子道東638號Mikiki地下G02B-G03號舖",
  },
  {
    storeId: "wtc-ching-long",
    district: "Kowloon_City",
    nameEn: "Ching Long Shopping Centre",
    nameTc: "晴朗商場",
    lat: 22.32872,
    lng: 114.191,
    addressEn: "Shop B021, G/F, Ching Long Shopping Centre, Kowloon City",
    addressTc: "九龍城晴朗商場地下B021號舖",
  },
  {
    storeId: "wtc-lok-fu-place",
    district: "Wong_Tai_Sin",
    nameEn: "Lok Fu Place",
    nameTc: "樂富廣場",
    lat: 22.34336,
    lng: 114.19564,
    addressEn: "Shop Nos. 2116 & 2117, 2/F, Lok Fu Place, 198 Junction Road, Kowloon",
    addressTc: "橫頭磡聯合道198號樂富廣場二樓2116及2117號舖",
  },
  {
    storeId: "wtc-choi-tak",
    district: "Kwun_Tong",
    nameEn: "Choi Tak Shopping Centre",
    nameTc: "彩德商場",
    lat: 22.31376,
    lng: 114.2254,
    addressEn: "Shop 513, 5/F, Choi Tak Shopping Centre, Ngau Tau Kok, Kowloon",
    addressTc: "牛頭角彩德商場5樓513號舖",
  },
  {
    storeId: "wtc-tsz-wan-shan",
    district: "Wong_Tai_Sin",
    nameEn: "Tsz Wan Shan",
    nameTc: "慈雲山",
    lat: 22.3408,
    lng: 114.1946,
    addressEn: "Shop 414-416, Tsz Wan Shan Shopping Centre, 23 Yuk Wah Street, Tze Wan Shan, Kln",
    addressTc: "毓華街23號慈雲山廣場414-416號舖",
  },
  {
    storeId: "wtc-diamond-hill",
    district: "Wong_Tai_Sin",
    nameEn: "Diamond Hill",
    nameTc: "鑽石山",
    lat: 22.34208,
    lng: 114.19428,
    addressEn: "Shop No. 228, L2, Plaza Hollywood, Diamond Hill, Kowloon",
    addressTc: "鑽石山荷里活廣場2樓228號舖",
  },
  {
    storeId: "wtc-chuk-yuen",
    district: "Wong_Tai_Sin",
    nameEn: "Chuk Yuen",
    nameTc: "竹園",
    lat: 22.34072,
    lng: 114.19444,
    addressEn: "Shop No. S231, Chuk Yuen Shopping Centre, Wong Tai Sin, Kowloon",
    addressTc: "黃大仙竹園商場S231號舖",
  },
  {
    storeId: "wtc-cheung-sha-wan-plaza",
    district: "Sham_Shui_Po",
    nameEn: "Cheung Sha Wan Plaza G/F",
    nameTc: "長沙灣廣場",
    lat: 22.33128,
    lng: 114.1624,
    addressEn: "Unit G02, G/F, Cheung Sha Wan Plaza, 833 Cheung Sha Wan Road, KL",
    addressTc: "長沙灣道833號長沙灣廣場地下G02號舖",
  },
  {
    storeId: "wtc-mei-foo",
    district: "Sham_Shui_Po",
    nameEn: "Mei Foo",
    nameTc: "美孚",
    lat: 22.33176,
    lng: 114.16144,
    addressEn: "G/F, N58 & N65-N68, Mount Sterling Mall, Stage 7, Mei Foo, Kowloon",
    addressTc: "美孚新村萬事達廣場七期地下N58, N65-68舖",
  },
  {
    storeId: "wtc-the-pacifica",
    district: "Sham_Shui_Po",
    nameEn: "The Pacifica Mall",
    nameTc: "宇晴軒",
    lat: 22.32976,
    lng: 114.16264,
    addressEn: "Shop No. 41, 42 & 47, 2/F, The Pacifica Mall, 9 Sham Shing Road, Lai Chi Kok, Kowloon",
    addressTc: "荔枝角深盛路9號宇晴軒商場2樓41, 42及47號舖",
  },
  {
    storeId: "wtc-un-chau-street",
    district: "Sham_Shui_Po",
    nameEn: "Un Chau Street",
    nameTc: "元洲街",
    lat: 22.32904,
    lng: 114.16192,
    addressEn: "Shop G03, Un Chau Shopping Centre, 303 Un Chau Street, Cheung Sha Wan, Kowloon",
    addressTc: "長沙灣元洲街303號元洲商場地下G03號舖",
  },
  {
    storeId: "wtc-domain",
    district: "Kwun_Tong",
    nameEn: "Domain",
    nameTc: "大本型",
    lat: 22.31168,
    lng: 114.22484,
    addressEn: "Shop No. 220 on second floor, Domain, Yau Tong, KL",
    addressTc: "油塘大本型第二層220號舖",
  },
  {
    storeId: "wtc-kai-tin",
    district: "Kwun_Tong",
    nameEn: "Kai Tin",
    nameTc: "啟田",
    lat: 22.312,
    lng: 114.2246,
    addressEn: "Shop 101A, 1/F, Kai Tin Shopping Centre, Lam Tin, Kowloon",
    addressTc: "藍田啟田商場一樓101A號舖",
  },
  {
    storeId: "wtc-tak-tin",
    district: "Kwun_Tong",
    nameEn: "Tak Tin Shopping Centre",
    nameTc: "德田商場",
    lat: 22.31224,
    lng: 114.22556,
    addressEn: "Shop No. G2A, G/F, Tak Tin Shopping Centre, 223 Pik Wan Road, Lam Tin, Kowloon",
    addressTc: "藍田碧雲道223號德田商場地下G2A號舖",
  },
  {
    storeId: "wtc-sau-mau-ping",
    district: "Kwun_Tong",
    nameEn: "Sau Mau Ping",
    nameTc: "秀茂坪",
    lat: 22.31224,
    lng: 114.22572,
    addressEn: "Shop no. 210, 2/F, Sau Mau Ping Shopping Ctr, 101 Sau Ming Rd, Kwun Tong",
    addressTc: "觀塘秀明道101號秀茂坪商場2樓210號舖",
  },
  {
    storeId: "wtc-crocodile-centre",
    district: "Kwun_Tong",
    nameEn: "Crocodile Centre",
    nameTc: "鱷魚恤中心",
    lat: 22.31184,
    lng: 114.2242,
    addressEn: "Shop A, G/F, Crocodile Centre, 79 Hoi Yuen Road, Kwun Tong, Kowloon",
    addressTc: "觀塘開源道79號鱷魚恤中心地下A舖",
  },
  {
    storeId: "wtc-cke-mall",
    district: "Yau_Tsim_Mong",
    nameEn: "CKE Mall Level 2",
    nameTc: "重慶站購物商場",
    lat: 22.30596,
    lng: 114.17092,
    addressEn: "Shop 2-383, 2-385-7, 2-396-397, 2/F Chungking Mansion, 36-44 Nathan Road, KL",
    addressTc: "尖沙咀彌敦道36-44號CKE重慶站購物商場二樓",
  },
  {
    storeId: "wtc-pak-tin",
    district: "Sham_Shui_Po",
    nameEn: "Pak Tin Commercial Centre",
    nameTc: "白田商場",
    lat: 22.32968,
    lng: 114.16128,
    addressEn: "Shop No. LG301, LG3/F, Pak Tin Commercial Centre, Pak Tin Estate, Sham Shui Po",
    addressTc: "白田邨白田商場LG3樓LG301號舖",
  },
  {
    storeId: "wtc-sham-shui-po-17",
    district: "Sham_Shui_Po",
    nameEn: "Sham Shui Po",
    nameTc: "深水埗",
    lat: 22.32872,
    lng: 114.16216,
    addressEn: "G/F and Cockloft, No. 17 Un Chau Street, Sham Shui Po",
    addressTc: "深水埗元州街17號地下及閣樓",
  },
  {
    storeId: "wtc-maritime-square",
    district: "Kwai_Tsing",
    nameEn: "Maritime Square",
    nameTc: "青衣城",
    lat: 22.35664,
    lng: 114.12476,
    addressEn: "Shop Unit 311-312, Level 3, Maritime Square, 33 Tsing King Road, Tsing Yi, N.T.",
    addressTc: "青衣青敬路33號青衣城3樓311-312號舖",
  },
  {
    storeId: "wtc-cheung-hong",
    district: "Kwai_Tsing",
    nameEn: "Cheung Hong",
    nameTc: "長康",
    lat: 22.35608,
    lng: 114.12428,
    addressEn: "Shops 13 & 14, G/F, Hong Kwai House, Cheung Hong Estate, Tsing Yi, NT",
    addressTc: "青衣長康邨康貴樓地下13,14號舖",
  },
  {
    storeId: "wtc-fu-tung-plaza",
    district: "Islands",
    nameEn: "Fu Tung Plaza",
    nameTc: "富東廣場",
    lat: 22.28656,
    lng: 113.94564,
    addressEn: "Shop Nos. 113B & 114, 1/F Fu Tung Plaza, 6 Fu Tung Street, Tung Chung, NT",
    addressTc: "東涌富東街6號富東廣場一樓113B及114號",
  },
  {
    storeId: "wtc-cheung-fat",
    district: "Kwai_Tsing",
    nameEn: "Cheung Fat Estate",
    nameTc: "長發村",
    lat: 22.35704,
    lng: 114.1254,
    addressEn: "Shop No. 209, 2/F, Cheung Fat Shopping Centre, Tsing Yi, New Territories",
    addressTc: "青衣長發村長發商場2樓209號舖",
  },
  {
    storeId: "wtc-tsuen-kam-centre",
    district: "Tsuen_Wan",
    nameEn: "Tsuen Kam Centre",
    nameTc: "荃灣錦中心",
    lat: 22.36908,
    lng: 114.11444,
    addressEn: "Shop Nos. 104-109, 2/F, Tsuen Kam Centre, 338 Castle Peak Road, Tsuen Wan, NT",
    addressTc: "荃灣青山公路338號荃灣錦中心二樓104-109號舖",
  },
  {
    storeId: "wtc-belvedere-square",
    district: "Tsuen_Wan",
    nameEn: "Belvedere Square",
    nameTc: "麗城薈",
    lat: 22.37292,
    lng: 114.11484,
    addressEn: "Shop Nos. 52-53, G/F Belvedere Square, 625 Castle Peak Rd, Tsuen Wan, N.T.",
    addressTc: "荃灣青山路625號麗城薈地下52-53號舖",
  },
  {
    storeId: "wtc-op-mall",
    district: "Tsuen_Wan",
    nameEn: "OP Mall",
    nameTc: "海之戀",
    lat: 22.37156,
    lng: 114.11508,
    addressEn: "Shop No. 3027, 3/F OP Mall, 100 Tai Ho Road, Tsuen Wan, NT",
    addressTc: "荃灣海之戀商場3樓3027號舖",
  },
  {
    storeId: "wtc-d-park",
    district: "Tsuen_Wan",
    nameEn: "D.Park Level 2",
    nameTc: "愉景新城",
    lat: 22.37052,
    lng: 114.11468,
    addressEn: "Shop Nos. 2004-2005, Level 2, D. Park Discovery Park, 398 Castle Peak Rd, Tsuen Wan, NT",
    addressTc: "荃灣青山道398號愉景新城購物商場二層2004-2005號舖",
  },
  {
    storeId: "wtc-on-yam",
    district: "Kwai_Tsing",
    nameEn: "On Yam",
    nameTc: "安蔭商場",
    lat: 22.35936,
    lng: 114.12508,
    addressEn: "Shops 103 & 104, 1/F, On Yam Shopping Centre, 7 On Chuk St, Kwai Chung, NT",
    addressTc: "葵涌安足街7號安蔭商場1樓103及104號舖",
  },
  {
    storeId: "wtc-shek-yam",
    district: "Kwai_Tsing",
    nameEn: "Shek Yam",
    nameTc: "石蔭",
    lat: 22.35688,
    lng: 114.12428,
    addressEn: "Shop No. 101, LG 1/F, Shek Yam Shopping Centre, Shek Yam Estate, Kwai Chung, NT",
    addressTc: "葵涌石蔭村石蔭商場地下101號舖",
  },
  {
    storeId: "wtc-shek-lei",
    district: "Kwai_Tsing",
    nameEn: "Shek Lei Shopping Centre",
    nameTc: "石籬商場",
    lat: 22.35968,
    lng: 114.12484,
    addressEn: "Shop No. B001B & B001C, G/F, Shek Lei Shopping Centre Phase 2, Kwai Chung, NT",
    addressTc: "葵涌石籬村石籬商場2期地下B001B及B001C號舖",
  },
  {
    storeId: "wtc-lei-muk-shue",
    district: "Tsuen_Wan",
    nameEn: "Lei Muk Shue",
    nameTc: "梨木樹",
    lat: 22.37092,
    lng: 114.11548,
    addressEn: "Shop 117, Lei Muk Shue Shopping Centre, Lei Muk Shue Estate, Tsuen Wan, NT",
    addressTc: "荃灣梨木樹村梨木樹商場117舖",
  },
  {
    storeId: "wtc-luk-yeung-galleria",
    district: "Tsuen_Wan",
    nameEn: "Luk Yeung Galleria",
    nameTc: "綠楊坊",
    lat: 22.37196,
    lng: 114.11508,
    addressEn: "Shop Unit F20A, Luk Yeung Galleria, Tsuen Wan, New Territories",
    addressTc: "荃灣綠楊新村商場F20A號舖",
  },
  {
    storeId: "wtc-lido-avenue",
    district: "Tsuen_Wan",
    nameEn: "LIDO AVENUE",
    nameTc: "麗都花園",
    lat: 22.37188,
    lng: 114.115,
    addressEn: "Shop Nos. 7&8, G/F Lido Avenue, 41-63 Castle Peak Road, Sham Tseng, N.T.",
    addressTc: "深井青山公路41-63號麗都花園地下7及8號舖",
  },
  {
    storeId: "wtc-citywalk-2",
    district: "Tsuen_Wan",
    nameEn: "Citywalk Phase 2",
    nameTc: "荃新天地2期",
    lat: 22.37052,
    lng: 114.11508,
    addressEn: "Shop G66-68, G/F, Citywalk 2, 18 Yeung Uk Road, Tsuen Wan, NT",
    addressTc: "荃灣楊屋道18號荃新天地2期G66-G68號舖",
  },
  {
    storeId: "wtc-metroplaza",
    district: "Kwai_Tsing",
    nameEn: "Metroplaza",
    nameTc: "葵芳新都會廣場",
    lat: 22.35752,
    lng: 114.12468,
    addressEn: "Shop 341, Level 3, Metroplaza, Kwai Fong, N.T.",
    addressTc: "葵芳新都會廣場三樓341號舖",
  },
  {
    storeId: "wtc-park-central",
    district: "Sai_Kung",
    nameEn: "Park Central",
    nameTc: "將軍澳中心",
    lat: 22.38144,
    lng: 114.27224,
    addressEn: "Shop Nos. 125 & 128A, Level 1, Park Central, 9 Tong Tak Street, Tseung Kwan O, NT",
    addressTc: "將軍澳唐德街9號將軍澳中心1樓125及128A號舖",
  },
  {
    storeId: "wtc-metro-discovery",
    district: "Sai_Kung",
    nameEn: "Metro Discovery",
    nameTc: "新都城中心三期商場",
    lat: 22.38296,
    lng: 114.27128,
    addressEn: "Shop No. 246-247, Level 2, MCP Discovery, Tseung Kwan O",
    addressTc: "將軍澳新都城三期二樓246-247號舖",
  },
  {
    storeId: "wtc-sheung-tak",
    district: "Sai_Kung",
    nameEn: "Sheung Tak Shopping Centre",
    nameTc: "尚德商場",
    lat: 22.38368,
    lng: 114.27272,
    addressEn: "Shop No. 202, 2/F, Sheung Tak Shopping Centre, Tseung Kwan O, N.T.",
    addressTc: "將軍澳尚德商場二樓202號鋪",
  },
  {
    storeId: "wtc-east-point-city",
    district: "Sai_Kung",
    nameEn: "East Point City",
    nameTc: "東港城",
    lat: 22.38352,
    lng: 114.27208,
    addressEn: "Shop No.226, 2/F, East Point City, 8 Chung Wa Road, Tseung Kwan O, NT",
    addressTc: "將軍澳重華路8號東港城2樓226號鋪",
  },
  {
    storeId: "wtc-metro-town",
    district: "Sai_Kung",
    nameEn: "Metro Town",
    nameTc: "都會駅",
    lat: 22.38056,
    lng: 114.27152,
    addressEn: "Shop Nos.L2-018 & L2-019, Level 2, Metro Town, 8 King Ling Road, Tseung Kwan O, NT",
    addressTc: "將軍澳景嶺路8號都會駅第二層18-19號",
  },
  {
    storeId: "wtc-tko-plaza",
    district: "Sai_Kung",
    nameEn: "Tseung Kwan O Plaza",
    nameTc: "將軍澳廣場",
    lat: 22.3804,
    lng: 114.27152,
    addressEn: "Shop Nos.1-073-075 & 1-085-086, Level 1, Tseung Kwan O Plaza, 1 Tong Tak St, TKO, NT",
    addressTc: "將軍澳唐德街一號將軍澳廣場一樓",
  },
  {
    storeId: "wtc-mcp-central",
    district: "Sai_Kung",
    nameEn: "MCP Central",
    nameTc: "新都城中心二期",
    lat: 22.38128,
    lng: 114.27272,
    addressEn: "Shops UG026-27, UG/F, MCP Central, Tseung Kwan O, NT",
    addressTc: "將軍澳新都城中心二期UG026-27號鋪",
  },
  {
    storeId: "wtc-sai-kung-garden",
    district: "Sai_Kung",
    nameEn: "Sai Kung Garden",
    nameTc: "西貢花園",
    lat: 22.38008,
    lng: 114.27152,
    addressEn: "Designated Portion on G/F of Sai Kung Garden, 16 Chan Man Street, Sai Kung, N.T.",
    addressTc: "西貢親民街16號西貢花園地下部份",
  },
  {
    storeId: "wtc-tai-wo-plaza",
    district: "Tai_Po",
    nameEn: "Tai Wo Plaza",
    nameTc: "太和廣場",
    lat: 22.44992,
    lng: 114.16944,
    addressEn: "Shop No. 218, Level 2, Tai Wo Plaza, 12 Tai Po Tai Wo Road, Tai Po, NT",
    addressTc: "大埔太和路12號太和廣場2樓218號",
  },
  {
    storeId: "wtc-tin-yiu-plaza",
    district: "Yuen_Long",
    nameEn: "Tin Yiu Plaza",
    nameTc: "天耀廣場",
    lat: 22.4454,
    lng: 114.02264,
    addressEn: "Shop Nos. L046A & L046B, G/F, Tin Yiu Plaza, Tin Shui Wai, NT",
    addressTc: "天水圍天耀廣場地下L046A及L046B號舖",
  },
  {
    storeId: "wtc-tin-shui-shopping",
    district: "Yuen_Long",
    nameEn: "Tin Shui Shopping Centre",
    nameTc: "天瑞商場",
    lat: 22.44372,
    lng: 114.02152,
    addressEn: "Shop No. L112, 1/F Tin Shui Shopping Centre, Tin Shui Wai, NT",
    addressTc: "天水圍天瑞商場1樓L112號舖",
  },
  {
    storeId: "wtc-yoho-mix",
    district: "Yuen_Long",
    nameEn: "YOHO Mix",
    nameTc: "元點",
    lat: 22.44612,
    lng: 114.02248,
    addressEn: "Shop B169 & B187, Level 1, Yoho Mix, Yuen Long, NT",
    addressTc: "元朗元點1樓B169及B187號舖",
  },
  {
    storeId: "wtc-park-circle",
    district: "Yuen_Long",
    nameEn: "Park Circle G/F",
    nameTc: "峻巒廣場",
    lat: 22.44612,
    lng: 114.02208,
    addressEn: "Shop Nos. 101-102, G/F, Park Circle, 18 Castle Peak Road Tam Mi, Kam Tin, NT",
    addressTc: "錦田青山公路18號峻巒廣場地下101-102號舖",
  },
  {
    storeId: "wtc-long-ping",
    district: "Yuen_Long",
    nameEn: "Long Ping",
    nameTc: "朗屏商場",
    lat: 22.44524,
    lng: 114.02128,
    addressEn: "Shop No. L112, 1/F, Long Ping Shopping Centre, Long Ping Estate, Yuen Long, NT",
    addressTc: "元朗朗屏邨朗屏商場1樓L112號舖",
  },
  {
    storeId: "wtc-fu-shin",
    district: "Tai_Po",
    nameEn: "Fu Shin Shopping Centre",
    nameTc: "富善商場",
    lat: 22.45192,
    lng: 114.17056,
    addressEn: "Shop No. G007 and G012, G/F, Fu Shin Estate, Tai Po, NT",
    addressTc: "大埔富善邨富善商場地下G007及G012號舖",
  },
  {
    storeId: "wtc-tai-po-mega-mall",
    district: "Tai_Po",
    nameEn: "Tai Po Mega Mall 2",
    nameTc: "大埔超級城",
    lat: 22.44944,
    lng: 114.17056,
    addressEn: "Shop No. 113, Level 1, Zone B, Tai Po Mega Mall, 8-10 On Pong Road, Tai Po, NT",
    addressTc: "大埔超級城1樓113號舖",
  },
  {
    storeId: "wtc-woo",
    district: "Yuen_Long",
    nameEn: "+WOO",
    nameTc: "嘉湖",
    lat: 22.4442,
    lng: 114.0212,
    addressEn: "Shop Nos. G73A, G74 & G75, G/F, +WOO Phase 1, 12-18 Tin Yan Road, Tin Shui Wai, N.T.",
    addressTc: "天水圍天恩路12-18號嘉湖1期地下G73A, G74及G75號舖",
  },
  {
    storeId: "wtc-t-town",
    district: "Yuen_Long",
    nameEn: "T-TOWN",
    nameTc: "T-TOWN",
    lat: 22.44436,
    lng: 114.02272,
    addressEn: "Shop N133-N134, 1/F, T-TOWN North, Tin Chung Court, Tin Shui Wai",
    addressTc: "天水圍天頌苑T-TOWN北翼1樓N133-N134號舖",
  },
  {
    storeId: "wtc-locwood-court",
    district: "Yuen_Long",
    nameEn: "Locwood Court",
    nameTc: "新北江商場",
    lat: 22.44396,
    lng: 114.02184,
    addressEn: "Shop Nos. 3 & 4, 1/F, Locwood Court, Kingswood Villas, 1 Tin Wu Road, Tin Shui Wai, NT",
    addressTc: "天水圍天湖路1號新北江商場1樓3及4號舖",
  },
  {
    storeId: "wtc-tin-chak",
    district: "Yuen_Long",
    nameEn: "Tin Chak Shopping Centre",
    nameTc: "天澤商場",
    lat: 22.44476,
    lng: 114.02176,
    addressEn: "Shop No. 212C, 2/F, Tin Chak Shopping Centre, Tin Chak Estate, Tin Shui Wai, NT",
    addressTc: "天水圍天澤商場2樓212C舖",
  },
  {
    storeId: "wtc-po-heung-street",
    district: "Tai_Po",
    nameEn: "Po Heung Street",
    nameTc: "寶鄉街",
    lat: 22.4484,
    lng: 114.17072,
    addressEn: "Shop B, G/F, Tak Shun Building, 82 Po Heung Street, Tai Po, NT",
    addressTc: "大埔寶鄉街82號德信大樓地下B舖",
  },
  {
    storeId: "wtc-uptown-plaza",
    district: "Tai_Po",
    nameEn: "Uptown Plaza",
    nameTc: "新達廣場",
    lat: 22.45184,
    lng: 114.16928,
    addressEn: "Shop 079-082, Level 1, Uptown Plaza, Tai Po, New Territories",
    addressTc: "大埔新達廣場一樓079-082號舖",
  },
  {
    storeId: "wtc-k-point",
    district: "Tuen_Mun",
    nameEn: "K-Point Level 3",
    nameTc: "錦薈坊",
    lat: 22.39068,
    lng: 113.97652,
    addressEn: "Shop Nos. 336, 337 & 345-352, Level 3, K-Point, 1 Tuen Lung Street, Tuen Mun, NT",
    addressTc: "屯門屯龍街1號K-POINT 3樓336, 337及345-352號舖",
  },
  {
    storeId: "wtc-hands",
    district: "Tuen_Mun",
    nameEn: "HANDS",
    nameTc: "愛定商場",
    lat: 22.391,
    lng: 113.97644,
    addressEn: "Shop No. A210-212, H.A.N.D.S., On Ting Estate, Tuen Mun, NT",
    addressTc: "屯門安定邨H.A.N.D.S商場A210-212號舖",
  },
  {
    storeId: "wtc-kin-sang",
    district: "Tuen_Mun",
    nameEn: "Kin Sang",
    nameTc: "建生商場",
    lat: 22.39292,
    lng: 113.97644,
    addressEn: "Shop No. 120 & 121, G/F Kin Sang Shopping Centre, Tuen Mun, NT",
    addressTc: "屯門建生商場地下120及121號舖",
  },
  {
    storeId: "wtc-hk-gold-coast",
    district: "Tsuen_Wan",
    nameEn: "HK Gold Coast",
    nameTc: "黃金海岸",
    lat: 22.37276,
    lng: 114.11468,
    addressEn: "Shop No 9-10, G/F, Marina Magic Shopping Mall, HK Gold Coast, 1 Castle Peak Road, Tsuen Wan, NT",
    addressTc: "荃灣青山道1號黃金海岸商場地下9-10號舖",
  },
  {
    storeId: "wtc-chelsea-heights",
    district: "Tuen_Mun",
    nameEn: "Chelsea Heights",
    nameTc: "卓爾居",
    lat: 22.39276,
    lng: 113.97724,
    addressEn: "Shop 101, 1/F, Chelsea Heights, Tuen Mun, New Territories",
    addressTc: "屯門卓爾居一樓101號舖",
  },
  {
    storeId: "wtc-yuen-long-142",
    district: "Yuen_Long",
    nameEn: "Yuen Long",
    nameTc: "元朗",
    lat: 22.44612,
    lng: 114.02248,
    addressEn: "G/F, 1/F & 2/F, 142 Castle Peak Road, Yuen Long, New Territories",
    addressTc: "元朗大馬路142號地下至2樓",
  },
  {
    storeId: "wtc-new-yuen-long",
    district: "Yuen_Long",
    nameEn: "New Yuen Long",
    nameTc: "新元朗",
    lat: 22.44612,
    lng: 114.02176,
    addressEn: "Shop 2 & 3, 8-10, G/F, Hing Fat House, 9-13 Kau Yuk Road, Yuen Long, NT",
    addressTc: "元朗教育路9-13號興發大樓地下2-3及8-10舖",
  },
  {
    storeId: "wtc-sun-tuen-mun",
    district: "Tuen_Mun",
    nameEn: "Sun Tuen Mun Centre",
    nameTc: "新屯門中心",
    lat: 22.39268,
    lng: 113.97652,
    addressEn: "Shop 125, Level 3, Sun Tuen Mun Shopping Centre, 55-65 Lung Mun Road, Tuen Mun, NT",
    addressTc: "屯門龍門路55-65號新屯門中心3樓125號舖",
  },
  {
    storeId: "wtc-tuen-mun-town-plaza",
    district: "Tuen_Mun",
    nameEn: "Tuen Mun",
    nameTc: "屯門市廣場",
    lat: 22.39148,
    lng: 113.97652,
    addressEn: "Shop 2100B-C & 2115-2122, 2/F, Tuen Mun Town Plaza Phase 1, 1 Tuen Shing Street, Tuen Mun, NT",
    addressTc: "屯門屯盛街1號屯門市廣場1期2樓2100B-C及2115-2122號",
  },
  {
    storeId: "wtc-butterfly-estate",
    district: "Tuen_Mun",
    nameEn: "Butterfly Estate",
    nameTc: "蝴蝶村",
    lat: 22.39268,
    lng: 113.97716,
    addressEn: "Shop Nos. R260, R261 and R262, Level 2, Butterfly Shopping Centre, Tuen Mun, N.T.",
    addressTc: "屯門蝴蝶村蝴蝶廣場R260, R261及R262號舖",
  },
  {
    storeId: "wtc-tseng-choi-street",
    district: "Tuen_Mun",
    nameEn: "Tseng Choi Street",
    nameTc: "井財街",
    lat: 22.39108,
    lng: 113.97628,
    addressEn: "Shop Nos. 11 & 12, G/F, Kam Men Mansion, 15 Tseng Choi Street, Tuen Mun, NT",
    addressTc: "屯門井財街15號金銘大廈地下11及12號舖",
  },
  {
    storeId: "wtc-v-city",
    district: "Tuen_Mun",
    nameEn: "V City",
    nameTc: "V City",
    lat: 22.39084,
    lng: 113.97628,
    addressEn: "Shop M-32, MTR Level, V City, 83 Tuen Mun Heung Sze Wui Road, Tuen Mun, NT",
    addressTc: "屯門鄉事會路83號V City地鐵樓層M-32號舖",
  },
  {
    storeId: "wtc-sau-fu-street",
    district: "Yuen_Long",
    nameEn: "Sau Fu Street",
    nameTc: "壽富街",
    lat: 22.44596,
    lng: 114.02176,
    addressEn: "G/F, 17 Sau Fu Street, Yuen Long, New Territories",
    addressTc: "元朗壽富街17號地下",
  },
  {
    storeId: "wtc-double-cove-place",
    district: "Sha_Tin",
    nameEn: "Double Cove Place",
    nameTc: "迎海薈",
    lat: 22.37916,
    lng: 114.19524,
    addressEn: "Shop No.7, 2/F Double Cove Place, 8 Wu Kai Sha Road, Ma On Shan, NT",
    addressTc: "馬鞍山烏溪沙路8號迎海薈2樓7號舖",
  },
  {
    storeId: "wtc-kings-wing-plaza",
    district: "Sha_Tin",
    nameEn: "Kings Wing Plaza",
    nameTc: "京瑞廣場",
    lat: 22.38044,
    lng: 114.19564,
    addressEn: "Shop G10, G/F, Kings Wing Plaza 1, 3 On Kwan Street, Shatin, NT",
    addressTc: "沙田安群街3號京瑞廣場1期地下G10號舖",
  },
  {
    storeId: "wtc-flora-plaza",
    district: "North",
    nameEn: "Flora Plaza 2",
    nameTc: "花都廣場",
    lat: 22.494,
    lng: 114.128,
    addressEn: "Shop Nos. A42 & A46, G/F, Flora Plaza, Fanling, NT",
    addressTc: "粉嶺花都廣場地下A42及A46號舖",
  },
  {
    storeId: "wtc-shatin-galleria",
    district: "Sha_Tin",
    nameEn: "Shatin Galleria",
    nameTc: "沙田商業中心",
    lat: 22.381,
    lng: 114.19428,
    addressEn: "Shop Nos. 7-9, 1/F Shatin Galleria, 18-24 Shan Mei Street, Shatin, N.T.",
    addressTc: "沙田火炭山尾街18-24號沙田商業中心1樓7-9號舖",
  },
  {
    storeId: "wtc-lung-hang",
    district: "Sha_Tin",
    nameEn: "Lung Hang Shopping Centre",
    nameTc: "隆亨商場",
    lat: 22.37948,
    lng: 114.19476,
    addressEn: "Shop No. 117, Level 2, Lung Hang Shopping Centre, Lung Hang Estate, Shatin, N.T.",
    addressTc: "沙田隆亨商場二樓117舖",
  },
  {
    storeId: "wtc-fanling-town-centre",
    district: "North",
    nameEn: "Fanling Town Centre",
    nameTc: "粉嶺名都廣場",
    lat: 22.49552,
    lng: 114.12816,
    addressEn: "Shop No. 28B, Level 2, Fanling Town Centre, Fanling, New Territories",
    addressTc: "粉嶺名都廣場二樓28B舖",
  },
  {
    storeId: "wtc-the-wai",
    district: "Sha_Tin",
    nameEn: "The Wai",
    nameTc: "圍方",
    lat: 22.38068,
    lng: 114.195,
    addressEn: "Shop Unit 504, 5/F, The Wai Commercial Development at Tai Wai Station, Shatin, NT",
    addressTc: "沙田大圍車公廟路18號圍方5樓504號舖",
  },
  {
    storeId: "wtc-ma-on-shan-plaza",
    district: "Sha_Tin",
    nameEn: "Ma On Shan",
    nameTc: "馬鞍山",
    lat: 22.38276,
    lng: 114.1954,
    addressEn: "Shop 222-225, Level 2, Ma On Shan Plaza, 608 Sai Sha Road, Ma On Shan, NT",
    addressTc: "馬鞍山西沙路608號馬鞍山廣場第二層222-225號",
  },
  {
    storeId: "wtc-mos-town",
    district: "Sha_Tin",
    nameEn: "MOS Town",
    nameTc: "新港城中心",
    lat: 22.38004,
    lng: 114.19564,
    addressEn: "Shop No.2136, Level 2, MOS Town, Ma On Shan, NT",
    addressTc: "馬鞍山新港城中心2樓2136號舖",
  },
  {
    storeId: "wtc-new-town-plaza",
    district: "Sha_Tin",
    nameEn: "New Town Plaza",
    nameTc: "新城市廣場",
    lat: 22.38212,
    lng: 114.19444,
    addressEn: "Shops 451-453, Level 4, New Town Plaza Phase 1, Shatin, New Territories",
    addressTc: "沙田新城市廣場1期4樓451-453號舖",
  },
  {
    storeId: "wtc-lucky-plaza",
    district: "Sha_Tin",
    nameEn: "Lucky Plaza",
    nameTc: "好運中心商場",
    lat: 22.38012,
    lng: 114.19444,
    addressEn: "Shops 3058, 3087 & 3088, Level 3 Lucky Plaza, 1-15 Wang Pok Street, Sha Tin, NT",
    addressTc: "沙田橫壆街1-15號好運中心商場3樓3058, 3087及3088號舖",
  },
  {
    storeId: "wtc-palazzo",
    district: "Sha_Tin",
    nameEn: "Palazzo",
    nameTc: "御龍山",
    lat: 22.38052,
    lng: 114.19548,
    addressEn: "Shop 102B, The Palazzo, Fo Tan, Shatin, New Territories",
    addressTc: "沙田火炭御龍山102B舖",
  },
  {
    storeId: "wtc-fortune-city-one",
    district: "Sha_Tin",
    nameEn: "Fortune City One",
    nameTc: "置富第一城",
    lat: 22.37908,
    lng: 114.1942,
    addressEn: "Shop G24B, G25 & G26, Fortune City One, City One Shatin, Shatin, NT",
    addressTc: "沙田置富第一城地下G24B, G25-G26舖",
  },
  {
    storeId: "wtc-regentville",
    district: "North",
    nameEn: "Regentville",
    nameTc: "帝庭軒",
    lat: 22.49344,
    lng: 114.12784,
    addressEn: "Shop No. 27-28, 1/F, Regentville Shopping Mall, 8 Wo Mun Street, Fanling, NT",
    addressTc: "粉嶺聯和墟和滿街8號帝庭軒購物商場1樓27-28號舖",
  },
  {
    storeId: "wtc-green-code",
    district: "North",
    nameEn: "Green Code",
    nameTc: "逸峯廣場",
    lat: 22.49296,
    lng: 114.1276,
    addressEn: "Shop G09, G/F, Green Code Plaza, 1 Ma Sik Road, Fanling, NT",
    addressTc: "粉嶺馬適路1號逸峯廣場地下G09號舖",
  },
  {
    storeId: "wtc-tai-wai",
    district: "Sha_Tin",
    nameEn: "Tai Wai",
    nameTc: "大圍",
    lat: 22.38012,
    lng: 114.19428,
    addressEn: "Shop A & B, G/F & Cockloft, Chung Pak Lau, 28-30 Tai Wai Road, Tai Wai, NT",
    addressTc: "沙田大圍路28-30號地下A,B及閣樓",
  },
  {
    storeId: "wtc-spot",
    district: "North",
    nameEn: "Spot",
    nameTc: "上水匯",
    lat: 22.49288,
    lng: 114.12824,
    addressEn: "Shop Nos 206, 213-214, 2/F Spot, 48 Lung Sum Avenue, Sheung Shui, NT",
    addressTc: "上水石湖墟龍琛路48號上水匯2樓206, 213-214號舖",
  },
  {
    storeId: "wtc-choi-yuen-plaza",
    district: "North",
    nameEn: "Choi Yuen Plaza",
    nameTc: "彩園村商場",
    lat: 22.49352,
    lng: 114.12856,
    addressEn: "Shop No. R42 & R43, 3/F, Choi Yuen Plaza, Sheung Shui, N.T.",
    addressTc: "上水彩園商場三樓R42及R43號舖",
  },
  {
    storeId: "wtc-sheung-shui-fu-hing",
    district: "North",
    nameEn: "Sheung Shui",
    nameTc: "上水",
    lat: 22.49344,
    lng: 114.12784,
    addressEn: "G/F & Cockloft, 43-45 Fu Hing Street, Sheung Shui, New Territories",
    addressTc: "上水符興街43-45號地下",
  },
  {
    storeId: "wtc-lok-ma-chau",
    district: "North",
    nameEn: "Lok Ma Chau",
    nameTc: "落馬洲",
    lat: 22.4936,
    lng: 114.12744,
    addressEn: "MTR Station Shop LMC 115 and Storeroom LMC STR 11, Lok Ma Chau Station, NT",
    addressTc: "港鐵落馬洲站LMC 115號舖",
  },
  {
    storeId: "wtc-mayfair-lane",
    district: "Tai_Po",
    nameEn: "Mayfair Lane",
    nameTc: "逸瓏灣",
    lat: 22.44856,
    lng: 114.17064,
    addressEn: "Shop LG 12, 13, 15 LG Floor, Mayfair Lane, 21 Fo Chun Road, Tai Po, NT",
    addressTc: "大埔科進路21號逸瓏灣II地下低層12,13,15號舖",
  },
  {
    storeId: "wtc-landmark-north",
    district: "North",
    nameEn: "Landmark North",
    nameTc: "上水廣場",
    lat: 22.49288,
    lng: 114.12784,
    addressEn: "Shop Nos. 401-402, Level 4 Landmark North, 39 Lung Sum Avenue, Sheung Shui, NT",
    addressTc: "上水石湖墟龍琛路39號上水廣場4樓401-402號舖",
  },
  {
    storeId: "wtc-lok-ma-chau-2",
    district: "North",
    nameEn: "Lok Ma Chau Station 2",
    nameTc: "落馬洲港鐵站2",
    lat: 22.49544,
    lng: 114.1272,
    addressEn: "Shop LMC 207, 208 and Storeroom LMC STR 12, 14, Lok Ma Chau Station, NT",
    addressTc: "港鐵落馬洲站LMC 207, 208號舖",
  },
  {
    storeId: "wtc-tin-ping",
    district: "North",
    nameEn: "Tin Ping Estate",
    nameTc: "天平邨",
    lat: 22.492,
    lng: 114.12736,
    addressEn: "Shops 108 & 120, G/F, Tin Ping Shopping Centre, Tin Ping Estate, Sheung Shui, NT",
    addressTc: "上水天平邨天平商場地下108及120號舖",
  },
  {
    storeId: "wtc-caribbean-square",
    district: "Islands",
    nameEn: "Caribbean Square",
    nameTc: "映灣薈",
    lat: 22.28808,
    lng: 113.945,
    addressEn: "Shop 35, Podium, 1/F, Caribbean Square, 1 Kin Tung Road, Tung Chung, NT",
    addressTc: "東涌健東道1號映灣薈平台1樓35號舖",
  },
  {
    storeId: "wtc-smartland",
    district: "Tsuen_Wan",
    nameEn: "Smartland",
    nameTc: "荃灣",
    lat: 22.37004,
    lng: 114.11556,
    addressEn: "Shop No. 7 G/F Smartland, 16 Tsuen Wah Street, Tsuen Wan, NT",
    addressTc: "荃灣荃華街創意無限廣場7號地舖",
  },
  {
    storeId: "wtc-citywalk-1",
    district: "Tsuen_Wan",
    nameEn: "Citywalk I",
    nameTc: "荃新天地1期",
    lat: 22.37084,
    lng: 114.11452,
    addressEn: "Shop Nos. G57, G59, G61a, G61b & G63, G/F, Citywalk 1, Tsuen Wan, N.T.",
    addressTc: "荃灣楊屋道1號荃新天地1期地下G57, G59, G61a, G61b及G63號舖",
  },
  {
    storeId: "wtc-kolour-tsuen-wan",
    district: "Tsuen_Wan",
    nameEn: "Kolour Tsuen Wan",
    nameTc: "荃灣千色匯",
    lat: 22.36908,
    lng: 114.11428,
    addressEn: "Shop Nos. 2020, 2029 & 2030, 2/F KOLOUR Tsuen Wan 1, 68 Chung On Street, Tsuen Wan, N.T.",
    addressTc: "荃灣眾安街68號荃灣千色匯1期2樓2020, 2029及2030舖",
  },
  {
    storeId: "wtc-soho-west",
    district: "Sham_Shui_Po",
    nameEn: "Soho West",
    nameTc: "Soho West",
    lat: 22.3288,
    lng: 114.1616,
    addressEn: "Shop No. 104, L1, SOHO WEST, 10 Lai Ying Street, Cheung Sha Wan, KL",
    addressTc: "荔枝角荔盈街10號SOHO WEST 1樓104號舖",
  },
  {
    storeId: "wtc-east-point-baby",
    district: "Sai_Kung",
    nameEn: "East Point Baby",
    nameTc: "東港城(Baby)",
    lat: 22.38168,
    lng: 114.27136,
    addressEn: "Shop No. 239, 2/F East Point City, 8 Chung Wa Road, Tseung Kwan O, N.T.",
    addressTc: "將軍澳重華路8號東港城2樓239號舖",
  },
  {
    storeId: "wtc-the-lohas",
    district: "Sai_Kung",
    nameEn: "The Lohas",
    nameTc: "康城",
    lat: 22.38072,
    lng: 114.2716,
    addressEn: "Shop Unit 430, 4/F The Lohas, Tseung Kwan O, N.T.",
    addressTc: "將軍澳康城4樓430號舖",
  },
  {
    storeId: "wtc-leung-king-plaza",
    district: "Tuen_Mun",
    nameEn: "Leung King Plaza",
    nameTc: "良景廣場",
    lat: 22.39212,
    lng: 113.97748,
    addressEn: "Shop L314, Level 3, Leung King Plaza, Tuen Mun, N.T.",
    addressTc: "屯門良景廣場3樓L314號舖",
  },
  {
    storeId: "wtc-queens-hill",
    district: "North",
    nameEn: "Queens Hill Shopping Centre",
    nameTc: "皇后山商場",
    lat: 22.49392,
    lng: 114.12744,
    addressEn: "Shop No. 14, G/F, Queens Hill Shopping Centre, Queens Hill Estate, Fanling",
    addressTc: "粉嶺皇后山村皇后山商場地下14號舖",
  },
  {
    storeId: "wtc-science-park",
    district: "Sha_Tin",
    nameEn: "Science Park",
    nameTc: "科學園",
    lat: 22.3798,
    lng: 114.19532,
    addressEn: "Unit S046B, G/F Building 10W Phase Two, Hong Kong Science Park, Pak Shek Kok, NT",
    addressTc: "香港科學園10W大樓2期地下S046B號舖",
  },
  {
    storeId: "wtc-rua-campo",
    district: "Macau",
    nameEn: "Rua Campo",
    nameTc: "水坑尾",
    lat: 22.1967,
    lng: 113.5439,
    addressEn: "Rua Campo No.62-92, Ljs. A,B,C,D, China Const. Com. Building, Macau",
    addressTc: "澳門水坑尾街62-92號地下A,B,C,D舖",
  },
  {
    storeId: "wtc-three-lamps",
    district: "Macau",
    nameEn: "Three Lamps",
    nameTc: "三盞燈",
    lat: 22.19782,
    lng: 113.54446,
    addressEn: "6A Rotunda De Carlos Da Maia, Macau",
    addressTc: "澳門嘉路米耶圓地添運大廈6A地下B,C舖",
  },
  {
    storeId: "wtc-largo-senado",
    district: "Macau",
    nameEn: "Largo Senado",
    nameTc: "議事亭",
    lat: 22.19702,
    lng: 113.54446,
    addressEn: "Largo Senado No. 11, Shun Tak House, G/F to 3/F, Macau",
    addressTc: "澳門議事亭前地11號信德堡地下及1-3樓",
  },
  {
    storeId: "wtc-costa",
    district: "Macau",
    nameEn: "Costa",
    nameTc: "世紀豪庭",
    lat: 22.20038,
    lng: 113.54398,
    addressEn: "Avenida De Horta E Costa, Millennium Court, Res-do-chao B, Macau",
    addressTc: "澳門高士德大馬路世紀豪庭地下B座",
  },
  {
    storeId: "wtc-the-londoner",
    district: "Macau",
    nameEn: "The Londoner",
    nameTc: "倫敦人",
    lat: 22.19942,
    lng: 113.54438,
    addressEn: "Shops 2230, 2231 & 2232, Level 2, Cotai, Macau",
    addressTc: "澳門倫敦人購物中心2樓2230, 2231及2232號舖",
  },
  {
    storeId: "wtc-nam-fai-building",
    district: "Macau",
    nameEn: "Nam Fai Building",
    nameTc: "南暉",
    lat: 22.19806,
    lng: 113.54326,
    addressEn: "Rua Da Serenidade No.82, Nam Fai, Macau",
    addressTc: "澳門永定街82號南暉地下S座, AO座及AN座",
  },
  {
    storeId: "wtc-parisian-macao",
    district: "Macau",
    nameEn: "Shoppes at Parisian",
    nameTc: "澳門巴黎人",
    lat: 22.19718,
    lng: 113.54438,
    addressEn: "Shop 3549, Level 5, Shoppes at Parisian, The Parisian Macao, Cotai, Macau",
    addressTc: "澳門巴黎人購物中心5樓3549號舖",
  },
  {
    storeId: "wtc-hoi-pan-fa-un",
    district: "Macau",
    nameEn: "Hoi Pan Fa Un",
    nameTc: "海濱花園",
    lat: 22.19838,
    lng: 113.54358,
    addressEn: "Rua Do Canal Novo Nos 62-64, Hoi Pan Fa Un Bloco XI, Macau",
    addressTc: "澳門涌河新街62-64號海濱花園第11座地下",
  },
  {
    storeId: "wtc-venetian-exp",
    district: "Macau",
    nameEn: "Venetian exp",
    nameTc: "威尼斯人度假村酒店exp",
    lat: 22.19894,
    lng: 113.54358,
    addressEn: "Shop 2016 & 2017a, Level 3, Shoppes at Venetian, Taipa, Macau",
    addressTc: "澳門威尼斯人購物中心三樓2016及2017a號舖",
  },
  {
    storeId: "wtc-venetian",
    district: "Macau",
    nameEn: "Venetian",
    nameTc: "威尼斯人度假村酒店",
    lat: 22.19942,
    lng: 113.54374,
    addressEn: "Shop 2025 & 2026, Level 3, Shoppes at Venetian, Taipa, Macau",
    addressTc: "澳門威尼斯人購物中心三樓2025及2026號舖",
  },
  {
    storeId: "wtc-studio-city",
    district: "Macau",
    nameEn: "Studio City",
    nameTc: "新濠影匯",
    lat: 22.20054,
    lng: 113.54374,
    addressEn: "Shop L1095 & L1097, Level 1, The Boulevard at Studio City, Cotai, Macau",
    addressTc: "澳門路氹連貫公路新濠影匯購物大道一樓L1095及L1097號舖",
  },
] as const;

export type WatsonsStoreLocation = (typeof WATSONS_STORE_LOCATIONS)[number];
